// Code generated by scripts/generate-findings-registry.mjs from
// standards/findings-registry.yaml. DO NOT EDIT — edit the YAML and run
// `make generate`.

// Package findings is the generated registry of finding producers and kinds
// (asset-inventory ADR-0005 D3). Every row in the findings table carries a
// producer and a kind from this registry; there is no CHECK constraint, so
// Validate is the enforcement point.
package findings

import "fmt"

// Producer keys.
const (
	ProducerCompliance    = "compliance"
	ProducerCrypto        = "crypto"
	ProducerEOL           = "eol"
	ProducerVulnerability = "vulnerability"
	ProducerConfiguration = "configuration"
	ProducerHygiene       = "hygiene"
	ProducerDrift         = "drift"
)

// Kind keys. Unique across the whole registry, not just within a producer.
const (
	KindControlNoncompliant       = "control_noncompliant"
	KindWeakConfiguration         = "weak_configuration"
	KindWeakCertificate           = "weak_certificate"
	KindPQCVulnerable             = "pqc_vulnerable"
	KindOSEndOfLife               = "os_end_of_life"
	KindSoftwareEndOfLife         = "software_end_of_life"
	KindHardwareEndOfSupport      = "hardware_end_of_support"
	KindKnownVulnerability        = "known_vulnerability"
	KindPlaintextManagement       = "plaintext_management"
	KindDefaultCredentialsExposed = "default_credentials_exposed"
	KindInsecureServiceExposed    = "insecure_service_exposed"
	KindNoOwner                   = "no_owner"
	KindNoClass                   = "no_class"
	KindNoLocation                = "no_location"
	KindDuplicateSuspected        = "duplicate_suspected"
	KindStale                     = "stale"
	KindOrphanRelationship        = "orphan_relationship"
	KindNewClassInSegment         = "new_class_in_segment"
	KindUnexpectedProtocol        = "unexpected_protocol"
	KindPortProfileChanged        = "port_profile_changed"
	KindNewIssuer                 = "new_issuer"
)

// Subject types. The shared vocabulary for what a finding (or a ticket, or an
// alert) is about.
const (
	SubjectAsset               = "asset"
	SubjectEndpoint            = "endpoint"
	SubjectCertificate         = "certificate"
	SubjectKey                 = "key"
	SubjectCryptoConfiguration = "crypto_configuration"
	SubjectSoftwareInstall     = "software_install"
	SubjectRelationship        = "relationship"
	SubjectControl             = "control"
	SubjectFramework           = "framework"
)

// Rung is one step of a ladder severity model. Rungs are ordered worst-last.
type Rung struct {
	Threshold string `json:"threshold"`
	Severity  string `json:"severity"`
	Score     int    `json:"score"`
}

// Producer is one finding producer: a subsystem that judges facts against a
// catalogue or a rule set.
type Producer struct {
	Key         string `json:"key"`
	Label       string `json:"label"`
	Catalogue   string `json:"catalogue"`
	Description string `json:"description"`
}

// Kind is one finding kind a producer may emit.
type Kind struct {
	Producer        string   `json:"producer"`
	Key             string   `json:"key"`
	SeverityModel   string   `json:"severity_model"`
	DefaultSeverity string   `json:"default_severity,omitempty"`
	Score           int      `json:"score"`
	ScoreSource     string   `json:"score_source"`
	Rungs           []Rung   `json:"rungs,omitempty"`
	SubjectTypes    []string `json:"subject_types"`
	FeedsRisk       bool     `json:"feeds_risk"`
	TitleTemplate   string   `json:"title_template"`

	// Guidance is the customer-facing remediation text for this kind: what a
	// person does about a finding of this kind, generic to the kind and never
	// to one instance.
	//
	// It is the REMEDIATOR seam's null default (ADR-0008 D1). A deployment
	// with no model configured answers "draft me a remediation plan" with
	// exactly this string, so it has to stand on its own — it is not a
	// placeholder for something an AI would say better, it is the answer.
	//
	// Deliberately NOT [Kind.Description], which is written for us and carries
	// internal history, table names and workstream numbers. None of that
	// belongs in front of a tenant, and none of it belongs in a prompt.
	Guidance string `json:"guidance"`

	Description string `json:"description"`
}

// Producers is the generated producer list, in YAML order.
var Producers = []Producer{
	{
		Key:         "compliance",
		Label:       "Compliance",
		Catalogue:   "frameworks",
		Description: "Evaluates activated framework controls against tenant inventory and records the controls that fail.",
	},
	{
		Key:         "crypto",
		Label:       "Cryptography",
		Catalogue:   "algorithms",
		Description: "Judges observed cryptographic posture — negotiated configurations, certificates and their algorithms — against the algorithms catalogue.",
	},
	{
		Key:         "eol",
		Label:       "End of life",
		Catalogue:   "eol_catalogue",
		Description: "Compares observed operating systems, software and hardware against the end-of-life catalogue.",
	},
	{
		Key:         "vulnerability",
		Label:       "Vulnerability",
		Catalogue:   "vulnerability_catalogue",
		Description: "Matches installed software against the mirrored vulnerability catalogue by CPE and Package URL.",
	},
	{
		Key:         "configuration",
		Label:       "Configuration",
		Catalogue:   "configuration_rules",
		Description: "Judges how a device is managed and what it exposes, from endpoint and interrogation facts, against the configuration rule table.",
	},
	{
		Key:         "hygiene",
		Label:       "Inventory hygiene",
		Catalogue:   "none",
		Description: "Reports gaps in the inventory itself — missing ownership, missing classification, suspected duplicates, stale records. Data quality, not security: nothing here feeds risk.",
	},
	{
		Key:         "drift",
		Label:       "Drift",
		Catalogue:   "none",
		Description: "Compares the current population of a segment or an asset against its recent baseline window and reports what changed. Rule-based defaults first; the ADR-0008 drift seam may propose more later.",
	},
}

// All is the generated finding-kind list, in YAML order.
var All = []Kind{
	{
		Producer:        "compliance",
		Key:             "control_noncompliant",
		SeverityModel:   "fixed",
		DefaultSeverity: "from-control",
		Score:           0,
		ScoreSource:     "fixed",
		Rungs:           nil,
		SubjectTypes:    []string{"asset", "certificate"},
		FeedsRisk:       false,
		TitleTemplate:   "Control {subject} is noncompliant",
		Guidance:        "Open the control to see which measurement failed and what it expected. Fix the underlying object — the asset or the certificate the measurement was taken on — and the next evaluation closes the finding. Where the requirement genuinely does not apply here, record a control override with a rationale rather than leaving the finding open.",
		Description:     "A published framework's control failed evaluation against one concrete object. The subject is the object the measurement was taken on — the asset, or the certificate — and `control_id` names the control it failed. One finding per (control, subject) pair, which is the granularity a tenant triages, assigns and raises a ticket at.\nWritten as `[control]` when the registry first landed, before the writer moved (workstream 3.1). A control-subject finding cannot be reached by `finding:(…)` from an asset, cannot be counted by the `has_findings` facet, and cannot carry a per-asset assignment — all three are live product surfaces, so the subject is the object, not the control.\nThe retired compliance table's three-value asset-kind CHECK maps onto TWO: network_asset → asset, crypto_implementation → asset, certificate → certificate. `asset_type` there named the measurement KIND, not the type of the id beside it — `asset_id` was always the asset's for the first two — so renaming the third value to `crypto_configuration` would have made every one of those rows claim to point at a `crypto_implementations.id` it has never held. A configuration measurement is scoped and selected per ASSET; the configurations it was taken over travel in `evidence.crypto_implementation_ids`.\n`crypto_configuration` is RESERVED for the `configuration` producer below (workstream 3.5), which measures one configuration at a time and carries its id. Do not add it back here without a writer that actually puts a crypto_implementations.id in subject_id.\nDoes not feed the per-asset risk rollup: compliance is scored by the framework score, and double-counting a control across every asset it touches would swamp the rollup.",
	},
	{
		Producer:        "crypto",
		Key:             "weak_configuration",
		SeverityModel:   "fixed",
		DefaultSeverity: "from-catalogue",
		Score:           0,
		ScoreSource:     "catalogue",
		Rungs:           nil,
		SubjectTypes:    []string{"crypto_configuration", "endpoint"},
		FeedsRisk:       true,
		TitleTemplate:   "{subject} {detail}",
		Guidance:        "Review the component or rule named in the finding. Move weak or acceptable components to strong or recommended alternatives: disable the obsolete protocol version, remove the cipher suite from the server's list, or move the key exchange to a modern curve. Change it on the service itself, not on the client — a client-side workaround leaves the endpoint willing to negotiate the weak option with anything else that asks. Re-scan the endpoint afterwards to confirm the new negotiation.",
		Description:     "A crypto configuration negotiates a protocol version, cipher suite, key exchange, signature, symmetric or hash algorithm the catalogue rates weak or acceptable, or an applicable key-size/hash rule fails. Weakness chooses the weak title; acceptable-only names that rating. Strong/recommended components alone emit nothing. The numeric score retains the maximum catalogue, persisted configuration and applicable rule assessment; severity follows from banding that score. Never hardcode a second opinion here — edit the catalogue row.",
	},
	{
		Producer:        "crypto",
		Key:             "weak_certificate",
		SeverityModel:   "fixed",
		DefaultSeverity: "from-catalogue",
		Score:           0,
		ScoreSource:     "catalogue",
		Rungs:           nil,
		SubjectTypes:    []string{"certificate"},
		FeedsRisk:       true,
		TitleTemplate:   "{subject} {detail}",
		Guidance:        "Reissue the certificate with a key and signature algorithm the catalogue rates strong or recommended. Address any key-size/hash failure, and use SHA-256 or better for the signature. Replace it everywhere it is deployed, then revoke the old one so a copy left on another host cannot still be used.",
		Description:     "A certificate's key algorithm, key size or signature algorithm is rated weak or acceptable by the catalogue, or fails a size/hash rule. The title follows strength independently of numeric risk; incomplete historical evidence retains the prior finding pending reassessment. Expiry is an alert (certificate_expiring), not a finding.",
	},
	{
		Producer:        "crypto",
		Key:             "pqc_vulnerable",
		SeverityModel:   "fixed",
		DefaultSeverity: "medium",
		Score:           40,
		ScoreSource:     "fixed",
		Rungs:           nil,
		SubjectTypes:    []string{"crypto_configuration", "certificate", "key"},
		FeedsRisk:       true,
		TitleTemplate:   "{subject} is vulnerable to quantum attack",
		Guidance:        "Plan a migration to a post-quantum or hybrid algorithm for this subject. Nothing here is broken today: NIST IR 8547 deprecates these primitives in 2030 and disallows them in 2035, so the work is inventory-led — confirm what depends on this key or configuration, check whether the software and the peers support a PQC or hybrid option yet, and schedule the change. Long-lived data protected by this key is the part to prioritise.",
		Description:     "The subject uses a classical asymmetric primitive broken by Shor's algorithm (signature, kem, key-agree, pke) per NIST IR 8547. Classification is the denylist in pqc_readiness.go — a subject not classified is unclassified, never assumed safe.",
	},
	{
		Producer:        "eol",
		Key:             "os_end_of_life",
		SeverityModel:   "ladder",
		DefaultSeverity: "",
		Score:           0,
		ScoreSource:     "ladder",
		Rungs:           []Rung{{Threshold: "within 90 days of end of life", Severity: "low", Score: 30}, {Threshold: "past end of life", Severity: "high", Score: 70}, {Threshold: "past end of life by more than 365 days", Severity: "critical", Score: 90}},
		SubjectTypes:    []string{"asset"},
		FeedsRisk:       true,
		TitleTemplate:   "{subject} runs an end-of-life operating system ({detail})",
		Guidance:        "Upgrade the operating system to a release that is still supported, or move the workload to a host that runs one. An end-of-life OS receives no security fixes, so the exposure grows with every advisory published after the date. Where an upgrade is genuinely blocked, isolate the host and record the compensating controls.",
		Description:     "The asset's os.name/os.version facts resolve to a catalogue entry whose end-of-life date has passed or is approaching. Escalates as the date recedes.",
	},
	{
		Producer:        "eol",
		Key:             "software_end_of_life",
		SeverityModel:   "ladder",
		DefaultSeverity: "",
		Score:           0,
		ScoreSource:     "ladder",
		Rungs:           []Rung{{Threshold: "within 90 days of end of life", Severity: "low", Score: 20}, {Threshold: "past end of life", Severity: "medium", Score: 50}, {Threshold: "past end of life by more than 365 days", Severity: "high", Score: 75}},
		SubjectTypes:    []string{"software_install"},
		FeedsRisk:       true,
		TitleTemplate:   "{subject} is end of life ({detail})",
		Guidance:        "Upgrade the package to a supported version, or remove it if nothing still needs it. Check what depends on it first — an end-of-life library is often pulled in by something else, and upgrading the dependent is the real fix.",
		Description:     "An installed software product has passed, or is approaching, its catalogue end-of-life date. Scored below OS end-of-life because the blast radius of one package is narrower than the platform it runs on.",
	},
	{
		Producer:        "eol",
		Key:             "hardware_end_of_support",
		SeverityModel:   "ladder",
		DefaultSeverity: "",
		Score:           0,
		ScoreSource:     "ladder",
		Rungs:           []Rung{{Threshold: "within 180 days of end of support", Severity: "low", Score: 20}, {Threshold: "past end of support", Severity: "medium", Score: 50}, {Threshold: "past end of support by more than 365 days", Severity: "high", Score: 70}},
		SubjectTypes:    []string{"asset"},
		FeedsRisk:       true,
		TitleTemplate:   "{subject} hardware is past vendor support ({detail})",
		Guidance:        "Plan the hardware refresh. Past end of support the vendor issues no further firmware fixes, so a future advisory against this model has no remedy. Until it is replaced, keep it off management networks reachable from anywhere untrusted.",
		Description:     "The asset's hw.vendor/hw.model facts resolve to a catalogue entry whose end-of-support date has passed or is approaching. Unsupported hardware stops receiving firmware fixes.",
	},
	{
		Producer:        "vulnerability",
		Key:             "known_vulnerability",
		SeverityModel:   "fixed",
		DefaultSeverity: "from-catalogue",
		Score:           0,
		ScoreSource:     "cvss_x10",
		Rungs:           nil,
		SubjectTypes:    []string{"software_install", "asset"},
		FeedsRisk:       true,
		TitleTemplate:   "{subject} is affected by {detail}",
		Guidance:        "Apply the vendor's fixed version for this advisory. Where a patch is not available yet, apply the vendor's documented mitigation and re-check when one ships. Confirm afterwards that the installed version really changed — the finding closes on the next inventory pass, not on the change ticket.",
		Description:     "An installed software version matches a catalogue advisory by CPE or PURL. Score is the CVSS base score x10 (the convention models.RiskBands is anchored to), so severity bands land on the CVSS qualitative ratings. A CVE with no CVSS score scores 0 and is reported as not scored, never as harmless.",
	},
	{
		Producer:        "configuration",
		Key:             "plaintext_management",
		SeverityModel:   "fixed",
		DefaultSeverity: "high",
		Score:           70,
		ScoreSource:     "fixed",
		Rungs:           nil,
		SubjectTypes:    []string{"asset", "endpoint"},
		FeedsRisk:       true,
		TitleTemplate:   "{subject} is managed over a plaintext protocol ({detail})",
		Guidance:        "Move management onto the encrypted equivalent — SSH instead of Telnet, HTTPS instead of HTTP, SFTP instead of FTP, SNMPv3 instead of v1 or v2c — and then disable the plaintext service so it cannot be reached at all. Treat any credential used over the plaintext service as exposed and rotate it.",
		Description:     "The asset's management plane runs over a protocol with no transport confidentiality — Telnet, HTTP, FTP, SNMP v1/v2c. Credentials and configuration cross the network in the clear.",
	},
	{
		Producer:        "configuration",
		Key:             "default_credentials_exposed",
		SeverityModel:   "fixed",
		DefaultSeverity: "critical",
		Score:           90,
		ScoreSource:     "fixed",
		Rungs:           nil,
		SubjectTypes:    []string{"asset", "endpoint"},
		FeedsRisk:       true,
		TitleTemplate:   "{subject} accepts default credentials",
		Guidance:        "Change the credential now, on the device itself, and then check whether the same default is in use anywhere else. A vendor default is published, so assume it has been tried. Where the device allows it, disable the default account rather than only changing its password.",
		Description:     "A management endpoint accepted a documented vendor default credential. The finding records that it was accepted; it never records the credential itself (see \"Collect posture, never key material\").",
	},
	{
		Producer:        "configuration",
		Key:             "insecure_service_exposed",
		SeverityModel:   "fixed",
		DefaultSeverity: "medium",
		Score:           50,
		ScoreSource:     "fixed",
		Rungs:           nil,
		SubjectTypes:    []string{"endpoint"},
		FeedsRisk:       true,
		TitleTemplate:   "{subject} exposes an insecure service ({detail})",
		Guidance:        "Close the port, bind the service to a management interface, or put it behind an authenticating proxy. Decide first whether the service is needed on this segment at all — the cheapest fix is usually removing an exposure nobody was using.",
		Description:     "An endpoint listens on a service the rule table rates as unsafe to expose on this segment — an unauthenticated database port, a debug interface, a legacy file-sharing protocol.",
	},
	{
		Producer:        "hygiene",
		Key:             "no_owner",
		SeverityModel:   "fixed",
		DefaultSeverity: "low",
		Score:           0,
		ScoreSource:     "fixed",
		Rungs:           nil,
		SubjectTypes:    []string{"asset"},
		FeedsRisk:       false,
		TitleTemplate:   "{subject} has no owner",
		Guidance:        "Set an owner email or a support group on the asset. An unowned asset has nobody to send a finding to, which is what makes it the one that stays unfixed.",
		Description:     "An asset has no owner_email and no support_group.",
	},
	{
		Producer:        "hygiene",
		Key:             "no_class",
		SeverityModel:   "fixed",
		DefaultSeverity: "low",
		Score:           0,
		ScoreSource:     "fixed",
		Rungs:           nil,
		SubjectTypes:    []string{"asset"},
		FeedsRisk:       false,
		TitleTemplate:   "{subject} is unclassified",
		Guidance:        "Classify the asset, or add an identification rule that classifies this shape of asset automatically. An unclassified asset is invisible to class facets and to every class-scoped policy, so it is silently excluded from work it should be part of.",
		Description:     "An asset has no class, or sits on a placeholder class the classifier could not refine. An unclassified asset is invisible to class facets and to any class-scoped policy.",
	},
	{
		Producer:        "hygiene",
		Key:             "no_location",
		SeverityModel:   "fixed",
		DefaultSeverity: "low",
		Score:           0,
		ScoreSource:     "fixed",
		Rungs:           nil,
		SubjectTypes:    []string{"asset"},
		FeedsRisk:       false,
		TitleTemplate:   "{subject} has no location",
		Guidance:        "Record a site, region or zone on the asset. Location is what turns a finding into a work order somebody can act on, and it is what scopes an exposure to a building or a plant.",
		Description:     "An asset has no site, region, zone or location record.",
	},
	{
		Producer:        "hygiene",
		Key:             "duplicate_suspected",
		SeverityModel:   "fixed",
		DefaultSeverity: "medium",
		Score:           0,
		ScoreSource:     "fixed",
		Rungs:           nil,
		SubjectTypes:    []string{"asset"},
		FeedsRisk:       false,
		TitleTemplate:   "{subject} may be a duplicate of {detail}",
		Guidance:        "Compare the two records and either merge them through the Approvals queue or record why they are genuinely different. Leaving both means every count that involves this asset is wrong by one, in a direction nobody can see.",
		Description:     "The identification engine found two assets sharing an identifier but disagreeing on others, so it did not merge them. The merge proposal goes to Approvals; this finding is how it surfaces in the inventory.",
	},
	{
		Producer:        "hygiene",
		Key:             "stale",
		SeverityModel:   "ladder",
		DefaultSeverity: "",
		Score:           0,
		ScoreSource:     "ladder",
		Rungs:           []Rung{{Threshold: "not seen for 30 days", Severity: "low", Score: 0}, {Threshold: "not seen for 90 days", Severity: "medium", Score: 0}, {Threshold: "not seen for 180 days", Severity: "high", Score: 0}},
		SubjectTypes:    []string{"asset", "endpoint", "software_install"},
		FeedsRisk:       false,
		TitleTemplate:   "{subject} has not been seen for {detail}",
		Guidance:        "Confirm whether the subject still exists. If it does, find out why no collector has seen it — a decommissioned sensor, a changed network path, or an agent that stopped reporting. If it does not, archive the record so it stops being counted as part of the estate.",
		Description:     "No collector has observed the subject within the freshness window. Stale records are the main way an inventory silently becomes wrong; escalating rungs prompt an archive decision.",
	},
	{
		Producer:        "hygiene",
		Key:             "orphan_relationship",
		SeverityModel:   "fixed",
		DefaultSeverity: "low",
		Score:           0,
		ScoreSource:     "fixed",
		Rungs:           nil,
		SubjectTypes:    []string{"relationship"},
		FeedsRisk:       false,
		TitleTemplate:   "Relationship {subject} points at a missing asset",
		Guidance:        "Delete the relationship, or restore the asset it points at if it was archived by mistake. An edge to a missing asset makes dependency views read as complete when they are not.",
		Description:     "A relationship edge references an asset that has been archived or deleted. The edge is kept so the history stays readable, but it should be resolved.",
	},
	{
		Producer:        "drift",
		Key:             "new_class_in_segment",
		SeverityModel:   "fixed",
		DefaultSeverity: "medium",
		Score:           30,
		ScoreSource:     "fixed",
		Rungs:           nil,
		SubjectTypes:    []string{"asset"},
		FeedsRisk:       true,
		TitleTemplate:   "{subject} is the first {detail} seen in its network segment",
		Guidance:        "Confirm whether the asset belongs on this segment. If it does, nothing needs fixing and the finding can be resolved. If it does not, move it — an unexpected class on a segment is usually either a misconfigured port or something nobody meant to plug in.",
		Description:     "An asset of a class never before seen in this network segment was observed. A printer on a server VLAN is worth a look; an OT device on a corporate VLAN is worth a call.",
	},
	{
		Producer:        "drift",
		Key:             "unexpected_protocol",
		SeverityModel:   "fixed",
		DefaultSeverity: "medium",
		Score:           40,
		ScoreSource:     "fixed",
		Rungs:           nil,
		SubjectTypes:    []string{"asset", "endpoint"},
		FeedsRisk:       true,
		TitleTemplate:   "{subject} started speaking {detail}",
		Guidance:        "Find out what started using the protocol and whether it was a planned change. A newly-appearing plaintext or remote-access protocol is the case worth chasing; where it was intentional, resolve the finding so the baseline picks the new behaviour up.",
		Description:     "An asset began using a protocol it has not used in the baseline window. Newly-appearing plaintext or remote-access protocols are the cases that matter.",
	},
	{
		Producer:        "drift",
		Key:             "port_profile_changed",
		SeverityModel:   "fixed",
		DefaultSeverity: "low",
		Score:           20,
		ScoreSource:     "fixed",
		Rungs:           nil,
		SubjectTypes:    []string{"asset"},
		FeedsRisk:       true,
		TitleTemplate:   "{subject}'s listening ports changed ({detail})",
		Guidance:        "Compare the current listening ports against what this asset is supposed to run, and confirm the change was planned. Ports opening is the signal to chase first, but a port closing unexpectedly can mean a service has failed rather than been removed.",
		Description:     "The set of listening sockets on an asset differs from its baseline. Ports opening is the signal; ports closing is recorded but scored the same because either direction can mean an unplanned change.",
	},
	{
		Producer:        "drift",
		Key:             "new_issuer",
		SeverityModel:   "fixed",
		DefaultSeverity: "medium",
		Score:           30,
		ScoreSource:     "fixed",
		Rungs:           nil,
		SubjectTypes:    []string{"certificate", "asset"},
		FeedsRisk:       true,
		TitleTemplate:   "{subject} presented a certificate from a new issuer ({detail})",
		Guidance:        "Confirm the new issuer is one you chose. A planned CA migration explains it and the finding can be resolved; an issuer nobody recognises on a connection that should be direct is what an interception looks like, and is worth treating as one until it is explained.",
		Description:     "A certificate was observed from an issuer not seen for this subject in the baseline window. A changed issuer is either a planned CA migration or an interception.",
	},
}

// SubjectTypes is the shared finding-subject vocabulary, in YAML order.
var SubjectTypes = []string{"asset", "endpoint", "certificate", "key", "crypto_configuration", "software_install", "relationship", "control", "framework"}

// OpenQuery is what "open" means, in the query language, in ONE place.
//
// Both halves are load-bearing. `detection_state` is the finding's own
// lifecycle — is the condition still detected? INACTIVE means it went away —
// and `workflow_status` is the human one: has anybody dealt with it? Counting
// only the first includes findings someone already signed off; counting only the
// second includes findings that have since been fixed.
//
// The inventory `has_findings` facet COMPILES this text to produce its count,
// and the facet rail WRITES it when its checkbox is ticked, so the number and
// the list it leads to are one predicate rather than two spellings of an
// intention. The TypeScript half is OPEN_FINDINGS_QUERY, generated from the same
// line of YAML.
const OpenQuery = "finding:(detection_state:ACTIVE and workflow_status not in (RESOLVED, SUPPRESSED))"

// Get returns the registry entry for a producer and kind. The second result is
// false when the pair is not registered.
func Get(producer, kind string) (Kind, bool) {
	for _, k := range All {
		if k.Producer == producer && k.Key == kind {
			return k, true
		}
	}
	return Kind{}, false
}

// GetProducer returns the registry entry for a producer key.
func GetProducer(producer string) (Producer, bool) {
	for _, p := range Producers {
		if p.Key == producer {
			return p, true
		}
	}
	return Producer{}, false
}

// Validate reports whether a finding may be written: the producer and kind
// must be registered together, and the subject type must be one the kind
// allows. This is the enforcement point — the findings table has no CHECK.
func Validate(producer, kind, subjectType string) error {
	k, ok := Get(producer, kind)
	if !ok {
		if _, producerKnown := GetProducer(producer); !producerKnown {
			return fmt.Errorf("findings: unknown producer %q", producer)
		}
		return fmt.Errorf("findings: producer %q does not emit kind %q", producer, kind)
	}
	for _, s := range k.SubjectTypes {
		if s == subjectType {
			return nil
		}
	}
	return fmt.Errorf(
		"findings: kind %q/%q cannot be about subject type %q (allowed: %v)",
		producer, kind, subjectType, k.SubjectTypes)
}

// GuidanceFor returns the customer-facing remediation guidance for a producer
// and kind, and false when the pair is not registered.
//
// The false is not decoration. It is what stops an unregistered kind being
// answered with an empty string that reads, in a UI or in a plan draft, like
// "there is nothing to do about this" — which is the not-assessed-rendered-as-
// assessed shape ADR-0008 D4.3 is written against.
func GuidanceFor(producer, kind string) (string, bool) {
	k, ok := Get(producer, kind)
	if !ok {
		return "", false
	}
	return k.Guidance, true
}

// FeedsRisk reports whether a producer and kind contribute to the asset risk
// rollup. An unregistered pair feeds nothing — callers that care about the
// difference between "does not feed risk" and "not registered" use Validate.
func FeedsRisk(producer, kind string) bool {
	k, ok := Get(producer, kind)
	return ok && k.FeedsRisk
}
