/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/scopes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List scopes for the current tenant
         * @description Returns all non-deleted scopes for the tenant. Lazily seeds the three system defaults (All / Production / Non-Dev-Test) on the first call for a tenant.
         */
        get: operations["listScopes"];
        put?: never;
        /** Create a scope */
        post: operations["createScope"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scopes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Scope UUID. */
                id: components["parameters"]["ScopeId"];
            };
            cookie?: never;
        };
        /** Get a scope by id */
        get: operations["getScope"];
        /**
         * Update a scope
         * @description Overwrites name/description/predicate. Version is bumped (and an audit row written) only when name or predicate actually changed.
         */
        put: operations["updateScope"];
        post?: never;
        /**
         * Soft-delete a scope
         * @description Soft-deletes a non-system scope. System scopes (All / Production / Non-Dev-Test) cannot be deleted and return 409.
         */
        delete: operations["deleteScope"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scopes/{id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Scope UUID. */
                id: components["parameters"]["ScopeId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview the assets a scope matches
         * @description Phase 1 stub — echoes the predicate with a not_implemented preview. Phase 2 resolves the predicate against inventory-service and returns a matched asset count.
         */
        post: operations["previewScope"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cbom/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate a new CBOM artifact from a scope
         * @description Snapshots inventory matching `scope_id` as of now and writes one
         *     immutable, hashed (and optionally HMAC-signed + compliance-attested)
         *     artifact row.
         *
         *     Phase 2 generation is **synchronous-but-quick** despite the 202
         *     response code: by the time the call returns the artifact row is
         *     committed and `GET /cbom/artifacts/{id}` will return it. The 202 +
         *     `status: "ready"` shape is preserved so consumers don't need to
         *     change if generation moves to a queue in the future.
         */
        post: operations["generateCBOMArtifact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cbom/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List CBOM artifacts for the current tenant
         * @description Returns non-deleted artifacts ordered by `generated_at` DESC.
         *
         *     `limit` defaults to 50 and is clamped to 200. Values below 1 or
         *     non-numeric are rejected with 400. `scope_id` filters server-side.
         */
        get: operations["listCBOMArtifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cbom/artifacts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description CBOM artifact UUID. */
                id: components["parameters"]["ArtifactId"];
            };
            cookie?: never;
        };
        /** Get a CBOM artifact by id */
        get: operations["getCBOMArtifact"];
        put?: never;
        post?: never;
        /**
         * Soft-delete a CBOM artifact
         * @description Soft delete only. The row is retained so dangling references from comparison runs surface as "deleted by X" rather than 404.
         */
        delete: operations["softDeleteCBOMArtifact"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cbom/artifacts/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description CBOM artifact UUID. */
                id: components["parameters"]["ArtifactId"];
            };
            cookie?: never;
        };
        /**
         * Download the artifact bytes in a chosen format
         * @description Returns the artifact rendered in the requested wire format.
         *
         *     - `cyclonedx` (default) → the artifact's canonical CycloneDX JSON, byte-stable
         *       against `content_hash`. Inline-stored artifacts stream the bytes
         *       directly with `Content-Type: application/vnd.cyclonedx+json`;
         *       object-stored artifacts return a 302 redirect to a presigned URL.
         *     - `spdx` → SPDX 2.3 JSON projection (re-rendered from canonical bytes).
         *       **Enterprise edition only.**
         *     - `pdf` → PDF rendering for human review (re-rendered from canonical
         *       bytes). **Enterprise edition only.**
         *
         *     SPDX and PDF re-render server-side and therefore need the raw bytes
         *     to be loadable. Inline-stored artifacts read from
         *     `cbom_artifacts.inline_content` directly; object-stored artifacts stream
         *     the bytes via `shared/storage.Stream()` (wired through
         *     `cbom/storage_read.go::ReadStoredBytes`). The handler returns 500 only
         *     when storage is mis-wired or the underlying bytes can't be fetched.
         *
         *     Edition and entitlement boundary: `cyclonedx` is served by every
         *     edition — it is the CBOM standard and the form `content_hash` refers
         *     to. `spdx` and `pdf` need both the Enterprise renderer and the
         *     tenant's `cbom_signing` entitlement; otherwise the handler returns
         *     **402**. The `format` enum is edition-independent on purpose, so
         *     clients can tell "valid format, wrong edition/subscription" (402)
         *     from "unknown format" (400).
         */
        get: operations["downloadCBOMArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cbom/artifacts/{id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description CBOM artifact UUID. */
                id: components["parameters"]["ArtifactId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recompute hash and (if signed) signature for an artifact
         * @description Loads the artifact's canonical bytes (from inline content or storage),
         *     re-hashes them, and compares to the row's `content_hash`. When the
         *     artifact was signed and a signer is configured **and** the hash check
         *     passed, also re-derives the HMAC and compares.
         *
         *     When bytes can't be loaded (no inline content and no storage wired)
         *     the call still returns 200 with `hash_valid` and `signature_checked`
         *     false — the UI greys the result rather than erroring.
         */
        post: operations["verifyCBOMArtifact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cbom/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Diff two CBOM artifacts (request-body form)
         * @description Computes a structured diff between two artifacts of the same tenant.
         *     Artifacts are immutable, so the result is deterministic for any
         *     (base_id, head_id) pair; Phase 3 recomputes on demand (no cache).
         *
         *     Component-level matching aligns on purl / OID / fingerprint /
         *     type+name; each change is categorized `improvement` / `regression` /
         *     `drift` / `neutral` with a one-phrase reason.
         *
         *     Requires the tenant's `cbom_signing` entitlement.
         */
        post: operations["compareCBOMArtifacts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cbom/compare/{base}/{head}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                base: string;
                head: string;
            };
            cookie?: never;
        };
        /**
         * Diff two CBOM artifacts (URL form)
         * @description Same semantics as `POST /cbom/compare`, with the artifact ids in the URL so a diff can be shared as a deep link. Requires the tenant's `cbom_signing` entitlement.
         */
        get: operations["compareCBOMArtifactsByURL"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Scope: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            name: string;
            /** @description Optional; omitted when empty. */
            description?: string;
            predicate: components["schemas"]["Predicate"];
            version: number;
            is_default: boolean;
            /** @description System scopes are editable but not deletable (deleting one would orphan CBOM artifacts that reference it by id). */
            is_system: boolean;
            /**
             * Format: date-time
             * @description Soft-delete timestamp; omitted/null for live scopes.
             */
            deleted_at?: string | null;
            /** Format: uuid */
            created_by: string;
            /** Format: uuid */
            updated_by: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description Selection rule stored as JSONB. An empty predicate (no include and no exclude) matches every asset visible to the tenant under RLS. */
        Predicate: {
            include?: components["schemas"]["PredicateClause"];
            exclude?: components["schemas"]["PredicateClause"];
        };
        /** @description A set of asset-attribute filters joined OR-within-a-field and OR-across-fields. Used for both include and exclude clauses. */
        PredicateClause: {
            environment?: string[];
            asset_type?: string[];
            asset_ownership?: string[];
            asset_status?: string[];
            business_unit?: string[];
            location_region?: string[];
            risk_level?: string[];
            /** @description Case-insensitive match against the asset's tags JSONB. */
            tags_any_of?: string[];
        };
        /** @description CURRENT list envelope for GET /scopes. Pre-ADR-0002; a collection wrapped under the `scopes` key with no pagination. Hardening this to the ADR-0002 collection envelope (`{ data, pagination }`) is the documented go-forward change. */
        ScopeListResponse: {
            scopes: components["schemas"]["Scope"][];
        };
        CreateScopeRequest: {
            name: string;
            description?: string;
            predicate?: components["schemas"]["Predicate"];
        };
        UpdateScopeRequest: {
            name: string;
            description?: string;
            predicate?: components["schemas"]["Predicate"];
        };
        PreviewResult: {
            /** Format: uuid */
            scope_id: string;
            name: string;
            predicate: components["schemas"]["Predicate"];
            preview: {
                /** @enum {string} */
                status: "not_implemented" | "ok";
                matched_count: number | null;
                note: string;
            };
        };
        /** @description An immutable, dated, content-hashed snapshot of every cryptographic component matching a Scope at the moment of generation. Storage is dual-path: exactly one of `storage_key` (S3) or inline content (dev, gated by `has_inline_content`). */
        CBOMArtifact: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: uuid */
            scope_id: string;
            /** @description Version of the scope predicate that was in force. */
            scope_version: number;
            /** @description Scope name as of generation. Stored so renames don't rewrite history. */
            scope_name_snapshot: string;
            /** @description Optional human-meaningful name; omitted when empty. */
            name?: string;
            /** @description Object-storage key when the canonical bytes live in S3. Omitted when the artifact is stored inline. */
            storage_key?: string;
            /** @description True when the canonical bytes live in Postgres (dev / no-S3). */
            has_inline_content: boolean;
            /** @description Hex SHA-256 over the canonical CycloneDX bytes. */
            content_hash: string;
            size_bytes: number;
            component_count: number;
            /** @description The CycloneDX specification version the stored bytes declare. Artifacts generated from v0.2.0 onward say "1.7"; earlier ones say "1.6" and keep their bytes — artifacts are immutable evidence and are never re-rendered. */
            cyclonedx_spec_version: string;
            /** @description Generation-time only, echoed from POST /cbom/generate. Never returned by GET — it is not a stored column. */
            storage_degraded?: string;
            /** @description Generation-time only, echoed from POST /cbom/generate. Never returned by GET — it is not a stored column. */
            attestation_error?: string;
            /**
             * Format: date-time
             * @description How recent the inventory was when generation ran.
             */
            input_data_freshness_at: string;
            /** Format: date-time */
            generated_at: string;
            /** Format: uuid */
            generated_by: string;
            /** @description Phase 4. Hex HMAC-SHA256 over `content_hash`. Empty when unsigned. */
            signature_hmac?: string;
            /** @description Phase 4. Key id used to sign. Empty when unsigned. */
            signature_kid?: string;
            provenance: components["schemas"]["Provenance"];
            /** @description Optional attestation/annotation layers (e.g. compliance_attestation). Emitted as `null` when generation ran with `include_attestation: false`, when the attestation builder is unwired, or when the build produced no attestable findings — `Layers []Layer` in Go lacks `omitempty`, so a nil slice serializes as `null` rather than `[]`. Consumers must tolerate both. */
            layers: components["schemas"]["Layer"][] | null;
            /**
             * Format: date-time
             * @description Soft-delete timestamp; omitted/null for live artifacts.
             */
            deleted_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        /** @description Non-canonical context about how the artifact was generated. */
        Provenance: {
            generator_service?: string;
            generator_version?: string;
            request_id?: string;
        };
        /** @description Optional annotation attached to an artifact. Each layer carries its own type+version so the schema can evolve without breaking older artifacts. */
        Layer: {
            /** @description e.g. "compliance_attestation". */
            type: string;
            version?: string;
            /** @description Layer-specific payload; opaque to the generic schema. */
            data?: {
                [key: string]: unknown;
            };
        };
        /** @description CURRENT list envelope for GET /cbom/artifacts. Pre-ADR-0002 — a collection wrapped under the `artifacts` key with no pagination. Hardening this to the ADR-0002 collection envelope (`{ data, pagination }`) is the documented go-forward change. */
        CBOMArtifactListResponse: {
            artifacts: components["schemas"]["CBOMArtifact"][];
        };
        GenerateCBOMRequest: {
            /** Format: uuid */
            scope_id: string;
            /** @description Optional human-meaningful name. */
            name?: string;
            /** @description Phase 4. Attach a compliance_attestation layer summarizing open findings for the scope's asset set. Server defaults to true when omitted — audit-ready by default. */
            include_attestation?: boolean;
            /** @description Phase 4. HMAC-sign the artifact. Server defaults to true when omitted (requires INTERNAL_AUTH_SECRET on the server side). */
            sign?: boolean;
        };
        UnsupportedPredicateError: {
            error: string;
            /** @description The predicate field names that could not be evaluated. */
            unsupported_fields: string[];
        };
        GenerateCBOMResponse: {
            /** Format: uuid */
            artifact_id: string;
            /**
             * @description Phase 2 returns "ready" — generation is synchronous-but-quick, the row is already committed when this response is sent. The "queued" value is reserved for a future async path so the wire shape doesn't change when that lands.
             * @enum {string}
             */
            status: "ready" | "queued";
            /** @description Present when the artifact was produced but not stored the way the deployment is configured to store it — an object-store upload failed and the bytes went to the database instead. The artifact is complete and valid; regenerating once storage is healthy will place the object in the bucket. */
            storage_degraded?: string;
            /** @description Present when a compliance-attestation layer was requested and could not be built. Absent means either not requested or built successfully — the artifact's `layers` distinguishes the two. */
            attestation_error?: string;
        };
        VerifyResponse: {
            /** Format: uuid */
            artifact_id: string;
            /** @description True when the recomputed hash matched the stored hash. */
            hash_valid: boolean;
            /** @description Hex SHA-256 we just computed. Omitted when the bytes were not loadable; the UI can render "expected X, got Y" when both recomputed and stored are present. */
            hash_recomputed?: string;
            /** @description The content_hash recorded on the row. */
            hash_stored: string;
            /** @description True when the stored HMAC matched a recomputed HMAC against the platform's current signing key. Only meaningful when `signature_checked` is true. */
            signature_valid: boolean;
            /** @description False covers three cases: artifact unsigned, no verifier wired, or the hash check failed (in which case re-signing would be misleading). Treat false as "not asserted," not "asserted invalid." */
            signature_checked: boolean;
            /** @description Key id stored on the artifact; empty for unsigned. */
            signature_kid?: string;
        };
        CompareRequest: {
            /** Format: uuid */
            base_id: string;
            /** Format: uuid */
            head_id: string;
        };
        /** @enum {string} */
        ChangeKind: "added" | "removed" | "modified";
        /** @enum {string} */
        ChangeCategory: "improvement" | "regression" | "drift" | "neutral";
        DiffChange: {
            kind: components["schemas"]["ChangeKind"];
            category: components["schemas"]["ChangeCategory"];
            /** @description Stable identity used to align the two components. */
            match_key: string;
            /** @description e.g. algorithm / certificate / protocol / key / library. */
            component_type: string;
            name: string;
            /** @description Short human-readable phrase explaining the category. */
            reason: string;
            /** @description Original component object from the base artifact. nil/omitted for `added` changes (no base). Shape passed through verbatim from CycloneDX — kept open so the diff UI doesn't couple to the full component schema. */
            base?: {
                [key: string]: unknown;
            };
            /** @description Component object from the head artifact. nil/omitted for `removed` changes (no head). See `base` for shape note. */
            head?: {
                [key: string]: unknown;
            };
        };
        DiffResult: {
            /** Format: uuid */
            base_artifact_id: string;
            /** Format: uuid */
            head_artifact_id: string;
            /** @description Map keyed by category enum value to count. Keys are open because Go's `map[Category]int` marshals only categories with non-zero counts; absent keys mean zero. */
            count_by_category: {
                [key: string]: number;
            };
            /** @description Map keyed by kind enum value to count. See `count_by_category` for the absent-means-zero convention. */
            count_by_kind: {
                [key: string]: number;
            };
            /** @description The change list. Currently serializes as `null` when there are no changes (Go nil slice) instead of `[]` — a known quirk mirroring the scopes `null`-on-empty finding, to be addressed in the same hardening pass. */
            changes?: components["schemas"]["DiffChange"][] | null;
            /** @description One or two prose sentences summarizing the net change. */
            narrative: string;
        };
        /** @description CURRENT error shape returned by every cbom-service endpoint today: a single human-readable string under `error`. Unstructured — cannot be branched on safely. Superseded by the ADR-0002 `Error` envelope below as endpoints are hardened. */
        LegacyError: {
            error: string;
        };
        /** @description ADR-0002 error envelope. Clients branch on `error.code`, never on `message`. */
        Error: {
            error: {
                /** @description Stable, machine-readable enum (e.g. scope_not_found). */
                code: string;
                /** @description Human-readable, safe to surface in UI. */
                message: string;
                details?: components["schemas"]["ErrorDetail"][];
                /** @description For support correlation. */
                request_id?: string;
            };
        };
        ErrorDetail: {
            field: string;
            issue: string;
        };
        /** @description ADR-0002 pagination block for collection envelopes. */
        Pagination: {
            total: number;
            limit: number;
            offset: number;
            /** @description Offset of the next page, or null when there are no more. */
            next_offset?: number | null;
        };
    };
    responses: {
        /** @description Invalid request. */
        LegacyBadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["LegacyError"];
            };
        };
        /** @description Missing or invalid tenant/auth context. */
        LegacyUnauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["LegacyError"];
            };
        };
        /** @description Scope not found. */
        LegacyNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["LegacyError"];
            };
        };
        /** @description Operation not permitted (e.g. deleting a system scope). */
        LegacyConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["LegacyError"];
            };
        };
        /** @description Unexpected server error. */
        LegacyServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["LegacyError"];
            };
        };
    };
    parameters: {
        /** @description Scope UUID. */
        ScopeId: string;
        /** @description CBOM artifact UUID. */
        ArtifactId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listScopes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The tenant's scopes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScopeListResponse"];
                };
            };
            401: components["responses"]["LegacyUnauthorized"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    createScope: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateScopeRequest"];
            };
        };
        responses: {
            /** @description The created scope. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scope"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    getScope: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Scope UUID. */
                id: components["parameters"]["ScopeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The scope. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scope"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    updateScope: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Scope UUID. */
                id: components["parameters"]["ScopeId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateScopeRequest"];
            };
        };
        responses: {
            /** @description The updated scope. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scope"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    deleteScope: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Scope UUID. */
                id: components["parameters"]["ScopeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. No body. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
            404: components["responses"]["LegacyNotFound"];
            409: components["responses"]["LegacyConflict"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    previewScope: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Scope UUID. */
                id: components["parameters"]["ScopeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The preview result (Phase 1 stub). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewResult"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    generateCBOMArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateCBOMRequest"];
            };
        };
        responses: {
            /** @description Artifact generated. Body carries the new artifact's id. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateCBOMResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
            /** @description The request explicitly asked for CBOM signing or compliance attestation, but the tenant lacks `cbom_signing`. */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegacyError"];
                };
            };
            /** @description Scope not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegacyError"];
                };
            };
            /** @description The scope's predicate uses fields this deployment cannot evaluate. Generation is refused rather than producing an artifact whose contents are wider than the boundary it names. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnsupportedPredicateError"];
                };
            };
            500: components["responses"]["LegacyServerError"];
        };
    };
    listCBOMArtifacts: {
        parameters: {
            query?: {
                /** @description Filter to artifacts generated from this scope. */
                scope_id?: string;
                /** @description Maximum number of artifacts to return. Defaults to 50; values above 200 are clamped to 200. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The tenant's artifacts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CBOMArtifactListResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    getCBOMArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description CBOM artifact UUID. */
                id: components["parameters"]["ArtifactId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The artifact. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CBOMArtifact"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    softDeleteCBOMArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description CBOM artifact UUID. */
                id: components["parameters"]["ArtifactId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. No body. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    downloadCBOMArtifact: {
        parameters: {
            query?: {
                /** @description Wire format. Defaults to `cyclonedx`. */
                format?: "cyclonedx" | "spdx" | "pdf";
            };
            header?: never;
            path: {
                /** @description CBOM artifact UUID. */
                id: components["parameters"]["ArtifactId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The artifact bytes in the requested format. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.cyclonedx+json": string;
                    "application/spdx+json": string;
                    "application/pdf": string;
                };
            };
            /** @description Object-stored CycloneDX downloads return a presigned URL in `Location`. */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
            /** @description The requested format (`spdx` or `pdf`) requires an Enterprise renderer and the tenant's `cbom_signing` entitlement. */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegacyError"];
                };
            };
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    verifyCBOMArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description CBOM artifact UUID. */
                id: components["parameters"]["ArtifactId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verify result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    compareCBOMArtifacts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description The diff result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiffResult"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
            /** @description Artifact comparison requires the tenant's `cbom_signing` entitlement. */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegacyError"];
                };
            };
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    compareCBOMArtifactsByURL: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                base: string;
                head: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The diff result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiffResult"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
            /** @description Artifact comparison requires the tenant's `cbom_signing` entitlement. */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegacyError"];
                };
            };
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
}
