/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the tenant's cloud integrations
         * @description Includes shared (platform-wide) integrations. Optional `?provider=` filters by integration type.
         */
        get: operations["listIntegrations"];
        put?: never;
        /** Create a cloud integration */
        post: operations["createIntegration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Integration UUID. */
                id: components["parameters"]["IntegrationId"];
            };
            cookie?: never;
        };
        /** Get a cloud integration by id */
        get: operations["getIntegration"];
        /**
         * Update a cloud integration
         * @description Partial update; `config` is merged into the existing (decrypted) config, re-validated, and re-encrypted.
         */
        put: operations["updateIntegration"];
        post?: never;
        /** Delete a cloud integration (soft delete) */
        delete: operations["deleteIntegration"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Integration UUID. */
                id: components["parameters"]["IntegrationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test a cloud integration's connection
         * @description Decrypts the stored credentials and probes the provider; records last_tested_at + status. Always 200 with a success flag (auth failures are reported in the body, not the HTTP status).
         */
        post: operations["testIntegrationConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the tenant's interrogation schedules */
        get: operations["listSchedules"];
        put?: never;
        /** Create an interrogation schedule */
        post: operations["createSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Schedule UUID. */
                id: components["parameters"]["ScheduleId"];
            };
            cookie?: never;
        };
        /**
         * Get a schedule by id
         * @description Bare object. Tenant isolation — a schedule owned by another tenant returns 404.
         */
        get: operations["getSchedule"];
        /** Update a schedule */
        put: operations["updateSchedule"];
        post?: never;
        /** Delete a schedule */
        delete: operations["deleteSchedule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules/{id}/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Schedule UUID. */
                id: components["parameters"]["ScheduleId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger a schedule to run now */
        post: operations["triggerSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules/{id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Schedule UUID. */
                id: components["parameters"]["ScheduleId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enable a schedule */
        post: operations["enableSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules/{id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Schedule UUID. */
                id: components["parameters"]["ScheduleId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable a schedule */
        post: operations["disableSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Schedule UUID. */
                id: components["parameters"]["ScheduleId"];
            };
            cookie?: never;
        };
        /** Get a schedule's recent run history */
        get: operations["getScheduleHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the tenant's device interrogation agents
         * @description Read-only roster of the tenant's enrolled device interrogation agents
         *     (the downloadable device-agent binary), for the web-ui Discovery →
         *     Sensors & Agents fleet list. Tenant-scoped (DiscoveryRead) and
         *     RLS-isolated on `device_agents`. Enveloped under `agents` (nullable
         *     array on an empty result) plus a `count`. Each row exposes only
         *     device_agents telemetry; the secret `registration_key` is intentionally
         *     NOT included.
         */
        get: operations["listAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the tenant's interrogation devices */
        get: operations["listDevices"];
        put?: never;
        /** Register a device for interrogation */
        post: operations["createDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device UUID. */
                id: string;
            };
            cookie?: never;
        };
        /**
         * Get a device by id
         * @description Returns the device (bare object). Tenant isolation — a device owned by another tenant returns 404.
         */
        get: operations["getDevice"];
        /**
         * Update a device
         * @description Partial update. Tenant-isolated — a device owned by another tenant returns 404.
         */
        put: operations["updateDevice"];
        post?: never;
        /**
         * Delete a device
         * @description Tenant-isolated — a device owned by another tenant returns 404.
         */
        delete: operations["deleteDevice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{id}/interrogate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device UUID. */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Interrogate a device
         * @description Kicks off interrogation of the device. The success path performs live
         *     device I/O (HTTP to the target), so it is integration-tested; the contract
         *     test pins the request-validation paths (400 bad id / 404 device not found).
         */
        post: operations["interrogateDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{id}/test-connection": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device UUID. */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test connectivity to a device
         * @description Tests connectivity to the device. The success path performs live device
         *     I/O, so it is integration-tested; the contract test pins the
         *     request-validation paths (400 bad id / 404 device not found).
         */
        post: operations["testDeviceConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/bulk-interrogate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Interrogate multiple devices
         * @description Kicks off interrogation of multiple devices. Live device I/O on success
         *     (integration-tested); the contract test pins the bad-body 400.
         */
        post: operations["bulkInterrogateDevices"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/discover-and-create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Discover a device and create it
         * @description Probes the target (live device I/O), then creates the device record.
         *     Integration-tested on success; the contract test pins the bad-body 400.
         *     Returns the created Device on success.
         */
        post: operations["discoverAndCreateDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List interrogation jobs for the current tenant
         * @description Returns a paginated page of jobs. Filters (status[], job_type, device_id,
         *     integration_id) are accepted as query params; page / page_size paginate.
         */
        get: operations["listInterrogationJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregate interrogation-job statistics */
        get: operations["getInterrogationJobStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List currently active (pending / in-progress) jobs */
        get: operations["getActiveInterrogationJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job UUID. */
                id: string;
            };
            cookie?: never;
        };
        /** Get an interrogation job by id */
        get: operations["getInterrogationJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job UUID. */
                id: string;
            };
            cookie?: never;
        };
        /**
         * Get an interrogation job's results
         * @description Placeholder results shape today (assets/summary are stubbed); the job_id + status are real.
         */
        get: operations["getInterrogationJobResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job UUID. */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry a failed or cancelled job
         * @description Resets the job to pending. Only failed/cancelled jobs may be retried (else 400).
         */
        post: operations["retryInterrogationJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job UUID. */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a pending or in-progress job
         * @description Only pending / assigned / in-progress jobs may be cancelled (else 400).
         */
        post: operations["cancelInterrogationJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cloud/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start an ad-hoc cloud discovery job
         * @description Triggers an immediate cloud discovery run for one integration. The job is
         *     created and started asynchronously; the response returns the job_id so the
         *     caller can poll /jobs/{id} for status. Requires discovery.manage permission.
         */
        post: operations["discoverCloudResources"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Platform-wide device/integration/job health summary
         * @description Aggregate health metrics across ALL tenants for the admin-ui platform
         *     oversight dashboard. Platform-admin only (`RequirePlatformAdmin()` — a
         *     tenant JWT is rejected with 401/403). Returns the bare
         *     `PlatformHealthSummary` object (NOT enveloped under a key).
         *
         *     Shape note: the admin-ui's `getMetrics()` (`platform-devices-api.ts`)
         *     expects a different, nested `PlatformMetrics` shape
         *     (`{ devices, jobs, tenants, recent_errors }`). The Go handler actually
         *     returns this FLAT `PlatformHealthSummary`. The client try/catches and
         *     falls back to zeros, masking the mismatch. This spec documents the
         *     real Go response.
         */
        get: operations["getAdminMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Platform-wide interrogation-agent roster (Fleet view)
         * @description Read-only roll-up of every device interrogation agent across ALL
         *     tenants, for the VISTA Operations "Fleet" view in admin-ui.
         *     Platform-admin only (`RequirePlatformAdmin()` — a tenant JWT is
         *     rejected with 403). Unlike the tenant-scoped `GET /agents` this
         *     deliberately omits the tenant_id filter and joins `tenants` so each row
         *     carries tenant identity (`tenant_id` + `tenant_name` + `tenant_slug`).
         *
         *     An optional `tenant_id` narrows the roll-up to a single tenant
         *     server-side (the operator "scope" selector) so the client is never
         *     shipped other tenants' rows; omit it for the full cross-tenant view.
         *
         *     Returned enveloped under `agents` (always a non-nil array) plus a
         *     `count`. Each row exposes only telemetry that exists on the
         *     `device_agents` table; the secret `registration_key` is intentionally
         *     NOT included.
         */
        get: operations["listAdminAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Platform-wide interrogation jobs (Jobs & Queues view)
         * @description Read-only roll-up of interrogation jobs across ALL tenants, for the VISTA
         *     Operations "Jobs & Queues" view in admin-ui. Platform-admin only
         *     (`RequirePlatformAdmin()` — a tenant JWT is rejected with 403). Unlike the
         *     tenant-scoped `GET /jobs` this deliberately omits the tenant_id filter and
         *     joins `tenants` so each row carries tenant identity (`tenant_id` +
         *     `tenant_name` + `tenant_slug`), plus the assigned `worker` (the executing
         *     agent id, from `device_jobs.agent_id`).
         *
         *     Same optional filters (status[], job_type, device_id, integration_id) and
         *     page / page_size pagination as `GET /jobs`. An optional `tenant_id` narrows
         *     the roll-up to a single tenant server-side (the operator "scope" selector) so
         *     the client is never shipped other tenants' rows; omit it for the full
         *     cross-tenant view. The Support cockpit's Job Repair action adds cross-tenant
         *     `POST /admin/jobs/{id}/retry` and `/cancel` (both platform-admin gated) so
         *     operators can recover a stuck customer job directly.
         */
        get: operations["listAdminJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/jobs/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job UUID. */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry a failed or cancelled job across any tenant (platform-admin)
         * @description Cross-tenant retry for the Support cockpit's Job Repair action. Looks the
         *     job up by id alone (no tenant scope) and resets it to pending. Only
         *     failed/cancelled jobs may be retried (else 400). Platform-admin only
         *     (`RequirePlatformAdmin()` — a tenant JWT is rejected with 403).
         */
        post: operations["retryAdminInterrogationJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/jobs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job UUID. */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a pending or in-progress job across any tenant (platform-admin)
         * @description Cross-tenant cancel for the Support cockpit's Job Repair action. Looks the
         *     job up by id alone (no tenant scope). Only pending / assigned / in-progress
         *     jobs may be cancelled (else 400). Platform-admin only
         *     (`RequirePlatformAdmin()` — a tenant JWT is rejected with 403).
         */
        post: operations["cancelAdminInterrogationJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/queues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Platform-wide JetStream queue (stream/consumer) telemetry
         * @description Read-only per-queue backlog telemetry for the VISTA Operations "Queues"
         *     panel, sourced live from NATS JetStream stream + durable-consumer info.
         *     Platform-admin only (`RequirePlatformAdmin()` — a tenant JWT is rejected
         *     with 403).
         *
         *     Each queue is one JetStream stream (the platform's DefaultStreams). The
         *     meaningful per-queue depth is each consumer's `depth` (JetStream
         *     `num_pending` — undelivered backlog); `in_flight` is delivered-but-unacked
         *     (`num_ack_pending`); `num_waiting` is parked pull requests (idle workers).
         *     Stream-level `messages`/`bytes` are total retained (subject to MaxAge),
         *     not a live depth.
         *
         *     Metrics honesty: JetStream does NOT expose per-queue throughput rate or
         *     p95 latency, so those are intentionally absent — they are not fabricated.
         *     Streams that do not yet exist (no producer has run) are skipped.
         *
         *     Returns 503 when NATS/JetStream is unavailable (e.g. dev compose without
         *     NATS) rather than inventing metrics.
         */
        get: operations["listAdminQueues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Request body for POST /cloud/discover — triggers an ad-hoc cloud discovery run. */
        CloudDiscoverRequest: {
            /**
             * Format: uuid
             * @description The cloud integration to run discovery against.
             */
            integration_id: string;
            /**
             * @description Provider hint (aws / azure / gcp). Auto-detected from the integration when omitted.
             * @enum {string}
             */
            cloud_provider?: "aws" | "azure" | "gcp";
            /** @description Provider-specific resource types to discover (e.g. alb, api_gateway, cloudfront for AWS). */
            resource_types: string[];
            /** @description AWS regions to scan (e.g. us-east-1). Ignored for GCP. */
            regions?: string[];
            /** @description Azure resource groups to filter by. Ignored for AWS and GCP. */
            resource_groups?: string[];
        };
        /** @description Response for POST /cloud/discover. */
        CloudDiscoverResponse: {
            message?: string;
            /** Format: uuid */
            job_id?: string;
        };
        /** @description Request body for POST /devices. `password` is encrypted at rest. */
        CreateDeviceRequest: {
            device_type: string;
            vendor?: string;
            model?: string;
            hostname?: string;
            ip_address?: string;
            management_url?: string;
            serial_number?: string;
            firmware_version?: string;
            discovery_method?: string;
            /** Format: uuid */
            credential_id?: string;
            username?: string;
            password?: string;
            tls_insecure_skip_verify?: boolean;
            metadata?: {
                [key: string]: unknown;
            };
            tags?: {
                [key: string]: unknown;
            };
        };
        /** @description Request body for PUT /devices/{id}. All fields optional. */
        UpdateDeviceRequest: {
            vendor?: string;
            model?: string;
            hostname?: string;
            ip_address?: string;
            management_url?: string;
            serial_number?: string;
            firmware_version?: string;
            /** Format: uuid */
            credential_id?: string;
            username?: string;
            password?: string;
            tls_insecure_skip_verify?: boolean;
            connection_status?: string;
            metadata?: {
                [key: string]: unknown;
            };
            tags?: {
                [key: string]: unknown;
            };
        };
        /** @description CURRENT envelope for POST /jobs/{id}/retry — `{ "message": "...", "job": { "id": ..., "status": "pending" } }`. */
        RetryJobResponse: {
            message: string;
            job: {
                /** Format: uuid */
                id: string;
                status: string;
            };
        };
        /**
         * @description A cloud integration (handlers.CloudIntegration — the API response shape).
         *     `config` is the credential map with sensitive fields MASKED (never the
         *     plaintext or ciphertext). The listed required fields are always present;
         *     the rest are `omitempty`.
         */
        CloudIntegration: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /** @description aws / azure / gcp / ... */
            integration_type: string;
            integration_name: string;
            provider: string;
            /** @description Credential map with sensitive values masked. */
            config: {
                [key: string]: unknown;
            } | null;
            account_id?: string;
            region?: string;
            environment?: string;
            description?: string;
            tags?: string[];
            is_enabled: boolean;
            is_shared?: boolean;
            /** @description pending / configured / connected / error. */
            status: string;
            status_message?: string;
            /** Format: date-time */
            last_tested_at?: string;
            last_test_error?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description Request body for POST /integrations. */
        CreateIntegrationRequest: {
            integration_type: string;
            integration_name: string;
            provider: string;
            config: {
                [key: string]: unknown;
            };
            account_id?: string;
            region?: string;
            environment?: string;
            description?: string;
            tags?: string[];
            is_enabled?: boolean;
        };
        /** @description Request body for PUT /integrations/{id}. All fields optional. */
        UpdateIntegrationRequest: {
            integration_name?: string;
            config?: {
                [key: string]: unknown;
            };
            account_id?: string;
            region?: string;
            environment?: string;
            description?: string;
            tags?: string[];
            is_enabled?: boolean;
        };
        /** @description CURRENT envelope for GET /integrations — `{ "integrations": [...], "count": N }`. `integrations` is always a non-nil array. */
        IntegrationListResponse: {
            integrations: components["schemas"]["CloudIntegration"][];
            count: number;
        };
        /** @description CURRENT envelope for GET /integrations/{id} and POST /integrations — `{ "integration": {...} }`. */
        IntegrationResponse: {
            integration: components["schemas"]["CloudIntegration"];
        };
        /** @description CURRENT shape for POST /integrations/{id}/test — `{ "success": bool, "message": "...", "details"?: {...} }`. */
        TestConnectionResult: {
            success: boolean;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        /**
         * @description A recurring interrogation schedule (services.InterrogationSchedule). The
         *     listed required fields are always present; the rest are `omitempty` and
         *     appear only when set.
         */
        InterrogationSchedule: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            name: string;
            description?: string;
            cron_expression: string;
            /** @description "device" or "cloud_integration". */
            target_type: string;
            /** Format: uuid */
            target_id: string;
            is_enabled: boolean;
            /** Format: date-time */
            last_run_at?: string;
            last_run_status?: string;
            /** Format: uuid */
            last_run_job_id?: string;
            /** Format: date-time */
            next_run_at?: string;
            success_count: number;
            failure_count: number;
            parameters?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            deleted_at?: string;
        };
        /** @description A single schedule run record (services.ScheduleHistory). */
        ScheduleHistory: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            schedule_id: string;
            /** Format: uuid */
            job_id: string;
            status: string;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            completed_at?: string;
            error_message?: string;
            assets_found: number;
        };
        /** @description Request body for POST /schedules. */
        CreateScheduleRequest: {
            name: string;
            description?: string;
            cron_expression: string;
            target_type: string;
            /** Format: uuid */
            target_id: string;
            is_enabled?: boolean;
            parameters?: {
                [key: string]: unknown;
            };
        };
        /** @description Request body for PUT /schedules/{id}. All fields optional. */
        UpdateScheduleRequest: {
            name?: string;
            description?: string;
            cron_expression?: string;
            is_enabled?: boolean;
            parameters?: {
                [key: string]: unknown;
            };
        };
        /** @description CURRENT envelope for GET /schedules — `{ "schedules": [...] }`. Nullable array when empty. */
        ScheduleListResponse: {
            schedules: components["schemas"]["InterrogationSchedule"][] | null;
        };
        /** @description CURRENT envelope for GET /schedules/{id}/history — `{ "history": [...] }`. Nullable array when empty. */
        ScheduleHistoryResponse: {
            history: components["schemas"]["ScheduleHistory"][] | null;
        };
        /** @description CURRENT envelope for POST /schedules/{id}/trigger — `{ "message": "...", "job_id": "..." }`. */
        TriggerScheduleResponse: {
            message: string;
            job_id: string;
        };
        /** @description Open envelope for the device action endpoints (interrogate / test-connection / bulk-interrogate). The concrete shape (queued-job id or live connectivity result) depends on live device I/O and is integration- tested, not contract-pinned — hence additionalProperties:true with no required fields. */
        DeviceActionAccepted: {
            [key: string]: unknown;
        };
        /** @description Bare acknowledgement envelope (e.g. delete). */
        MessageResponse: {
            message: string;
        };
        /**
         * @description A network device registered for interrogation (models.Device). Field
         *     presence follows the json tags: the nullable pointer / JSONB fields are
         *     required-but-nullable (serialize as null when unset); credential_id /
         *     username / password are `omitempty` and appear only when set. password is
         *     masked/encrypted server-side.
         */
        Device: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /** @description unifi / cisco / fortinet / palo_alto / f5. */
            device_type: string;
            vendor: string | null;
            model: string | null;
            hostname: string | null;
            ip_address: string | null;
            management_url: string | null;
            serial_number: string | null;
            firmware_version: string | null;
            discovery_method: string;
            /** Format: uuid */
            credential_id?: string;
            username?: string;
            password?: string;
            tls_insecure_skip_verify: boolean;
            /** @description connected / disconnected / error / unknown / testing. */
            connection_status: string;
            /** Format: date-time */
            last_interrogated_at: string | null;
            interrogation_error: string | null;
            metadata: {
                [key: string]: unknown;
            } | null;
            tags: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            deleted_at: string | null;
        };
        /**
         * @description A tenant's enrolled device interrogation agent (models.Agent). Telemetry
         *     mirrors the device_agents columns; the secret registration_key is omitted.
         *     `name` and `profile` are nullable (DB NULLs surface as JSON null) — they
         *     are carried from the pending registration at bootstrap time.
         */
        Agent: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /** @description Operator-assigned agent name (carried from the pending registration); null when unset. */
            name: string | null;
            /** @description Agent host platform (e.g. linux/amd64). */
            platform: string;
            /** @description Registration profile (device_interrogation); null when unset. */
            profile: string | null;
            /** @description Agent binary version. */
            version: string;
            /** @description Agent status: active, inactive, or error. */
            status: string;
            /**
             * @description The agent host's primary address, self-reported on each heartbeat —
             *     the source address its kernel uses to reach the platform. Null until
             *     an agent new enough to report one checks in. The platform cannot
             *     derive this: NAT and ingress rewrite the connection source.
             */
            ip_address: string | null;
            /**
             * Format: date-time
             * @description Last heartbeat timestamp; null if the agent has never checked in.
             */
            last_heartbeat: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description Envelope for GET /agents — `{ "agents": [...], "count": N }`. On an empty/nil result `agents` can serialize as JSON null, so it is typed as a nullable array. */
        AgentListResponse: {
            agents: components["schemas"]["Agent"][] | null;
            count: number;
        };
        /** @description CURRENT envelope for GET /devices — `{ "devices": [...] }`. On an empty/nil result `devices` can serialize as JSON null, so it is typed as a nullable array. */
        DeviceListResponse: {
            devices: components["schemas"]["Device"][] | null;
        };
        /**
         * @description An interrogation job (handlers.InterrogationJob — the API response shape).
         *     The listed required fields are always present; every other field is
         *     `omitempty` and appears only when set.
         */
        InterrogationJob: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            job_type: string;
            status: string;
            /** Format: uuid */
            device_id?: string;
            device_name?: string;
            device_type?: string;
            /** Format: uuid */
            integration_id?: string;
            integration_name?: string;
            cloud_provider?: string;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            completed_at?: string;
            error_message?: string;
            progress?: number;
            assets_discovered?: number;
            duration_seconds?: number;
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Last24hStats: {
            completed: number;
            failed: number;
        };
        /** @description Aggregate interrogation-job statistics (handlers.JobStats). */
        JobStats: {
            total: number;
            pending: number;
            in_progress: number;
            completed: number;
            failed: number;
            last_24h: components["schemas"]["Last24hStats"];
            average_duration_seconds?: number;
        };
        /**
         * @description Aggregate health metrics across all tenants
         *     (services.PlatformHealthSummary), returned bare by GET /admin/metrics.
         *     Every field has a non-omitempty json tag, so all are always present;
         *     the two maps are constructed non-nil server-side (never JSON null).
         */
        PlatformHealthSummary: {
            total_devices: number;
            connected_devices: number;
            disconnected_devices: number;
            total_integrations: number;
            active_integrations: number;
            error_integrations: number;
            jobs_last_24h: number;
            successful_jobs_last_24h: number;
            failed_jobs_last_24h: number;
            success_rate: number;
            average_job_duration_ms: number;
            /** @description Map of device_type → count (non-nil; empty object when no devices). */
            devices_by_type: {
                [key: string]: number;
            };
            /** @description Map of provider → count (non-nil; empty object when no integrations). */
            integrations_by_provider: {
                [key: string]: number;
            };
        };
        /**
         * @description A device interrogation agent enriched with tenant identity, for the
         *     platform-admin Fleet view (models.AdminAgent). Telemetry fields mirror
         *     the device_agents columns; the secret registration_key is omitted.
         *     `name`, `profile`, and `last_heartbeat` are nullable (DB NULLs surface
         *     as JSON null).
         */
        AdminAgent: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /** @description Tenant display name (from the tenants join; empty string if the tenant row is missing). */
            tenant_name: string;
            /** @description Tenant slug (from the tenants join; empty string if the tenant row is missing). */
            tenant_slug: string;
            /** @description Operator-assigned agent name; null when unset. */
            name: string | null;
            /** @description Agent host platform (e.g. linux/amd64). */
            platform: string;
            /** @description Registration profile (e.g. device_interrogation); null when unset. */
            profile: string | null;
            /** @description Agent binary version. */
            version: string;
            /** @description Agent status: active, inactive, or error. */
            status: string;
            /**
             * @description The agent host's primary address, self-reported on each heartbeat —
             *     the source address its kernel uses to reach the platform. Null until
             *     an agent new enough to report one checks in. The platform cannot
             *     derive this: NAT and ingress rewrite the connection source.
             */
            ip_address: string | null;
            /**
             * Format: date-time
             * @description Last heartbeat timestamp; null if the agent has never checked in.
             */
            last_heartbeat: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description Envelope for GET /admin/agents — `{ "agents": [...], "count": N }`. `agents` is a non-nil array. */
        AdminAgentListResponse: {
            agents: components["schemas"]["AdminAgent"][];
            count: number;
        };
        /** @description CURRENT envelope for GET /jobs — `{ "jobs": [...], "total": N, "page": P, "page_size": S }`. `jobs` is always a non-nil array. */
        JobListResponse: {
            jobs: components["schemas"]["InterrogationJob"][];
            total: number;
            page: number;
            page_size: number;
        };
        /**
         * @description Cross-tenant interrogation job for the platform-admin Jobs & Queues view
         *     (handlers.AdminInterrogationJob). Same telemetry as InterrogationJob plus
         *     per-row tenant identity (tenant_name/tenant_slug) and the assigned
         *     `worker` (device_jobs.agent_id). The listed required fields are always
         *     present; every other field is omitempty and appears only when set. Note
         *     there is no `progress`/`metadata` field here — device_jobs has no progress
         *     column and admin rows do not project metadata.
         */
        AdminInterrogationJob: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            tenant_name: string;
            tenant_slug: string;
            job_type: string;
            status: string;
            /** Format: uuid */
            device_id?: string;
            device_name?: string;
            device_type?: string;
            /** Format: uuid */
            integration_id?: string;
            integration_name?: string;
            cloud_provider?: string;
            /**
             * Format: uuid
             * @description device_jobs.agent_id — the agent executing the job (null for unassigned/cloud jobs).
             */
            worker?: string;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            completed_at?: string;
            error_message?: string;
            assets_discovered?: number;
            duration_seconds?: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description Envelope for GET /admin/jobs — `{ "jobs": [...], "total": N, "page": P, "page_size": S }`. `jobs` is always a non-nil array. */
        AdminJobListResponse: {
            jobs: components["schemas"]["AdminInterrogationJob"][];
            total: number;
            page: number;
            page_size: number;
        };
        /**
         * @description Per-consumer backlog telemetry from JetStream ConsumerInfo
         *     (handlers.QueueConsumer). `depth` is num_pending (undelivered backlog),
         *     `in_flight` is num_ack_pending (delivered, awaiting ack), `num_waiting` is
         *     parked pull requests (idle workers). No rate/p95 — JetStream does not
         *     expose them.
         */
        QueueConsumer: {
            name: string;
            /** @description JetStream num_pending — undelivered backlog for this consumer. */
            depth: number;
            /** @description JetStream num_ack_pending — delivered but not yet acked. */
            in_flight: number;
            /** @description Outstanding pull requests parked by idle workers. */
            num_waiting: number;
            num_redelivered: number;
            /** Format: date-time */
            last_delivered?: string;
        };
        /**
         * @description One JetStream stream and its per-consumer backlog breakdown
         *     (handlers.AdminQueue). Stream-level `messages`/`bytes` are total retained
         *     (subject to MaxAge), not a live depth — the meaningful depth is each
         *     consumer's `depth`.
         */
        AdminQueue: {
            name: string;
            subjects: string[];
            /** @description Stream State.Msgs — total messages retained in the stream. */
            messages: number;
            /** @description Stream State.Bytes. */
            bytes: number;
            consumer_count: number;
            /** Format: date-time */
            last_message_at?: string;
            consumers: components["schemas"]["QueueConsumer"][];
        };
        /**
         * @description Envelope for GET /admin/queues — `{ "queues": [...], "count": N,
         *     "metrics_note": "..." }`. `queues` is a non-nil array. `metrics_note`
         *     documents that per-queue rate/p95 are intentionally absent (JetStream
         *     does not expose them).
         */
        AdminQueueListResponse: {
            queues: components["schemas"]["AdminQueue"][];
            count: number;
            metrics_note: string;
        };
        /** @description CURRENT envelope for GET /jobs/{id} — `{ "job": {...} }`. */
        JobResponse: {
            job: components["schemas"]["InterrogationJob"];
        };
        /** @description CURRENT envelope for GET /jobs/stats — `{ "stats": {...} }`. */
        JobStatsResponse: {
            stats: components["schemas"]["JobStats"];
        };
        /** @description CURRENT envelope for GET /jobs/active — `{ "jobs": [...] }` (non-nil array). */
        ActiveJobsResponse: {
            jobs: components["schemas"]["InterrogationJob"][];
        };
        /**
         * @description CURRENT shape for GET /jobs/{id}/results. assets / summary are stubbed
         *     placeholders today (empty array, zeroed summary); job_id + status are real.
         */
        JobResultsResponse: {
            job_id: string;
            status: string;
            assets: {
                [key: string]: unknown;
            }[];
            summary: {
                total_assets: number;
                new_assets: number;
                updated_assets: number;
            };
        };
        /** @description CURRENT error shape — a single human-readable string under `error`. Superseded by the ADR-0002 Error envelope as endpoints are hardened. */
        LegacyError: {
            error: string;
        } & {
            [key: string]: unknown;
        };
        /** @description ADR-0002 error envelope. Clients branch on `error.code`, never on `message`. */
        Error: {
            error: {
                code: string;
                message: string;
                details?: components["schemas"]["ErrorDetail"][];
                request_id?: string;
            };
        };
        ErrorDetail: {
            field: string;
            issue: string;
        };
        /** @description ADR-0002 pagination block for collection envelopes. */
        Pagination: {
            total: number;
            limit: number;
            offset: number;
            next_offset?: number | null;
        };
    };
    responses: {
        /** @description Invalid request. */
        LegacyBadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["LegacyError"];
            };
        };
        /** @description Resource not found. */
        LegacyNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["LegacyError"];
            };
        };
        /** @description Unexpected server error. */
        LegacyServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["LegacyError"];
            };
        };
        /** @description Caller is not a platform admin. */
        LegacyForbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["LegacyError"];
            };
        };
    };
    parameters: {
        /** @description Schedule UUID. */
        ScheduleId: string;
        /** @description Integration UUID. */
        IntegrationId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listIntegrations: {
        parameters: {
            query?: {
                /** @description Filter by integration_type (e.g. aws). */
                provider?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The tenant's integrations (credentials masked). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationListResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    createIntegration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIntegrationRequest"];
            };
        };
        responses: {
            /** @description The created integration (credentials masked). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    getIntegration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Integration UUID. */
                id: components["parameters"]["IntegrationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The integration (credentials masked). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    updateIntegration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Integration UUID. */
                id: components["parameters"]["IntegrationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateIntegrationRequest"];
            };
        };
        responses: {
            /** @description Update acknowledged. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    deleteIntegration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Integration UUID. */
                id: components["parameters"]["IntegrationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deletion acknowledged. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    testIntegrationConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Integration UUID. */
                id: components["parameters"]["IntegrationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The connection test result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestConnectionResult"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    listSchedules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The tenant's schedules. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleListResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    createSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateScheduleRequest"];
            };
        };
        responses: {
            /** @description The created schedule (bare object). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterrogationSchedule"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    getSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Schedule UUID. */
                id: components["parameters"]["ScheduleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The schedule. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterrogationSchedule"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            404: components["responses"]["LegacyNotFound"];
        };
    };
    updateSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Schedule UUID. */
                id: components["parameters"]["ScheduleId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateScheduleRequest"];
            };
        };
        responses: {
            /** @description The updated schedule (bare object). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterrogationSchedule"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    deleteSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Schedule UUID. */
                id: components["parameters"]["ScheduleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deletion acknowledged. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    triggerSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Schedule UUID. */
                id: components["parameters"]["ScheduleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The schedule run was queued; returns the created job id. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerScheduleResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    enableSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Schedule UUID. */
                id: components["parameters"]["ScheduleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The updated schedule (is_enabled=true). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterrogationSchedule"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    disableSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Schedule UUID. */
                id: components["parameters"]["ScheduleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The updated schedule (is_enabled=false). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterrogationSchedule"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    getScheduleHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Schedule UUID. */
                id: components["parameters"]["ScheduleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The schedule's run history (up to 50 most recent). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleHistoryResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    listAgents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The tenant's device interrogation agents. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentListResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    listDevices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The tenant's devices. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceListResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    createDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDeviceRequest"];
            };
        };
        responses: {
            /** @description The created device (bare object). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    getDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device UUID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The device (bare object). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            404: components["responses"]["LegacyNotFound"];
        };
    };
    updateDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device UUID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDeviceRequest"];
            };
        };
        responses: {
            /** @description The updated device (bare object). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    deleteDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device UUID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deletion acknowledged. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    interrogateDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device UUID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Interrogation accepted (async). Body is the queued-job info (not contract-pinned). */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceActionAccepted"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    testDeviceConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Device UUID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connectivity result (live; not contract-pinned). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceActionAccepted"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    bulkInterrogateDevices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Bulk interrogation accepted (async; not contract-pinned). */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceActionAccepted"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    discoverAndCreateDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description The created device. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    listInterrogationJobs: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of interrogation jobs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    getInterrogationJobStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job statistics. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatsResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
        };
    };
    getActiveInterrogationJobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The active jobs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveJobsResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
        };
    };
    getInterrogationJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job UUID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The job. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    getInterrogationJobResults: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job UUID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The job results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResultsResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    retryInterrogationJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job UUID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The job was queued for retry. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetryJobResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    cancelInterrogationJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job UUID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The job was cancelled. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    discoverCloudResources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloudDiscoverRequest"];
            };
        };
        responses: {
            /** @description Discovery job accepted and started. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudDiscoverResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    getAdminMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The platform-wide health summary (bare object). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformHealthSummary"];
                };
            };
            500: components["responses"]["LegacyServerError"];
        };
    };
    listAdminAgents: {
        parameters: {
            query?: {
                /** @description Narrow the cross-tenant roll-up to a single tenant (operator scope). */
                tenant_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The platform-wide agent roster. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAgentListResponse"];
                };
            };
            403: components["responses"]["LegacyForbidden"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    listAdminJobs: {
        parameters: {
            query?: {
                page?: number;
                /** @description Narrow the cross-tenant roll-up to a single tenant (operator scope). */
                tenant_id?: string;
                page_size?: number;
                /** @description Repeatable; filters by job status (status=pending&status=failed). */
                status?: string[];
                job_type?: string;
                device_id?: string;
                integration_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of platform-wide interrogation jobs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminJobListResponse"];
                };
            };
            403: components["responses"]["LegacyForbidden"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    retryAdminInterrogationJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job UUID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The job was queued for retry. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetryJobResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            403: components["responses"]["LegacyForbidden"];
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    cancelAdminInterrogationJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job UUID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The job was cancelled. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            403: components["responses"]["LegacyForbidden"];
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    listAdminQueues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-queue live JetStream telemetry. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminQueueListResponse"];
                };
            };
            403: components["responses"]["LegacyForbidden"];
            500: components["responses"]["LegacyServerError"];
            /** @description NATS/JetStream unavailable; queue metrics cannot be read. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegacyError"];
                };
            };
        };
    };
}
