/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/sensors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List sensors for the current tenant
         * @description Returns the tenant's sensors. On any service error the handler logs and
         *     returns 200 with an empty list rather than 500, so the Operations page
         *     always renders.
         */
        get: operations["listSensors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sensors/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sensor count breakdown for the current tenant
         * @description Aggregate counts used by the Operations dashboard tiles. Computed from
         *     the tenant's sensors by status. Discovery/packet/error totals are
         *     currently always zero (not yet wired) and `last_updated` is the server
         *     time of the call.
         */
        get: operations["getSensorStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sensors/discovery-counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Per-sensor discovery counts for the current tenant
         * @description Maps each of the tenant's sensor ids to its discovery count. Returns an
         *     empty map when the underlying DB is unavailable.
         */
        get: operations["getSensorDiscoveryCounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sensors/{sensor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sensor UUID. */
                sensor_id: components["parameters"]["SensorId"];
            };
            cookie?: never;
        };
        /**
         * Get a sensor by id
         * @description Returns a single sensor. The body is the sensor object **directly** (not
         *     wrapped under a `sensor` key). Any retrieval failure maps to 404.
         */
        get: operations["getSensor"];
        put?: never;
        post?: never;
        /**
         * Soft-delete a sensor
         * @description Soft-deletes the sensor. Gated by the `sensors.delete` permission.
         *
         *     Platform-managed sensors are refused with 403: those rows are the
         *     tenant's handle to the in-cluster services shared by all tenants, and
         *     removing one silently stops discovery results reaching that tenant's
         *     inventory.
         */
        delete: operations["deleteSensor"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sensors/{sensor_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sensor UUID. */
                sensor_id: components["parameters"]["SensorId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Update a sensor's status
         * @description Sets the sensor's status. `status` is required in the body. Gated by the
         *     `sensors.update` permission.
         */
        put: operations["updateSensorStatus"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sensors/{sensor_id}/interfaces": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sensor UUID. */
                sensor_id: components["parameters"]["SensorId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Add/remove a sensor's capture network interfaces
         * @description Adds and/or removes interfaces on the sensor's capture set. The body
         *     carries optional `add` / `remove` string arrays (entries already present
         *     are not duplicated; entries in `remove` are dropped). Gated by the
         *     `sensors.update` permission. Returns the resulting interface list.
         */
        put: operations["updateSensorInterfaces"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sensors/{sensor_id}/config": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sensor UUID. */
                sensor_id: components["parameters"]["SensorId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Update a sensor's configuration
         * @description Updates a sensor's profile / description / tags and capture options; all
         *     body fields are optional. When capture options (`active_probing`,
         *     `network_discovery`, `dedup_ttl_minutes`) change, an `update_config`
         *     command is queued for the sensor to apply on next checkin. Gated by the
         *     `sensors.update` permission. Returns the updated config subset.
         */
        put: operations["updateSensorConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sensors/config/defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The tenant's fleet-wide default settings for sensors
         * @description Every settable sensor setting with the value that applies fleet-wide,
         *     and an `origin` saying whether the tenant set it (`fleet`) or is
         *     inheriting the sensor binary's own default (`built_in`). Gated at
         *     SensorsRead.
         */
        get: operations["getSensorFleetDefaults"];
        /**
         * Replace the tenant's fleet-wide default settings for sensors
         * @description Replaces the whole set: a key left out is cleared, because a partial
         *     write cannot express "remove this one". Every sensor without its own
         *     override converges on the new values at its next heartbeat, with nothing
         *     to push — the desired revision is a content hash, so a changed default
         *     makes every inheriting sensor disagree.
         *
         *     Gated at SensorsManage. A value below a setting's floor is RAISED rather
         *     than rejected, and the response says so in `adjusted`. Turning on a
         *     setting that starts a new kind of collection — `host_observation_dns` —
         *     answers 409 until the request carries `confirmed: true`, and the change
         *     is recorded with the acting user.
         */
        put: operations["putSensorFleetDefaults"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sensors/{sensor_id}/desired-config/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Who changed this sensor's configuration, when, and what moved
         * @description The recorded change history, newest first, covering this sensor's own
         *     overrides AND the tenant's fleet defaults for its runtime — an operator
         *     asking "why is this on" is not served by a history that can only answer
         *     half the time.
         *
         *     Gated at SensorsRead rather than behind update or manage: reading who
         *     changed something is a read, and the person most likely to ask is the
         *     one who cannot change it.
         */
        get: operations["getSensorConfigHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sensors/{sensor_id}/desired-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One sensor's effective settings and how far it has converged
         * @description The effective value of every sensor setting with the `origin` it came
         *     from (`built_in`, `fleet` or `device`), plus a `status` block reconciling
         *     what the platform wants against what the sensor last reported.
         *
         *     Distinct from `/sensors/{sensor_id}/config`, which queues a one-shot
         *     `update_config` command and persists nothing — so the platform cannot
         *     say what it asked for, a missed command is never re-sent, and the
         *     console can show a value that never took effect.
         *
         *     Gated at SensorsRead. Another tenant's sensor id is answered 404,
         *     identically to an unknown id.
         */
        get: operations["getSensorDesiredConfig"];
        /**
         * Replace one sensor's settings override
         * @description Sets what THIS sensor should be, over and above the fleet defaults. An
         *     explicit `false` is an override and beats a fleet default of `true`; an
         *     omitted key inherits. Send `{"values": {}}` to clear the override
         *     entirely.
         *
         *     Gated at SensorsManage. The sensor adopts the change at its next
         *     heartbeat; settings marked `apply: restart` — host observation and DNS
         *     decoding, whose BPF filter is fixed when the capture handle opens — are
         *     listed in `needs_restart` and adopted when the sensor restarts.
         */
        put: operations["putSensorDesiredConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sensors/{sensor_id}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sensor UUID. */
                sensor_id: components["parameters"]["SensorId"];
            };
            cookie?: never;
        };
        /** List a sensor's pending commands */
        get: operations["listSensorCommands"];
        put?: never;
        /**
         * Queue a command for a sensor
         * @description Creates a pending command for the sensor to pick up on its next poll.
         *     `command_type` is required in the body. Gated by the `sensors.update`
         *     permission. Returns 201 with the created command.
         */
        post: operations["createSensorCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sensors/{sensor_id}/health": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sensor UUID. */
                sensor_id: components["parameters"]["SensorId"];
            };
            cookie?: never;
        };
        /**
         * Latest health metrics for a sensor
         * @description Returns the most recent health-metrics row for the sensor, as a bare
         *     object (not wrapped). 404 when no metrics exist yet.
         */
        get: operations["getSensorHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sensors/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List pending sensor registrations for the current tenant
         * @description Returns the tenant's pending registration keys. Expired-but-still-pending
         *     rows have their `status` reflected as `expired` in the response. On any
         *     service error the handler returns 200 with an empty list.
         */
        get: operations["listPendingSensors"];
        put?: never;
        /**
         * Create a pending sensor registration
         * @description Mints a registration key for a new sensor. `name`, `ip_address`, and
         *     `profile` are required; `ip_address` must be a valid IP. Gated by the
         *     `sensors.create` permission. Returns 200 with the pending registration
         *     and a ready-to-run installation command.
         */
        post: operations["createPendingSensor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform-ca": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fingerprint of the CA behind this platform's edge certificate
         * @description Returns the SHA-256 fingerprint of the certificate authority that signed
         *     this platform's browser-facing TLS certificate, so an operator enrolling
         *     an agent can compare it against the fingerprint the agent displays before
         *     approving it.
         *
         *     The comparison is the point. An agent facing a privately-signed platform
         *     is asked to trust the CA it is shown, and anything able to intercept that
         *     enrollment could present its own. Reading the fingerprint here — over an
         *     authenticated browser session — gives the operator a channel the agent's
         *     connection cannot forge.
         *
         *     The probed URL comes only from server-side configuration
         *     (`WEB_UI_BASE_URL`), never from the request, so this endpoint cannot be
         *     pointed at an arbitrary host.
         *
         *     Always 200. When the fingerprint cannot be determined (no public URL
         *     configured, plain HTTP, or the platform cannot reach its own front door)
         *     `available` is false and `reason` explains why. When the edge certificate
         *     is publicly trusted, `trusted_by_default` is true and no fingerprint is
         *     returned — agents will not prompt at all.
         */
        get: operations["getPlatformCA"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sensors/pending/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pending registration key (e.g. `REG-...`). */
                key: components["parameters"]["PendingKey"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a pending sensor registration
         * @description Deletes the pending registration identified by its registration key.
         *     Gated by the `sensors.delete` permission. 404 when the key is unknown or
         *     belongs to another tenant.
         */
        delete: operations["deletePendingSensor"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get sensor-admin settings
         * @description Returns the current sensor-registration admin settings — the
         *     registration-key expiry, the maximum number of simultaneous pending
         *     registrations, and the source-IP-validation toggle. Read by the Sensor
         *     Configuration page.
         */
        get: operations["getAdminSettings"];
        /**
         * Update sensor-admin settings
         * @description Updates the sensor-registration admin settings. Gated by the
         *     `settings.update` permission. `key_expiration_minutes` must be 5–1440 and
         *     `max_pending_sensors` must be 1–1000; an out-of-range or unparseable body
         *     returns 400.
         */
        put: operations["updateAdminSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/capture-defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Apply tenant-wide capture defaults
         * @description Applies a tenant-wide capture-configuration default (currently the
         *     dedup-TTL observation rest period) to every active sensor by queueing an
         *     `update_config` command for each. Gated by the `settings.update`
         *     permission. Returns the number of sensors a command was queued for.
         *     `dedup_ttl_minutes` is required and must be 1–1440. Returns 503 when the
         *     sensor service is unavailable.
         */
        put: operations["updateTenantCaptureDefaults"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/sensors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List sensors across ALL tenants (platform admin only)
         * @description Platform-admin, cross-tenant, READ-ONLY roll-up powering the VISTA
         *     Operations Fleet view. Unlike `GET /sensors` (tenant-scoped), this lists
         *     every non-deleted sensor across every tenant and carries tenant identity
         *     (`tenant_id` / `tenant_name` / `tenant_slug`) on each row.
         *
         *     Requires a platform token whose ROLE holds `platform.health`, resolved
         *     through platform_user_has_permission() — the role name on the token is
         *     not consulted — matching device-interrogation-service's `/admin/agents`,
         *     the other half of the Fleet view. A tenant token or a role without the
         *     permission gets 403. There is no mutation surface here.
         *
         *     The platform-managed rows every tenant is given (the Platform Discovery
         *     Sensor and the Platform Device Interrogation Agent) appear like any
         *     other sensor; `is_platform_sensor` flags them (platform = "platform" OR
         *     the "system" tag — models.Sensor.IsPlatformManaged).
         */
        get: operations["listAdminSensors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sensors/{sensor_id}/health/history": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sensor UUID. */
                sensor_id: components["parameters"]["SensorId"];
            };
            cookie?: never;
        };
        /**
         * Health-metrics history for a sensor
         * @description Returns up to `limit` health-metrics rows (default 100, max 1000) for the
         *     sensor since `since` (RFC3339; default last 24h), newest first.
         */
        get: operations["getSensorHealthHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sensors/{sensor_id}/discoveries": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sensor UUID. */
                sensor_id: components["parameters"]["SensorId"];
            };
            cookie?: never;
        };
        /**
         * Recent discoveries for a sensor
         * @description Returns the sensor's most recent discoveries (default 50), newest first.
         *     Each item carries the base discovery fields plus selected metadata
         *     (source_ip / version / cipher_suite / key_size) promoted to the top level
         *     when present — so a discovery item is an open object.
         */
        get: operations["getSensorDiscoveries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pcap/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a PCAP/PCAPNG file for processing
         * @description Uploads a capture file (multipart form field `file`, .pcap/.pcapng,
         *     validated by extension + magic bytes + max-size). Creates a processing
         *     job and publishes it for the pcap-processor. Gated by `pcap.upload`.
         *     Returns 201 with the new job id; 413 when the file exceeds the platform
         *     max-upload size.
         */
        post: operations["uploadPcap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pcap/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List PCAP upload/processing jobs */
        get: operations["listPcapJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pcap/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description PCAP job UUID. */
                id: string;
            };
            cookie?: never;
        };
        /** Get a PCAP job by id */
        get: operations["getPcapJob"];
        put?: never;
        post?: never;
        /** Delete a PCAP job */
        delete: operations["deletePcapJob"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sensors/{sensor_id}/regenerate-certificates": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sensor UUID. */
                sensor_id: components["parameters"]["SensorId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate a sensor's mTLS certificates
         * @description Generates a fresh CA + client certificate for the sensor (in-process
         *     x509/RSA) and returns the PEM bundle. Gated by `sensors.manage`.
         */
        post: operations["regenerateSensorCertificates"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sensors/{sensor_id}/certificate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sensor UUID. */
                sensor_id: components["parameters"]["SensorId"];
            };
            cookie?: never;
        };
        /**
         * Get a sensor's current certificate
         * @description Returns the sensor's current certificate metadata (PEM, serial, validity,
         *     revocation state). The success path reads the DB-backed CertificateService;
         *     the contract test pins the request-validation (400) path.
         */
        get: operations["getSensorCertificate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sensors/{sensor_id}/certificates/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sensor UUID. */
                sensor_id: components["parameters"]["SensorId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke a sensor's certificate
         * @description Revokes the sensor's certificate with a reason (compromised / expired /
         *     rotated / manual). Gated by `sensors.manage`. The success path uses the
         *     DB-backed CertificateService; the contract test pins the request-validation
         *     (400) paths.
         */
        post: operations["revokeSensorCertificate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sensors/{sensor_id}/certificates/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sensor UUID. */
                sensor_id: components["parameters"]["SensorId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate a sensor's certificate from a CSR
         * @description Issues a new certificate from the supplied CSR (revoking the old one).
         *     Gated by `sensors.manage`. The success path uses the DB-backed
         *     CertificateService + CA manager; the contract test pins the
         *     request-validation + sensor-not-found (400/404) paths.
         */
        post: operations["rotateSensorCertificate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sensors/{sensor_id}/discovery-jobs/{job_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sensor UUID. */
                sensor_id: components["parameters"]["SensorId"];
                /** @description Discovery job UUID — the job the platform dispatched to this sensor. */
                job_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * A sensor reports that a dispatched discovery job has finished
         * @description Tenant-sensor dispatch. The one sensor-agent-facing route this spec
         *     carries, because it closes a job the tenant is watching on Discovery →
         *     Discovery Jobs. The caller is authenticated **as the sensor** (the
         *     `sensors` group's mTLS/HMAC auth, fail-closed when agent mTLS is
         *     required) — not by a tenant JWT.
         *
         *     The job's RESULTS do not travel here. The sensor submits them through
         *     its ordinary `POST /sensors/{sensor_id}/discoveries` batch, tagged
         *     `discovery_method: active` and carrying the `job_id` in
         *     `raw_metadata`, so they flow `sensor_discoveries` → discovery-processor
         *     → inventory exactly like passive data. This call only marks the job
         *     `completed` or `failed` with the sensor's counts.
         *
         *     The job must belong to the sensor's tenant and be assigned to this
         *     sensor (404 otherwise — an unknown, cross-tenant, differently
         *     assigned and platform-run job all answer the same). A job that is no
         *     longer `awaiting_sensor` (the platform already failed it as "sensor
         *     offline", or it was cancelled) answers 409: the late report is kept in
         *     the job's metadata as evidence, but a verdict the tenant has already
         *     been shown is not rewritten.
         */
        post: operations["completeDispatchedDiscoveryJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description One recorded configuration change. Both the device's own overrides and
         *     the tenant's fleet defaults appear, because a device's effective
         *     configuration moves when either does.
         */
        AgentConfigChange: {
            /** Format: date-time */
            changed_at: string;
            /** @description The account that made the change. Empty when it was not made by a user. */
            changed_by: string;
            /** @enum {string} */
            scope: "device" | "fleet";
            /** @description The setting keys whose value actually moved, derived server-side so no client re-implements the comparison. */
            keys: string[];
            values_before: {
                [key: string]: unknown;
            };
            values_after: {
                [key: string]: unknown;
            };
        };
        AgentConfigHistory: {
            /** @description Newest first. Always present, never null — a device nobody has configured has an empty history, not an unknown one. */
            changes: components["schemas"]["AgentConfigChange"][];
        };
        /**
         * @description What the device runs, what this platform release ships, and whether they
         *     differ. The expected version is the release the PLATFORM is running,
         *     because the device binaries ship from the same tag — so the platform can
         *     only report a device as behind once it has itself been upgraded, and it
         *     never queries an external service to find out.
         */
        AgentConfigVersion: {
            /** @description What the device last reported. Empty when it has never reported one. */
            device: string;
            /** @description The version shipping with this platform release. Empty when the platform does not know its own. */
            expected: string;
            /**
             * @description `unknown` when the comparison could not be made — either side
             *     missing or unparseable. Deliberately distinct from `current`: a
             *     comparison that was not made must never render as up to date.
             *     `ahead` is a device newer than the platform, which happens mid-
             *     rollout and also when the wrong binary was installed.
             * @enum {string}
             */
            state: "unknown" | "current" | "behind" | "ahead";
        };
        /**
         * @description One setting: its effective value, where that value came from, and enough
         *     of its registry entry for a client to render a control for it without
         *     hard-coding a second copy of the rules.
         */
        AgentConfigSetting: {
            /**
             * @description The setting's name, spelled as the device's own config file spells it.
             * @example host_inventory_enabled
             */
            key: string;
            /** @description The effective value — a boolean, a whole number or a string. */
            value: boolean | number | string;
            /**
             * @description Where the effective value came from. `built_in` is the device's own
             *     default (nobody has set it), `fleet` the tenant default, `device` an
             *     override on this device. Without this the console cannot offer
             *     "revert to fleet default", or say whether a value is deliberate.
             * @enum {string}
             */
            origin: "built_in" | "fleet" | "device";
            /** @enum {string} */
            kind: "bool" | "int" | "enum";
            /**
             * @description When the device adopts a change. `restart` settings sit at
             *     `awaiting_restart` until the process restarts; showing them as
             *     applied on the next check-in would be false.
             * @enum {string}
             */
            apply: "immediate" | "restart";
            /**
             * @description Operator-facing name, present only for a setting whose key reads
             *     badly when turned into words. Absent means the client derives the
             *     name from `key`.
             */
            label?: string;
            /** @description Operator-facing explanation of what the setting does. */
            description: string;
            /**
             * @description Present when turning this setting ON requires explicit
             *     confirmation, and states what begins to be collected. Only settings
             *     that start a new kind of collection carry one.
             */
            confirm?: string;
            /** Format: int64 */
            min?: number;
            /** Format: int64 */
            max?: number;
            allowed?: string[];
        };
        /** @description How far the device has converged on the desired settings. */
        AgentConfigStatus: {
            /** @enum {string} */
            state: "never_reported" | "not_reporting" | "pending" | "awaiting_restart" | "applied" | "failed";
            /**
             * @description Content hash of the effective settings. The device reports the
             *     revision it has adopted; equality is what "applied" means. A hash
             *     rather than a counter, so a changed fleet default moves every
             *     inheriting device with nothing having to notify them.
             */
            desired_revision: string;
            /**
             * Format: date-time
             * @description When the device last reported. Absent if it never has.
             */
            reported_at?: string;
            /** @description The device's own reason, per setting it could not apply. */
            failures?: {
                [key: string]: string;
            };
            /** @description Settings accepted but not adopted until the device restarts. */
            pending_restart?: string[];
        };
        SensorConfigResponse: {
            /** @enum {string} */
            runtime: "sensor";
            settings: components["schemas"]["AgentConfigSetting"][];
            status: components["schemas"]["AgentConfigStatus"];
            version: components["schemas"]["AgentConfigVersion"];
        };
        SensorConfigDefaultsResponse: {
            /** @enum {string} */
            runtime: "sensor";
            settings: components["schemas"]["AgentConfigSetting"][];
        };
        AgentConfigWriteRequest: {
            /**
             * @description The settings to store, keyed by setting name. The whole set is
             *     replaced: a key left out is cleared. A null value clears that one
             *     key. An explicit `false` is a value, not an absence.
             * @example {
             *       "host_inventory_enabled": true,
             *       "host_inventory_interval_seconds": 21600
             *     }
             */
            values: {
                [key: string]: boolean | number | string | null;
            };
            /**
             * @description Acknowledges any setting whose registry entry demands confirmation.
             *     The server decides whether one is needed; omitting the flag cannot
             *     waive it.
             */
            confirmed?: boolean;
        };
        AgentConfigWriteResponse: {
            /**
             * @description One line per setting that actually changed, rendered as key, then the old and new values.
             * @example [
             *       "host_inventory_enabled: false → true"
             *     ]
             */
            changed: string[];
            /**
             * @description Values silently raised to a setting's floor. The device does this on
             *     its own today and logs it locally, so whoever typed the value never
             *     learns it was changed; saying so here is the point.
             * @example [
             *       "host_inventory_interval_seconds: raised 300 to the minimum of 3600"
             *     ]
             */
            adjusted: string[];
            /**
             * @description Changed settings the device can only adopt on restart. An operator
             *     who is not told will read the resulting `awaiting_restart` as a
             *     failure.
             */
            needs_restart: string[];
        };
        AgentConfigConfirmationRequired: {
            error: string;
            needs_confirming: {
                key: string;
                /** @description What begins to be collected if this is turned on. */
                confirm: string;
            }[];
        };
        /**
         * @description A tenant sensor. Field presence follows models.Sensor's json tags:
         *     non-`omitempty` fields are always present (nullable pointers serialize as
         *     null). The handler also emits a legacy `config` object (a zero-valued
         *     models.SensorConfig — `config,omitempty` does NOT omit a non-pointer
         *     struct) plus optional legacy fields (type, last_seen, capabilities,
         *     location, legacy_tags, metadata). Those are not read by the v2 frontend
         *     and are intentionally NOT pinned here — hence `additionalProperties:
         *     true`. This contract pins the stable fields the UI relies on; the legacy
         *     blob is dropped when the endpoint is hardened to ADR-0002.
         */
        Sensor: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            name: string;
            /** @description 'network' | 'endpoint' | 'cloud' | 'api'. */
            sensor_type: string;
            description: string | null;
            platform: string;
            version: string;
            profile: string;
            /** @description When true, the sensor does not check in / heartbeat / stream discoveries; the platform still shows it registered and imports findings out-of-band. */
            air_gapped: boolean;
            /** @description 'pending' | 'active' | 'inactive' | 'error' | 'offline'. */
            status: string;
            network_interfaces: string[] | null;
            /** @description OS interfaces eligible for scoped DNS, reported by the current collector. */
            reported_dns_interfaces?: string[];
            /** @description Supported commands reported by the current sensor binary in its authenticated heartbeat. Missing reports clear prior capabilities. */
            reported_capabilities?: string[];
            /** @description Full host NIC inventory the sensor reports in its heartbeat; populates the UI interface picker. Distinct from network_interfaces (the monitored subset). */
            available_interfaces: string[] | null;
            tags: string[] | null;
            ip_address: string | null;
            /**
             * Format: uuid
             * @description The asset the HOST THIS SENSOR RUNS ON resolved to, from the
             *     sensor's own self-reported host identity (hostname, FQDN,
             *     interfaces) turned into a host observation. Null until the first
             *     successful self-observation, and always null for a sensor build
             *     old enough to send none.
             */
            asset_id: string | null;
            /** Format: date-time */
            last_heartbeat: string | null;
            /** @description Sensor's data-send cadence in seconds (null until the sensor reports it). */
            reporting_interval?: number | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            deleted_at: string | null;
            /**
             * @description Every IP the sensor host reported, with its prefix. Present on the
             *     single-sensor read only (the list endpoint omits it). A capture host
             *     is often multi-homed and watching several segments at once, which
             *     `ip_address` — the primary, i.e. the address the host reaches the
             *     platform from — cannot express on its own.
             */
            addresses?: components["schemas"]["AgentAddress"][];
        } & {
            [key: string]: unknown;
        };
        /** @description One IP bound to one interface on an agent host. */
        AgentAddress: {
            /** @description Host interface the address is bound to (e.g. eth0, "Ethernet 2"). */
            interface_name: string;
            /** @description The bare IP, without a prefix suffix. */
            address: string;
            /** @description Network prefix (24 for 192.0.2.173/24). Absent when the agent reported none. */
            prefix_length?: number;
            /** @description True for the address the agent reaches the control plane from. At most one per agent. */
            is_primary: boolean;
        };
        /**
         * @description CURRENT list envelope for GET /sensors: the collection is wrapped under
         *     `sensors`. On an empty/nil result the field can serialize as JSON null
         *     (the empty-slice-as-null quirk also seen in the scopes slice), so it is
         *     typed as a nullable array.
         */
        SensorListResponse: {
            sensors: components["schemas"]["Sensor"][] | null;
        };
        /**
         * @description One row of the platform-admin, cross-tenant Fleet view (GET
         *     /admin/sensors). Mirrors the canonical models.Sensor telemetry but adds
         *     tenant identity (tenant_name / tenant_slug from a join to tenants) and a
         *     derived is_platform_sensor flag. Every field maps to a real
         *     sensors/tenants column — no invented telemetry. Unlike the tenant Sensor
         *     schema this is closed (additionalProperties: false): the admin handler
         *     emits an explicit struct (handlers.AdminSensor), not the legacy blob.
         */
        AdminSensor: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /** @description Owning tenant's display name (empty string if the tenant row is missing). */
            tenant_name: string;
            /** @description Owning tenant's slug (empty string if the tenant row is missing). */
            tenant_slug: string;
            name: string;
            description: string | null;
            /** @description 'network' | 'endpoint' | 'cloud' | 'api'. */
            sensor_type: string;
            /** @description "platform" for the in-cluster Platform Sensor. */
            platform: string;
            /** @description "system" for the Platform Sensor. */
            version: string;
            /** @description "discovery" for the Platform Sensor. */
            profile: string;
            /** @description 'pending' | 'active' | 'inactive' | 'error' | 'offline'. */
            status: string;
            air_gapped: boolean;
            network_interfaces: string[] | null;
            available_interfaces: string[] | null;
            tags: string[] | null;
            ip_address: string | null;
            /** @description True for a platform-managed row (platform = "platform" OR the "system" tag — models.Sensor.IsPlatformManaged). A platform row whose profile is device_interrogation is the in-cluster interrogation agent, not a sensor. */
            is_platform_sensor: boolean;
            /** Format: date-time */
            last_heartbeat: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description Envelope for GET /admin/sensors: the cross-tenant collection wrapped
         *     under `sensors`, with a `count`. The handler always initializes the
         *     slice, so `sensors` is a (possibly empty) array, never null.
         */
        AdminSensorListResponse: {
            sensors: components["schemas"]["AdminSensor"][];
            count: number;
        };
        /** @description Sensor count breakdown for the Operations dashboard. */
        SensorStats: {
            total_sensors: number;
            active_sensors: number;
            inactive_sensors: number;
            error_sensors: number;
            pending_sensors: number;
            total_discoveries: number;
            total_packets: number;
            total_errors: number;
            /** Format: date-time */
            last_updated: string;
        };
        /** @description GET /sensors/discovery-counts — sensor id → discovery count. */
        DiscoveryCountsResponse: {
            counts: {
                [key: string]: number;
            };
        };
        /** @description Request body for PUT /sensors/{sensor_id}/interfaces — interfaces to add and/or remove. Both fields optional. */
        UpdateSensorInterfacesRequest: {
            add?: string[];
            remove?: string[];
        };
        /** @description Response for PUT /sensors/{sensor_id}/interfaces — `{ message, interfaces }` with the resulting interface set. */
        UpdateSensorInterfacesResponse: {
            message: string;
            interfaces: string[];
        };
        /**
         * @description Request body for PUT /sensors/{sensor_id}/config. All fields optional;
         *     only provided fields are applied. Capture options
         *     (active_probing/network_discovery/host_observation/dedup_ttl_minutes)
         *     additionally queue an update_config command for the sensor.
         */
        UpdateSensorConfigRequest: {
            air_gapped?: boolean;
            scan_interval?: number;
            tags?: string[];
            description?: string;
            active_probing?: boolean;
            network_discovery?: boolean;
            /**
             * @description Passive host observation: ARP, DHCP, mDNS, NetBIOS, DNS answers,
             *     LLDP and CDP decoded into host identity. Queues an update_config
             *     command, but the sensor applies it on its next RESTART rather than
             *     immediately — the packet-capture filter is fixed when the interface
             *     handle opens, so enabling the decoders without reopening it would
             *     leave them running and receiving nothing.
             */
            host_observation?: boolean;
            dedup_ttl_minutes?: number;
            /**
             * @description Sensor data-send cadence in seconds. Must be one of the allowed
             *     presets (30, 60, 300, 900, 1800, 3600, 7200, 14400, 28800, 43200,
             *     86400); other values are rejected. Queues an update_config command.
             */
            reporting_interval?: number;
        };
        /** @description Response for PUT /sensors/{sensor_id}/config — `{ message, sensor }` with the updated config subset. */
        UpdateSensorConfigResponse: {
            message: string;
            sensor: {
                /** Format: uuid */
                id: string;
                air_gapped: boolean;
                description: string | null;
                tags: string[] | null;
                /** Format: date-time */
                updated_at: string;
            };
        };
        /** @description GET /sensors/{sensor_id}/health/history — `{ metrics, count, since }`. */
        SensorHealthHistoryResponse: {
            metrics: components["schemas"]["SensorHealthMetrics"][];
            count: number;
            /** Format: date-time */
            since: string;
        };
        /**
         * @description A single sensor discovery row. Open object: in addition to the base
         *     fields below, selected metadata keys (source_ip, version, cipher_suite,
         *     key_size) are promoted to the top level when present.
         */
        SensorDiscovery: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            sensor_id: string;
            batch_id: string;
            protocol: string;
            dest_ip: string;
            port: number;
            confidence: number;
            /** Format: date-time */
            timestamp: string;
            /** Format: date-time */
            created_at: string;
        } & {
            [key: string]: unknown;
        };
        /** @description GET /sensors/{sensor_id}/discoveries — `{ discoveries, count }`. */
        SensorDiscoveriesResponse: {
            discoveries: components["schemas"]["SensorDiscovery"][];
            count: number;
        };
        /**
         * @description A PCAP upload/processing job (models.PcapUploadJob). `file_path` is never
         *     serialized (json:"-"). `protocols_found` / `capture_time_range` serialize
         *     as JSON null when unset (nil map); the optional timestamps + error_message
         *     are omitted when absent.
         */
        PcapUploadJob: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: uuid */
            uploaded_by: string;
            original_filename: string;
            file_size_bytes: number;
            status: string;
            discovery_count: number;
            packet_count: number;
            protocols_found: {
                [key: string]: number;
            } | null;
            capture_time_range: Record<string, never> | null;
            error_message?: string;
            /** Format: date-time */
            processing_started_at?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            completed_at?: string;
        };
        /** @description POST /pcap/upload — `{ job_id, status }` for the created job. */
        PcapUploadResponse: {
            /** Format: uuid */
            job_id: string;
            status: string;
        };
        /** @description GET /pcap/jobs — `{ jobs, total, page, limit }`. `jobs` is null on an empty page. */
        PcapJobListResponse: {
            jobs: components["schemas"]["PcapUploadJob"][] | null;
            total: number;
            page: number;
            limit: number;
        };
        /** @description Request body for the revoke endpoint (reason required). */
        RevokeCertificateRequest: {
            /** @description compromised / expired / rotated / manual. */
            reason: string;
        };
        /** @description Request body for the rotate endpoint (PEM CSR). */
        RotateCertificateRequest: {
            csr: string;
        };
        /** @description POST /sensors/{sensor_id}/regenerate-certificates — fresh CA + client cert PEM bundle. */
        RegenerateCertificatesResponse: {
            sensor_id: string;
            client_cert: string;
            client_key: string;
            server_ca_cert: string;
            expires_at: string;
            message: string;
        };
        /** @description POST /sensors/{sensor_id}/certificates/revoke result. */
        RevokeCertificateResponse: {
            sensor_id: string;
            /** Format: date-time */
            revoked_at: string;
            reason: string;
            message: string;
        };
        /**
         * @description A sensor's report that a dispatched discovery job finished. Mirrors
         *     shared/sensordispatch.Completion, the struct both the sensor and the
         *     platform compile against. Counts are never negative; `status` is
         *     `completed` or `failed`. `discoveries_submitted` is how many result
         *     rows the sensor pushed through the discovery batch route for this job
         *     — zero with `completed` is a legitimate answer (every target answered,
         *     none spoke a protocol the probe recognises).
         */
        DiscoveryJobCompletion: {
            /** @enum {string} */
            status: "completed" | "failed";
            /** @description Why, when status is `failed`. */
            error_message?: string;
            total_targets?: number;
            successful_targets?: number;
            failed_targets?: number;
            discoveries_submitted?: number;
        };
        /** @description POST /sensors/{sensor_id}/discovery-jobs/{job_id}/complete result. */
        DiscoveryJobCompletionResponse: {
            /** @enum {string} */
            status: "success";
            message: string;
            /** Format: uuid */
            job_id: string;
        };
        /** @description POST /sensors/{sensor_id}/certificates/rotate result. */
        RotateCertificateResponse: {
            sensor_id: string;
            client_cert: string;
            server_ca_cert: string;
            /** Format: date-time */
            certificate_expires_at: string;
            message: string;
        };
        /**
         * @description GET /sensors/{sensor_id}/certificate — certificate metadata. Open object;
         *     revoked_at / revocation_reason are null when the cert is active.
         */
        SensorCertificateResponse: {
            sensor_id: string;
            certificate_pem: string;
            serial_number: string;
            /** Format: date-time */
            issued_at: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            revoked_at?: string | null;
            revocation_reason?: string | null;
            is_revoked: boolean;
            is_expired: boolean;
            days_until_expiry: number;
        } & {
            [key: string]: unknown;
        };
        /** @description Bare acknowledgement envelope used by mutating sensor endpoints. */
        MessageResponse: {
            message: string;
        };
        /**
         * @description Sensor-registration admin settings (handlers.AdminSettings). Used as both
         *     the GET /admin/settings response body and the PUT /admin/settings request
         *     body. All three fields are present in the response; in a PUT each must be
         *     in range (key expiry 5–1440, max pending 1–1000) or the update is
         *     rejected with 400.
         */
        AdminSettings: {
            /** @description Minutes a registration key stays valid (5–1440). */
            key_expiration_minutes: number;
            /** @description Maximum simultaneous pending registrations (1–1000). */
            max_pending_sensors: number;
            /** @description Whether registration enforces source-IP validation. */
            require_ip_validation: boolean;
        };
        /** @description Request body for PUT /admin/capture-defaults. */
        UpdateCaptureDefaultsRequest: {
            /** @description Observation rest period in minutes applied to all active sensors (1–1440). */
            dedup_ttl_minutes: number;
        };
        /** @description Result of applying tenant-wide capture defaults. */
        CaptureDefaultsResponse: {
            message: string;
            /** @description Number of active sensors an update_config command was queued for. */
            sensors_queued: number;
        };
        /**
         * @description A command queued for a sensor (models.SensorCommand). Pointer timestamps
         *     and `error_message` serialize as null until set.
         */
        SensorCommand: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            sensor_id: string;
            command_type: string;
            payload: {
                [key: string]: unknown;
            } | null;
            /** @description 'pending' | 'delivered' | 'acknowledged' | 'completed' | 'failed'. */
            status: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            delivered_at: string | null;
            /** Format: date-time */
            acknowledged_at: string | null;
            /** Format: date-time */
            completed_at: string | null;
            error_message: string | null;
            /** Format: date-time */
            updated_at: string | null;
            /** @description Sensor execution result/output; null until acknowledged. */
            response_data: {
                [key: string]: unknown;
            } | null;
        };
        /** @description CURRENT envelope for POST /sensors/{id}/commands — `{ "command": {...} }`. */
        SensorCommandResponse: {
            command: components["schemas"]["SensorCommand"];
        };
        /** @description CURRENT envelope for GET /sensors/{id}/commands — `{ "commands": [...] }`. */
        SensorCommandListResponse: {
            commands: components["schemas"]["SensorCommand"][] | null;
        };
        /** @description Request body for POST /sensors/{id}/commands. */
        CreateSensorCommandRequest: {
            command_type: string;
            payload?: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /** @description Request body for PUT /sensors/{id}/status. */
        UpdateSensorStatusRequest: {
            status: string;
        };
        /** @description Latest health-metrics row for a sensor (models.SensorHealthMetrics). */
        SensorHealthMetrics: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            sensor_id: string;
            uptime_seconds: number;
            memory_usage_bytes: number;
            cpu_usage_percent: number;
            packets_captured: number;
            discoveries_made: number;
            errors_count: number;
            /**
             * @description Heartbeat counters that have no column of their own — today, the
             *     eight `host_observations_*` metrics the passive host-observation
             *     pipeline reports (offered, decoded, emitted, malformed,
             *     queue_dropped, emit_dropped, coalesce_dropped, pending).
             *
             *     ABSENT means the sensor reported none: an older build, or host
             *     observation switched off. That is deliberately distinct from an
             *     empty object, which would mean it reported the set and every counter
             *     was zero — "not running" and "running and seeing nothing" must not
             *     look the same.
             *
             *     An open map rather than named fields because the set grows with the
             *     decoders: a protocol added to shared/hostobs brings its own
             *     counters, and a schema change per counter is how a diagnostic stops
             *     being worth adding.
             */
            extra_counters?: {
                [key: string]: number;
            } | null;
            /** Format: date-time */
            recorded_at: string;
        };
        /**
         * @description A pending sensor registration (models.PendingSensorRegistration). The
         *     handler may emit additional legacy fields; the stable fields the UI reads
         *     are pinned here.
         */
        PendingSensor: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            registration_key: string;
            name: string;
            ip_address: string;
            /** @description 'datacenter_host' | 'cloud_instance' | 'end_user_machine' | 'air_gapped' | 'device_interrogation'. */
            profile: string;
            network_interfaces: string[] | null;
            tags: string[] | null;
            description: string | null;
            metadata: {
                [key: string]: unknown;
            } | null;
            /** @description 'pending' | 'used' | 'expired' | 'cancelled'. */
            status: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            used_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        } & {
            [key: string]: unknown;
        };
        /** @description CURRENT envelope for GET /sensors/pending — `{ "pending_sensors": [...] }`. */
        PendingSensorListResponse: {
            pending_sensors: components["schemas"]["PendingSensor"][];
        };
        /**
         * @description Identity of the CA behind this platform's edge certificate, for an
         *     operator to compare against what an enrolling agent displays.
         */
        PlatformCAResponse: {
            /** @description Whether the platform's certificate could be inspected at all. */
            available: boolean;
            /**
             * @description Why no fingerprint is shown — either because it could not be
             *     determined, or because the certificate is publicly trusted and no
             *     approval step exists.
             */
            reason?: string;
            /**
             * @description The edge certificate verifies against the public trust store. Agents
             *     enroll with no trust prompt, so there is nothing to compare.
             */
            trusted_by_default: boolean;
            /** @description The public origin that was inspected. */
            public_url?: string;
            /** @description Lowercase unseparated hex SHA-256 of the CA certificate's DER bytes. */
            fingerprint_sha256?: string;
            /** @description The same fingerprint, colon-grouped for a human to read against a terminal. */
            fingerprint_display?: string;
            subject?: string;
            issuer?: string;
            /** Format: date-time */
            not_after?: string;
            /**
             * @description False means the platform did not present its root and this is the
             *     issuer-most intermediate it did present.
             */
            self_signed?: boolean;
        };
        /** @description Request body for POST /sensors/pending. */
        CreatePendingSensorRequest: {
            name: string;
            ip_address: string;
            profile: string;
            network_interfaces?: string[];
            tags?: string[];
            description?: string;
        } & {
            [key: string]: unknown;
        };
        /** @description CURRENT envelope for POST /sensors/pending success. */
        CreatePendingSensorResponse: {
            pending_sensor: components["schemas"]["PendingSensor"];
            installation_command: string;
        };
        /**
         * @description CURRENT error shape returned by sensor-manager endpoints today: a single
         *     human-readable string under `error`. Some 400s carry extra sibling keys,
         *     so additionalProperties is permitted. Unstructured — cannot be branched
         *     on safely. Superseded by the ADR-0002 `Error` envelope below as
         *     endpoints are hardened.
         */
        LegacyError: {
            error: string;
        } & {
            [key: string]: unknown;
        };
        /** @description ADR-0002 error envelope. Clients branch on `error.code`, never on `message`. */
        Error: {
            error: {
                /** @description Stable, machine-readable enum (e.g. sensor_not_found). */
                code: string;
                /** @description Human-readable, safe to surface in UI. */
                message: string;
                details?: components["schemas"]["ErrorDetail"][];
                /** @description For support correlation. */
                request_id?: string;
            };
        };
        ErrorDetail: {
            field: string;
            issue: string;
        };
        /** @description ADR-0002 pagination block for collection envelopes. */
        Pagination: {
            total: number;
            limit: number;
            offset: number;
            /** @description Offset of the next page, or null when there are no more. */
            next_offset?: number | null;
        };
    };
    responses: {
        /** @description Invalid request. */
        LegacyBadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["LegacyError"];
            };
        };
        /** @description Missing or invalid authentication. */
        LegacyUnauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["LegacyError"];
            };
        };
        /** @description Caller lacks the required role (platform-admin). */
        LegacyForbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["LegacyError"];
            };
        };
        /** @description Resource not found. */
        LegacyNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["LegacyError"];
            };
        };
        /** @description Unexpected server error. */
        LegacyServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["LegacyError"];
            };
        };
        /** @description A required dependency is unavailable. */
        LegacyServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["LegacyError"];
            };
        };
    };
    parameters: {
        /** @description Sensor UUID. */
        SensorId: string;
        /** @description Pending registration key (e.g. `REG-...`). */
        PendingKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listSensors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The tenant's sensors. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorListResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
        };
    };
    getSensorStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sensor stats. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorStats"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
        };
    };
    getSensorDiscoveryCounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Map of sensor id → discovery count. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryCountsResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
        };
    };
    getSensor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sensor UUID. */
                sensor_id: components["parameters"]["SensorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The sensor (bare object). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sensor"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
            404: components["responses"]["LegacyNotFound"];
        };
    };
    deleteSensor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sensor UUID. */
                sensor_id: components["parameters"]["SensorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deletion acknowledged. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
            403: components["responses"]["LegacyForbidden"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    updateSensorStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sensor UUID. */
                sensor_id: components["parameters"]["SensorId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSensorStatusRequest"];
            };
        };
        responses: {
            /** @description Status updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    updateSensorInterfaces: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sensor UUID. */
                sensor_id: components["parameters"]["SensorId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSensorInterfacesRequest"];
            };
        };
        responses: {
            /** @description Interfaces updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateSensorInterfacesResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    updateSensorConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sensor UUID. */
                sensor_id: components["parameters"]["SensorId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSensorConfigRequest"];
            };
        };
        responses: {
            /** @description Configuration updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateSensorConfigResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    getSensorFleetDefaults: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The fleet defaults. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorConfigDefaultsResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    putSensorFleetDefaults: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentConfigWriteRequest"];
            };
        };
        responses: {
            /** @description The defaults were saved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentConfigWriteResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            /** @description A setting in this change needs explicit confirmation. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentConfigConfirmationRequired"];
                };
            };
            500: components["responses"]["LegacyServerError"];
        };
    };
    getSensorConfigHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The sensor's UUID. */
                sensor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The change history. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentConfigHistory"];
                };
            };
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    getSensorDesiredConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The sensor's UUID. */
                sensor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The sensor's configuration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorConfigResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    putSensorDesiredConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The sensor's UUID. */
                sensor_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentConfigWriteRequest"];
            };
        };
        responses: {
            /** @description The override was saved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentConfigWriteResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            404: components["responses"]["LegacyNotFound"];
            /** @description A setting in this change needs explicit confirmation. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentConfigConfirmationRequired"];
                };
            };
            500: components["responses"]["LegacyServerError"];
        };
    };
    listSensorCommands: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sensor UUID. */
                sensor_id: components["parameters"]["SensorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The sensor's commands. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorCommandListResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    createSensorCommand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sensor UUID. */
                sensor_id: components["parameters"]["SensorId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSensorCommandRequest"];
            };
        };
        responses: {
            /** @description The created command. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorCommandResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    getSensorHealth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sensor UUID. */
                sensor_id: components["parameters"]["SensorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest health metrics (bare object). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorHealthMetrics"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
            404: components["responses"]["LegacyNotFound"];
        };
    };
    listPendingSensors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The tenant's pending registrations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingSensorListResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
        };
    };
    createPendingSensor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePendingSensorRequest"];
            };
        };
        responses: {
            /** @description The created pending registration plus install command. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatePendingSensorResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    getPlatformCA: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Platform CA fingerprint, or why it is unavailable. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformCAResponse"];
                };
            };
            401: components["responses"]["LegacyUnauthorized"];
        };
    };
    deletePendingSensor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pending registration key (e.g. `REG-...`). */
                key: components["parameters"]["PendingKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deletion acknowledged. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    getAdminSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current admin settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSettings"];
                };
            };
            401: components["responses"]["LegacyUnauthorized"];
        };
    };
    updateAdminSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminSettings"];
            };
        };
        responses: {
            /** @description Settings updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
        };
    };
    updateTenantCaptureDefaults: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCaptureDefaultsRequest"];
            };
        };
        responses: {
            /** @description Capture defaults applied; per-sensor commands queued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureDefaultsResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
            503: components["responses"]["LegacyServiceUnavailable"];
        };
    };
    listAdminSensors: {
        parameters: {
            query?: {
                /** @description Narrow the cross-tenant roll-up to a single tenant (operator scope). */
                tenant_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All sensors across all tenants. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSensorListResponse"];
                };
            };
            401: components["responses"]["LegacyUnauthorized"];
            403: components["responses"]["LegacyForbidden"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    getSensorHealthHistory: {
        parameters: {
            query?: {
                since?: string;
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Sensor UUID. */
                sensor_id: components["parameters"]["SensorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health-metrics history. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorHealthHistoryResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    getSensorDiscoveries: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Sensor UUID. */
                sensor_id: components["parameters"]["SensorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent discoveries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorDiscoveriesResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    uploadPcap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Upload accepted; processing job created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PcapUploadResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
            /** @description File exceeds the platform max-upload size. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegacyError"];
                };
            };
            500: components["responses"]["LegacyServerError"];
            503: components["responses"]["LegacyServiceUnavailable"];
        };
    };
    listPcapJobs: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of pcap jobs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PcapJobListResponse"];
                };
            };
            401: components["responses"]["LegacyUnauthorized"];
            500: components["responses"]["LegacyServerError"];
            503: components["responses"]["LegacyServiceUnavailable"];
        };
    };
    getPcapJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description PCAP job UUID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The pcap job (bare object). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PcapUploadJob"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
            503: components["responses"]["LegacyServiceUnavailable"];
        };
    };
    deletePcapJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description PCAP job UUID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
            503: components["responses"]["LegacyServiceUnavailable"];
        };
    };
    regenerateSensorCertificates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sensor UUID. */
                sensor_id: components["parameters"]["SensorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The regenerated certificate bundle. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegenerateCertificatesResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    getSensorCertificate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sensor UUID. */
                sensor_id: components["parameters"]["SensorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The certificate metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorCertificateResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            404: components["responses"]["LegacyNotFound"];
        };
    };
    revokeSensorCertificate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sensor UUID. */
                sensor_id: components["parameters"]["SensorId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevokeCertificateRequest"];
            };
        };
        responses: {
            /** @description Certificate revoked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeCertificateResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    rotateSensorCertificate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sensor UUID. */
                sensor_id: components["parameters"]["SensorId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RotateCertificateRequest"];
            };
        };
        responses: {
            /** @description Certificate rotated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotateCertificateResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            404: components["responses"]["LegacyNotFound"];
            500: components["responses"]["LegacyServerError"];
        };
    };
    completeDispatchedDiscoveryJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sensor UUID. */
                sensor_id: components["parameters"]["SensorId"];
                /** @description Discovery job UUID — the job the platform dispatched to this sensor. */
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscoveryJobCompletion"];
            };
        };
        responses: {
            /** @description Completion recorded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryJobCompletionResponse"];
                };
            };
            400: components["responses"]["LegacyBadRequest"];
            401: components["responses"]["LegacyUnauthorized"];
            404: components["responses"]["LegacyNotFound"];
            /** @description The job is no longer awaiting this sensor; the report was recorded but the job's status stands. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegacyError"];
                };
            };
            500: components["responses"]["LegacyServerError"];
            503: components["responses"]["LegacyServiceUnavailable"];
        };
    };
}
