// Code generated by scripts/generate-asset-classes.mjs from
// standards/asset-classes.yaml. DO NOT EDIT — edit the YAML and run
// `make generate`.
//
// The EFFECTIVE attribute schema of every class — its own properties merged
// over every ancestor's — which is the same content as the Go mirror
// `shared/assetclass/attribute_schemas_gen.json`, typed.
//
// This is the vocabulary behind `attr.<name>` in the query language (§4.2).
// That namespace is flat and global: `attr.model` is ONE field, not one per
// class, because a query is a predicate over `assets` and its `attributes`
// jsonb holds whichever class's keys the row carries. The generator therefore
// refuses to emit two classes declaring one name with two types.

import type { AssetClassKey } from './classes.gen';

/** The value types a class attribute may declare. */
export type AssetAttributeType = "string" | "integer" | "number" | "boolean" | "array";

/** One class-specific attribute: a JSON-schema property restricted to the
 *  shapes the registry allows. */
export interface AssetAttributeProperty {
  type: AssetAttributeType;
  description: string;
  /** Closed value set. Only a string attribute may declare one. */
  enum?: readonly string[];
  /** The element type of an array attribute. */
  items?: { type: AssetAttributeType };
}

/** A class's effective attribute schema. `additionalProperties` is always
 *  false — an attribute nothing declared is a collection bug, not a bonus. */
export interface AssetAttributeSchema {
  type: 'object';
  additionalProperties: false;
  properties: Readonly<Record<string, AssetAttributeProperty>>;
}

export const ATTRIBUTE_SCHEMAS: Readonly<Record<AssetClassKey, AssetAttributeSchema>> = {
  "hardware": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "vendor": {
        type: "string",
        description: "Manufacturer or brand as reported by the device.",
      },
      "model": {
        type: "string",
        description: "Manufacturer model designation.",
      },
      "asset_tag": {
        type: "string",
        description: "Organisation's own inventory tag, if one is affixed.",
      },
    },
  },
  "computer": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "vendor": {
        type: "string",
        description: "Manufacturer or brand as reported by the device.",
      },
      "model": {
        type: "string",
        description: "Manufacturer model designation.",
      },
      "asset_tag": {
        type: "string",
        description: "Organisation's own inventory tag, if one is affixed.",
      },
      "operating_system": {
        type: "string",
        description: "OS product name, e.g. \"Ubuntu\", \"Windows Server\".",
      },
      "os_version": {
        type: "string",
        description: "OS version string as reported.",
      },
      "architecture": {
        type: "string",
        description: "CPU architecture, e.g. amd64, arm64.",
      },
      "cpu_count": {
        type: "integer",
        description: "Logical CPU count.",
      },
      "memory_mb": {
        type: "integer",
        description: "Installed memory in mebibytes.",
      },
    },
  },
  "server": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "vendor": {
        type: "string",
        description: "Manufacturer or brand as reported by the device.",
      },
      "model": {
        type: "string",
        description: "Manufacturer model designation.",
      },
      "asset_tag": {
        type: "string",
        description: "Organisation's own inventory tag, if one is affixed.",
      },
      "operating_system": {
        type: "string",
        description: "OS product name, e.g. \"Ubuntu\", \"Windows Server\".",
      },
      "os_version": {
        type: "string",
        description: "OS version string as reported.",
      },
      "architecture": {
        type: "string",
        description: "CPU architecture, e.g. amd64, arm64.",
      },
      "cpu_count": {
        type: "integer",
        description: "Logical CPU count.",
      },
      "memory_mb": {
        type: "integer",
        description: "Installed memory in mebibytes.",
      },
      "server_role": {
        type: "string",
        description: "Primary role the server plays, e.g. web, database, file, domain controller. Free text; the relationship graph is authoritative.",
      },
    },
  },
  "workstation": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "vendor": {
        type: "string",
        description: "Manufacturer or brand as reported by the device.",
      },
      "model": {
        type: "string",
        description: "Manufacturer model designation.",
      },
      "asset_tag": {
        type: "string",
        description: "Organisation's own inventory tag, if one is affixed.",
      },
      "operating_system": {
        type: "string",
        description: "OS product name, e.g. \"Ubuntu\", \"Windows Server\".",
      },
      "os_version": {
        type: "string",
        description: "OS version string as reported.",
      },
      "architecture": {
        type: "string",
        description: "CPU architecture, e.g. amd64, arm64.",
      },
      "cpu_count": {
        type: "integer",
        description: "Logical CPU count.",
      },
      "memory_mb": {
        type: "integer",
        description: "Installed memory in mebibytes.",
      },
      "assigned_user": {
        type: "string",
        description: "Primary user, by email or directory name.",
      },
    },
  },
  "laptop": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "vendor": {
        type: "string",
        description: "Manufacturer or brand as reported by the device.",
      },
      "model": {
        type: "string",
        description: "Manufacturer model designation.",
      },
      "asset_tag": {
        type: "string",
        description: "Organisation's own inventory tag, if one is affixed.",
      },
      "operating_system": {
        type: "string",
        description: "OS product name, e.g. \"Ubuntu\", \"Windows Server\".",
      },
      "os_version": {
        type: "string",
        description: "OS version string as reported.",
      },
      "architecture": {
        type: "string",
        description: "CPU architecture, e.g. amd64, arm64.",
      },
      "cpu_count": {
        type: "integer",
        description: "Logical CPU count.",
      },
      "memory_mb": {
        type: "integer",
        description: "Installed memory in mebibytes.",
      },
      "assigned_user": {
        type: "string",
        description: "Primary user, by email or directory name.",
      },
    },
  },
  "mobile": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "vendor": {
        type: "string",
        description: "Manufacturer or brand as reported by the device.",
      },
      "model": {
        type: "string",
        description: "Manufacturer model designation.",
      },
      "asset_tag": {
        type: "string",
        description: "Organisation's own inventory tag, if one is affixed.",
      },
      "operating_system": {
        type: "string",
        description: "OS product name, e.g. \"Ubuntu\", \"Windows Server\".",
      },
      "os_version": {
        type: "string",
        description: "OS version string as reported.",
      },
      "architecture": {
        type: "string",
        description: "CPU architecture, e.g. amd64, arm64.",
      },
      "cpu_count": {
        type: "integer",
        description: "Logical CPU count.",
      },
      "memory_mb": {
        type: "integer",
        description: "Installed memory in mebibytes.",
      },
      "platform": {
        type: "string",
        description: "Mobile platform family.",
        enum: ["ios", "android", "other"],
      },
      "mdm_enrolled": {
        type: "boolean",
        description: "Whether the device is enrolled in mobile device management.",
      },
    },
  },
  "network_device": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "vendor": {
        type: "string",
        description: "Manufacturer or brand as reported by the device.",
      },
      "model": {
        type: "string",
        description: "Manufacturer model designation.",
      },
      "asset_tag": {
        type: "string",
        description: "Organisation's own inventory tag, if one is affixed.",
      },
      "firmware_version": {
        type: "string",
        description: "Running firmware or network-OS version.",
      },
    },
  },
  "switch": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "vendor": {
        type: "string",
        description: "Manufacturer or brand as reported by the device.",
      },
      "model": {
        type: "string",
        description: "Manufacturer model designation.",
      },
      "asset_tag": {
        type: "string",
        description: "Organisation's own inventory tag, if one is affixed.",
      },
      "firmware_version": {
        type: "string",
        description: "Running firmware or network-OS version.",
      },
      "switch_layer": {
        type: "integer",
        description: "2 or 3, per the forwarding the switch performs.",
      },
      "port_count": {
        type: "integer",
        description: "Physical port count.",
      },
    },
  },
  "router": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "vendor": {
        type: "string",
        description: "Manufacturer or brand as reported by the device.",
      },
      "model": {
        type: "string",
        description: "Manufacturer model designation.",
      },
      "asset_tag": {
        type: "string",
        description: "Organisation's own inventory tag, if one is affixed.",
      },
      "firmware_version": {
        type: "string",
        description: "Running firmware or network-OS version.",
      },
      "routing_protocols": {
        type: "array",
        description: "Routing protocols observed in the configuration.",
        items: { type: "string" },
      },
    },
  },
  "firewall": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "vendor": {
        type: "string",
        description: "Manufacturer or brand as reported by the device.",
      },
      "model": {
        type: "string",
        description: "Manufacturer model designation.",
      },
      "asset_tag": {
        type: "string",
        description: "Organisation's own inventory tag, if one is affixed.",
      },
      "firmware_version": {
        type: "string",
        description: "Running firmware or network-OS version.",
      },
      "ha_role": {
        type: "string",
        description: "Role in a high-availability pair.",
        enum: ["standalone", "active", "passive", "unknown"],
      },
    },
  },
  "load_balancer": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "vendor": {
        type: "string",
        description: "Manufacturer or brand as reported by the device.",
      },
      "model": {
        type: "string",
        description: "Manufacturer model designation.",
      },
      "asset_tag": {
        type: "string",
        description: "Organisation's own inventory tag, if one is affixed.",
      },
      "firmware_version": {
        type: "string",
        description: "Running firmware or network-OS version.",
      },
      "virtual_server_count": {
        type: "integer",
        description: "Number of configured virtual servers or listeners.",
      },
      "ssl_offload_enabled": {
        type: "boolean",
        description: "Whether the device terminates TLS on behalf of backends.",
      },
    },
  },
  "wireless_controller": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "vendor": {
        type: "string",
        description: "Manufacturer or brand as reported by the device.",
      },
      "model": {
        type: "string",
        description: "Manufacturer model designation.",
      },
      "asset_tag": {
        type: "string",
        description: "Organisation's own inventory tag, if one is affixed.",
      },
      "firmware_version": {
        type: "string",
        description: "Running firmware or network-OS version.",
      },
      "managed_ap_count": {
        type: "integer",
        description: "Access points the controller reports managing.",
      },
    },
  },
  "access_point": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "vendor": {
        type: "string",
        description: "Manufacturer or brand as reported by the device.",
      },
      "model": {
        type: "string",
        description: "Manufacturer model designation.",
      },
      "asset_tag": {
        type: "string",
        description: "Organisation's own inventory tag, if one is affixed.",
      },
      "firmware_version": {
        type: "string",
        description: "Running firmware or network-OS version.",
      },
      "radio_bands": {
        type: "array",
        description: "Radio bands in service, e.g. 2.4GHz, 5GHz, 6GHz.",
        items: { type: "string" },
      },
      "controller_managed": {
        type: "boolean",
        description: "Whether a wireless controller manages this AP.",
      },
    },
  },
  "vpn_gateway": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "vendor": {
        type: "string",
        description: "Manufacturer or brand as reported by the device.",
      },
      "model": {
        type: "string",
        description: "Manufacturer model designation.",
      },
      "asset_tag": {
        type: "string",
        description: "Organisation's own inventory tag, if one is affixed.",
      },
      "firmware_version": {
        type: "string",
        description: "Running firmware or network-OS version.",
      },
      "vpn_types": {
        type: "array",
        description: "Tunnel families terminated, e.g. ipsec, ssl, wireguard.",
        items: { type: "string" },
      },
    },
  },
  "storage_device": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "vendor": {
        type: "string",
        description: "Manufacturer or brand as reported by the device.",
      },
      "model": {
        type: "string",
        description: "Manufacturer model designation.",
      },
      "asset_tag": {
        type: "string",
        description: "Organisation's own inventory tag, if one is affixed.",
      },
      "firmware_version": {
        type: "string",
        description: "Running firmware version.",
      },
      "capacity_gb": {
        type: "integer",
        description: "Raw capacity in gigabytes.",
      },
      "storage_protocols": {
        type: "array",
        description: "Protocols served, e.g. iscsi, nfs, smb, fc.",
        items: { type: "string" },
      },
    },
  },
  "printer": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "vendor": {
        type: "string",
        description: "Manufacturer or brand as reported by the device.",
      },
      "model": {
        type: "string",
        description: "Manufacturer model designation.",
      },
      "asset_tag": {
        type: "string",
        description: "Organisation's own inventory tag, if one is affixed.",
      },
      "firmware_version": {
        type: "string",
        description: "Running firmware version.",
      },
      "print_protocols": {
        type: "array",
        description: "Print protocols offered, e.g. ipp, lpd, raw9100.",
        items: { type: "string" },
      },
    },
  },
  "ot_device": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "vendor": {
        type: "string",
        description: "Manufacturer or brand as reported by the device.",
      },
      "model": {
        type: "string",
        description: "Manufacturer model designation.",
      },
      "asset_tag": {
        type: "string",
        description: "Organisation's own inventory tag, if one is affixed.",
      },
      "firmware_version": {
        type: "string",
        description: "Running firmware version.",
      },
      "purdue_level": {
        type: "integer",
        description: "Purdue model level 0-5 the device sits at.",
      },
      "industrial_protocols": {
        type: "array",
        description: "Industrial protocols spoken, e.g. modbus, dnp3, ethernet-ip.",
        items: { type: "string" },
      },
    },
  },
  "plc": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "vendor": {
        type: "string",
        description: "Manufacturer or brand as reported by the device.",
      },
      "model": {
        type: "string",
        description: "Manufacturer model designation.",
      },
      "asset_tag": {
        type: "string",
        description: "Organisation's own inventory tag, if one is affixed.",
      },
      "firmware_version": {
        type: "string",
        description: "Running firmware version.",
      },
      "purdue_level": {
        type: "integer",
        description: "Purdue model level 0-5 the device sits at.",
      },
      "industrial_protocols": {
        type: "array",
        description: "Industrial protocols spoken, e.g. modbus, dnp3, ethernet-ip.",
        items: { type: "string" },
      },
    },
  },
  "rtu": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "vendor": {
        type: "string",
        description: "Manufacturer or brand as reported by the device.",
      },
      "model": {
        type: "string",
        description: "Manufacturer model designation.",
      },
      "asset_tag": {
        type: "string",
        description: "Organisation's own inventory tag, if one is affixed.",
      },
      "firmware_version": {
        type: "string",
        description: "Running firmware version.",
      },
      "purdue_level": {
        type: "integer",
        description: "Purdue model level 0-5 the device sits at.",
      },
      "industrial_protocols": {
        type: "array",
        description: "Industrial protocols spoken, e.g. modbus, dnp3, ethernet-ip.",
        items: { type: "string" },
      },
      "telemetry_protocol": {
        type: "string",
        description: "Primary telemetry protocol, e.g. dnp3, iec-101.",
      },
    },
  },
  "hmi": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "vendor": {
        type: "string",
        description: "Manufacturer or brand as reported by the device.",
      },
      "model": {
        type: "string",
        description: "Manufacturer model designation.",
      },
      "asset_tag": {
        type: "string",
        description: "Organisation's own inventory tag, if one is affixed.",
      },
      "firmware_version": {
        type: "string",
        description: "Running firmware version.",
      },
      "purdue_level": {
        type: "integer",
        description: "Purdue model level 0-5 the device sits at.",
      },
      "industrial_protocols": {
        type: "array",
        description: "Industrial protocols spoken, e.g. modbus, dnp3, ethernet-ip.",
        items: { type: "string" },
      },
      "hmi_software": {
        type: "string",
        description: "HMI/SCADA software product running on the panel.",
      },
      "hmi_software_version": {
        type: "string",
        description: "Version of that software.",
      },
    },
  },
  "ied": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "vendor": {
        type: "string",
        description: "Manufacturer or brand as reported by the device.",
      },
      "model": {
        type: "string",
        description: "Manufacturer model designation.",
      },
      "asset_tag": {
        type: "string",
        description: "Organisation's own inventory tag, if one is affixed.",
      },
      "firmware_version": {
        type: "string",
        description: "Running firmware version.",
      },
      "purdue_level": {
        type: "integer",
        description: "Purdue model level 0-5 the device sits at.",
      },
      "industrial_protocols": {
        type: "array",
        description: "Industrial protocols spoken, e.g. modbus, dnp3, ethernet-ip.",
        items: { type: "string" },
      },
      "iec61850_edition": {
        type: "string",
        description: "IEC 61850 edition the device implements, if any.",
      },
    },
  },
  "iot_device": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "vendor": {
        type: "string",
        description: "Manufacturer or brand as reported by the device.",
      },
      "model": {
        type: "string",
        description: "Manufacturer model designation.",
      },
      "asset_tag": {
        type: "string",
        description: "Organisation's own inventory tag, if one is affixed.",
      },
      "firmware_version": {
        type: "string",
        description: "Running firmware version.",
      },
      "device_category": {
        type: "string",
        description: "What the thing is, e.g. camera, badge reader, thermostat.",
      },
    },
  },
  "bmc": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "vendor": {
        type: "string",
        description: "Manufacturer or brand as reported by the device.",
      },
      "model": {
        type: "string",
        description: "Manufacturer model designation.",
      },
      "asset_tag": {
        type: "string",
        description: "Organisation's own inventory tag, if one is affixed.",
      },
      "firmware_version": {
        type: "string",
        description: "Running controller firmware version.",
      },
      "bmc_protocol": {
        type: "string",
        description: "Management protocol the controller answers.",
        enum: ["ipmi", "redfish", "proprietary", "unknown"],
      },
    },
  },
  "virtual": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "cpu_count": {
        type: "integer",
        description: "Allocated virtual CPUs.",
      },
      "memory_mb": {
        type: "integer",
        description: "Allocated memory in mebibytes.",
      },
    },
  },
  "virtual_machine": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "cpu_count": {
        type: "integer",
        description: "Allocated virtual CPUs.",
      },
      "memory_mb": {
        type: "integer",
        description: "Allocated memory in mebibytes.",
      },
      "operating_system": {
        type: "string",
        description: "Guest OS product name.",
      },
      "os_version": {
        type: "string",
        description: "Guest OS version string.",
      },
      "guest_tools_version": {
        type: "string",
        description: "Hypervisor guest-tools version, if installed.",
      },
    },
  },
  "container": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "cpu_count": {
        type: "integer",
        description: "Allocated virtual CPUs.",
      },
      "memory_mb": {
        type: "integer",
        description: "Allocated memory in mebibytes.",
      },
      "image": {
        type: "string",
        description: "Image reference the container runs.",
      },
      "image_digest": {
        type: "string",
        description: "Immutable digest of that image.",
      },
      "runtime": {
        type: "string",
        description: "Container runtime, e.g. containerd, docker, cri-o.",
      },
      "namespace": {
        type: "string",
        description: "Orchestrator namespace the container runs in.",
      },
    },
  },
  "cluster": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "cpu_count": {
        type: "integer",
        description: "Allocated virtual CPUs.",
      },
      "memory_mb": {
        type: "integer",
        description: "Allocated memory in mebibytes.",
      },
      "orchestrator": {
        type: "string",
        description: "Cluster technology, e.g. kubernetes, vsphere, nomad.",
      },
      "orchestrator_version": {
        type: "string",
        description: "Version of that technology.",
      },
      "node_count": {
        type: "integer",
        description: "Member nodes reported by the cluster.",
      },
    },
  },
  "hypervisor": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "cpu_count": {
        type: "integer",
        description: "Allocated virtual CPUs.",
      },
      "memory_mb": {
        type: "integer",
        description: "Allocated memory in mebibytes.",
      },
      "product": {
        type: "string",
        description: "Hypervisor product, e.g. ESXi, Hyper-V, KVM, Proxmox.",
      },
      "product_version": {
        type: "string",
        description: "Version of that product.",
      },
    },
  },
  "cloud_resource": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "provider": {
        type: "string",
        description: "Cloud provider.",
        enum: ["aws", "azure", "gcp", "oci", "other"],
      },
      "account_id": {
        type: "string",
        description: "Account, subscription or project the resource belongs to.",
      },
      "region": {
        type: "string",
        description: "Provider region.",
      },
    },
  },
  "compute_instance": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "provider": {
        type: "string",
        description: "Cloud provider.",
        enum: ["aws", "azure", "gcp", "oci", "other"],
      },
      "account_id": {
        type: "string",
        description: "Account, subscription or project the resource belongs to.",
      },
      "region": {
        type: "string",
        description: "Provider region.",
      },
      "instance_type": {
        type: "string",
        description: "Provider instance size, e.g. m6i.large.",
      },
      "image_id": {
        type: "string",
        description: "Machine image the instance booted from.",
      },
      "operating_system": {
        type: "string",
        description: "Guest OS product name.",
      },
      "os_version": {
        type: "string",
        description: "Guest OS version string.",
      },
    },
  },
  "managed_database": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "provider": {
        type: "string",
        description: "Cloud provider.",
        enum: ["aws", "azure", "gcp", "oci", "other"],
      },
      "account_id": {
        type: "string",
        description: "Account, subscription or project the resource belongs to.",
      },
      "region": {
        type: "string",
        description: "Provider region.",
      },
      "engine": {
        type: "string",
        description: "Database engine, e.g. postgres, mysql, sqlserver.",
      },
      "engine_version": {
        type: "string",
        description: "Engine version.",
      },
    },
  },
  "object_storage": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "provider": {
        type: "string",
        description: "Cloud provider.",
        enum: ["aws", "azure", "gcp", "oci", "other"],
      },
      "account_id": {
        type: "string",
        description: "Account, subscription or project the resource belongs to.",
      },
      "region": {
        type: "string",
        description: "Provider region.",
      },
      "encryption_algorithm": {
        type: "string",
        description: "Algorithm the provider reports for default encryption.",
      },
      "public_access_blocked": {
        type: "boolean",
        description: "Whether public access is blocked at the resource level.",
      },
    },
  },
  "key_store": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "provider": {
        type: "string",
        description: "Cloud provider.",
        enum: ["aws", "azure", "gcp", "oci", "other"],
      },
      "account_id": {
        type: "string",
        description: "Account, subscription or project the resource belongs to.",
      },
      "region": {
        type: "string",
        description: "Provider region.",
      },
      "key_store_kind": {
        type: "string",
        description: "What kind of store this is.",
        enum: ["kms", "key_vault", "hsm", "secrets_manager", "other"],
      },
      "certification_level": {
        type: "string",
        description: "Certification claimed, e.g. \"FIPS 140-3 Level 3\".",
      },
      "key_count": {
        type: "integer",
        description: "Number of keys the store reports holding.",
      },
    },
  },
  "cloud_load_balancer": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "provider": {
        type: "string",
        description: "Cloud provider.",
        enum: ["aws", "azure", "gcp", "oci", "other"],
      },
      "account_id": {
        type: "string",
        description: "Account, subscription or project the resource belongs to.",
      },
      "region": {
        type: "string",
        description: "Provider region.",
      },
      "scheme": {
        type: "string",
        description: "Whether the balancer is reachable from the internet.",
        enum: ["internet_facing", "internal", "unknown"],
      },
      "listener_count": {
        type: "integer",
        description: "Configured listeners.",
      },
      "tls_policy": {
        type: "string",
        description: "Provider TLS security policy applied to listeners.",
      },
    },
  },
  "api_gateway": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "provider": {
        type: "string",
        description: "Cloud provider.",
        enum: ["aws", "azure", "gcp", "oci", "other"],
      },
      "account_id": {
        type: "string",
        description: "Account, subscription or project the resource belongs to.",
      },
      "region": {
        type: "string",
        description: "Provider region.",
      },
      "endpoint_type": {
        type: "string",
        description: "Deployment type of the gateway endpoint.",
        enum: ["regional", "edge", "private", "unknown"],
      },
    },
  },
  "cdn_distribution": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "provider": {
        type: "string",
        description: "Cloud provider.",
        enum: ["aws", "azure", "gcp", "oci", "other"],
      },
      "account_id": {
        type: "string",
        description: "Account, subscription or project the resource belongs to.",
      },
      "region": {
        type: "string",
        description: "Provider region.",
      },
      "origin_count": {
        type: "integer",
        description: "Configured origins.",
      },
    },
  },
  "serverless_function": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "provider": {
        type: "string",
        description: "Cloud provider.",
        enum: ["aws", "azure", "gcp", "oci", "other"],
      },
      "account_id": {
        type: "string",
        description: "Account, subscription or project the resource belongs to.",
      },
      "region": {
        type: "string",
        description: "Provider region.",
      },
      "runtime": {
        type: "string",
        description: "Execution runtime, e.g. nodejs, python, go.",
      },
      "runtime_version": {
        type: "string",
        description: "Runtime version.",
      },
      "memory_mb": {
        type: "integer",
        description: "Configured memory in mebibytes.",
      },
    },
  },
  "virtual_network": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "provider": {
        type: "string",
        description: "Cloud provider.",
        enum: ["aws", "azure", "gcp", "oci", "other"],
      },
      "account_id": {
        type: "string",
        description: "Account, subscription or project the resource belongs to.",
      },
      "region": {
        type: "string",
        description: "Provider region.",
      },
      "cidr_blocks": {
        type: "array",
        description: "CIDR blocks assigned to the network.",
        items: { type: "string" },
      },
    },
  },
  "subnet": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "provider": {
        type: "string",
        description: "Cloud provider.",
        enum: ["aws", "azure", "gcp", "oci", "other"],
      },
      "account_id": {
        type: "string",
        description: "Account, subscription or project the resource belongs to.",
      },
      "region": {
        type: "string",
        description: "Provider region.",
      },
      "cidr_block": {
        type: "string",
        description: "CIDR block of the subnet.",
      },
      "availability_zone": {
        type: "string",
        description: "Provider availability zone.",
      },
      "is_public": {
        type: "boolean",
        description: "Whether the subnet routes to an internet gateway.",
      },
    },
  },
  "application": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "product": {
        type: "string",
        description: "Software product name.",
      },
      "version": {
        type: "string",
        description: "Product version.",
      },
      "vendor": {
        type: "string",
        description: "Publisher of the software.",
      },
    },
  },
  "web_application": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "product": {
        type: "string",
        description: "Software product name.",
      },
      "version": {
        type: "string",
        description: "Product version.",
      },
      "vendor": {
        type: "string",
        description: "Publisher of the software.",
      },
      "base_url": {
        type: "string",
        description: "Root URL the application is served from.",
      },
      "framework": {
        type: "string",
        description: "Application framework, if identified.",
      },
      "server_software": {
        type: "string",
        description: "Server banner or identified server software.",
      },
    },
  },
  "database_instance": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "product": {
        type: "string",
        description: "Software product name.",
      },
      "version": {
        type: "string",
        description: "Product version.",
      },
      "vendor": {
        type: "string",
        description: "Publisher of the software.",
      },
      "engine": {
        type: "string",
        description: "Database engine, e.g. postgres, mysql, oracle.",
      },
      "engine_version": {
        type: "string",
        description: "Engine version.",
      },
      "instance_name": {
        type: "string",
        description: "Instance or SID name that distinguishes it on its host.",
      },
      "tls_required": {
        type: "boolean",
        description: "Whether the engine requires TLS for client connections.",
      },
    },
  },
  "service_daemon": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "product": {
        type: "string",
        description: "Software product name.",
      },
      "version": {
        type: "string",
        description: "Product version.",
      },
      "vendor": {
        type: "string",
        description: "Publisher of the software.",
      },
      "process_name": {
        type: "string",
        description: "Executable or unit name.",
      },
      "service_account": {
        type: "string",
        description: "Account the process runs as.",
      },
    },
  },
  "middleware": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "product": {
        type: "string",
        description: "Software product name.",
      },
      "version": {
        type: "string",
        description: "Product version.",
      },
      "vendor": {
        type: "string",
        description: "Publisher of the software.",
      },
      "middleware_kind": {
        type: "string",
        description: "What role the middleware plays.",
        enum: ["message_broker", "application_server", "api_proxy", "cache", "other"],
      },
    },
  },
  "service": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "criticality": {
        type: "string",
        description: "How badly the organisation is hurt when this is down.",
        enum: ["critical", "high", "medium", "low"],
      },
    },
  },
  "business_service": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "criticality": {
        type: "string",
        description: "How badly the organisation is hurt when this is down.",
        enum: ["critical", "high", "medium", "low"],
      },
      "business_capability": {
        type: "string",
        description: "Capability the service delivers, e.g. \"online banking\".",
      },
    },
  },
  "technical_service": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "criticality": {
        type: "string",
        description: "How badly the organisation is hurt when this is down.",
        enum: ["critical", "high", "medium", "low"],
      },
      "technology_domain": {
        type: "string",
        description: "Domain the service belongs to, e.g. messaging, identity.",
      },
    },
  },
  "external": {
    type: 'object',
    additionalProperties: false,
    properties: {
      "organization": {
        type: "string",
        description: "Organisation the endpoint is attributed to, if known.",
      },
      "relationship": {
        type: "string",
        description: "How the tenant relates to that organisation.",
        enum: ["vendor", "partner", "customer", "unknown"],
      },
    },
  },
  "unknown_host": { type: 'object', additionalProperties: false, properties: {} },
};

/** A class's effective attribute schema, or undefined for a key the platform
 *  taxonomy does not define (a tenant leaf subclass is runtime data). */
export function attributeSchema(key: string): AssetAttributeSchema | undefined {
  return Object.prototype.hasOwnProperty.call(ATTRIBUTE_SCHEMAS, key)
    ? ATTRIBUTE_SCHEMAS[key as AssetClassKey]
    : undefined;
}
