// Code generated by scripts/generate-asset-classes.mjs from
// standards/asset-classes.yaml. DO NOT EDIT — edit the YAML and run
// `make generate`.
//
// The asset class taxonomy for the TypeScript side — facets, the class picker,
// and the per-class column/form registry import it as
// `@vistasecurity/primitives/assets`. The Go mirror is shared/assetclass; the
// DB mirror is the asset_classes table. All three come from the same YAML.

export const ASSET_IDENTIFIER_KINDS = ["declaration_id", "agent_id", "cloud_resource_id", "serial_number", "cmdb_sys_id", "ssh_host_key_fingerprint", "mac_address", "fqdn", "hostname", "ip_address", "name"] as const;

/** Every platform class key. Tenant leaf subclasses are runtime data and are
 *  deliberately NOT in this union — they are typed as `string`. */
export type AssetClassKey =
  | "hardware"
  | "computer"
  | "server"
  | "workstation"
  | "laptop"
  | "mobile"
  | "network_device"
  | "switch"
  | "router"
  | "firewall"
  | "load_balancer"
  | "wireless_controller"
  | "access_point"
  | "vpn_gateway"
  | "storage_device"
  | "printer"
  | "ot_device"
  | "plc"
  | "rtu"
  | "hmi"
  | "ied"
  | "iot_device"
  | "bmc"
  | "virtual"
  | "virtual_machine"
  | "container"
  | "cluster"
  | "hypervisor"
  | "cloud_resource"
  | "compute_instance"
  | "managed_database"
  | "object_storage"
  | "key_store"
  | "cloud_load_balancer"
  | "api_gateway"
  | "cdn_distribution"
  | "serverless_function"
  | "virtual_network"
  | "subnet"
  | "application"
  | "web_application"
  | "database_instance"
  | "service_daemon"
  | "middleware"
  | "service"
  | "business_service"
  | "technical_service"
  | "external"
  | "unknown_host";

/** A CycloneDX component type, or "service" for classes emitted into the
 *  CycloneDX `services` array rather than `components`. */
export type AssetClassCycloneDXType = "application" | "container" | "data" | "device" | "platform" | "service";

export interface AssetClass {
  key: AssetClassKey;
  /** Parent class key; null for a top-level class. */
  parent: AssetClassKey | null;
  /** Materialised dot-separated ancestor chain, e.g. "hardware.computer.server". */
  path: string;
  label: string;
  description: string;
  /** lucide-react export name. */
  icon: string;
  /** Default ServiceNow class for the CMDB sync; null means no confident
   *  default (resolve to the nearest mapped ancestor). */
  cmdbCiType: string | null;
  cyclonedxType: AssetClassCycloneDXType;
  /** Ordered identifier kinds the identification engine tries, best first.
   *  Empty means dependent identity (ADR-0002 D3). */
  identifierPrecedence: string[];
  /** The public.asset_type enum value this class maps onto. Reference only. */
  legacyAssetType: string;
}

export const ASSET_CLASSES: Record<AssetClassKey, AssetClass> = {
  "hardware": {
    key: "hardware",
    parent: null,
    path: "hardware",
    label: "Hardware",
    description: "A physical thing with a chassis. Use this class directly when a device is known to be physical but nothing narrows it further.",
    icon: "CircuitBoard",
    cmdbCiType: "cmdb_ci_hardware",
    cyclonedxType: "device",
    identifierPrecedence: ["serial_number", "cmdb_sys_id", "mac_address", "fqdn", "hostname", "ip_address"],
    legacyAssetType: "appliance",
  },
  "computer": {
    key: "computer",
    parent: "hardware",
    path: "hardware.computer",
    label: "Computer",
    description: "A general-purpose machine running an operating system.",
    icon: "Computer",
    cmdbCiType: "cmdb_ci_computer",
    cyclonedxType: "device",
    identifierPrecedence: ["agent_id", "serial_number", "cmdb_sys_id", "ssh_host_key_fingerprint", "mac_address", "fqdn", "hostname", "ip_address"],
    legacyAssetType: "endpoint",
  },
  "server": {
    key: "server",
    parent: "computer",
    path: "hardware.computer.server",
    label: "Server",
    description: "A computer providing services to other machines.",
    icon: "Server",
    cmdbCiType: "cmdb_ci_server",
    cyclonedxType: "device",
    identifierPrecedence: ["agent_id", "serial_number", "cmdb_sys_id", "ssh_host_key_fingerprint", "mac_address", "fqdn", "hostname", "ip_address"],
    legacyAssetType: "server",
  },
  "workstation": {
    key: "workstation",
    parent: "computer",
    path: "hardware.computer.workstation",
    label: "Workstation",
    description: "A desktop computer used by a person.",
    icon: "Monitor",
    cmdbCiType: "cmdb_ci_pc_hardware",
    cyclonedxType: "device",
    identifierPrecedence: ["agent_id", "serial_number", "cmdb_sys_id", "mac_address", "fqdn", "hostname"],
    legacyAssetType: "endpoint",
  },
  "laptop": {
    key: "laptop",
    parent: "computer",
    path: "hardware.computer.laptop",
    label: "Laptop",
    description: "A portable computer used by a person.",
    icon: "Laptop",
    cmdbCiType: "cmdb_ci_pc_hardware",
    cyclonedxType: "device",
    identifierPrecedence: ["agent_id", "serial_number", "cmdb_sys_id", "mac_address", "hostname"],
    legacyAssetType: "endpoint",
  },
  "mobile": {
    key: "mobile",
    parent: "computer",
    path: "hardware.computer.mobile",
    label: "Mobile device",
    description: "A phone or tablet.",
    icon: "Smartphone",
    cmdbCiType: null,
    cyclonedxType: "device",
    identifierPrecedence: ["agent_id", "serial_number", "cmdb_sys_id", "mac_address", "hostname"],
    legacyAssetType: "endpoint",
  },
  "network_device": {
    key: "network_device",
    parent: "hardware",
    path: "hardware.network_device",
    label: "Network device",
    description: "Equipment whose job is moving or filtering traffic.",
    icon: "Network",
    cmdbCiType: "cmdb_ci_netgear",
    cyclonedxType: "device",
    identifierPrecedence: ["serial_number", "cmdb_sys_id", "ssh_host_key_fingerprint", "mac_address", "fqdn", "hostname", "ip_address"],
    legacyAssetType: "appliance",
  },
  "switch": {
    key: "switch",
    parent: "network_device",
    path: "hardware.network_device.switch",
    label: "Switch",
    description: "A layer-2 (or layer-3) forwarding device.",
    icon: "EthernetPort",
    cmdbCiType: "cmdb_ci_ip_switch",
    cyclonedxType: "device",
    identifierPrecedence: ["serial_number", "cmdb_sys_id", "ssh_host_key_fingerprint", "mac_address", "fqdn", "hostname", "ip_address"],
    legacyAssetType: "appliance",
  },
  "router": {
    key: "router",
    parent: "network_device",
    path: "hardware.network_device.router",
    label: "Router",
    description: "A device routing between networks.",
    icon: "Router",
    cmdbCiType: "cmdb_ci_ip_router",
    cyclonedxType: "device",
    identifierPrecedence: ["serial_number", "cmdb_sys_id", "ssh_host_key_fingerprint", "mac_address", "fqdn", "hostname", "ip_address"],
    legacyAssetType: "appliance",
  },
  "firewall": {
    key: "firewall",
    parent: "network_device",
    path: "hardware.network_device.firewall",
    label: "Firewall",
    description: "A policy-enforcing filter between network zones.",
    icon: "Shield",
    cmdbCiType: "cmdb_ci_ip_firewall",
    cyclonedxType: "device",
    identifierPrecedence: ["serial_number", "cmdb_sys_id", "ssh_host_key_fingerprint", "mac_address", "fqdn", "hostname", "ip_address"],
    legacyAssetType: "appliance",
  },
  "load_balancer": {
    key: "load_balancer",
    parent: "network_device",
    path: "hardware.network_device.load_balancer",
    label: "Load balancer",
    description: "A device distributing connections across backends. Often the tenant's largest concentration of TLS termination.",
    icon: "Split",
    cmdbCiType: "cmdb_ci_lb",
    cyclonedxType: "device",
    identifierPrecedence: ["serial_number", "cmdb_sys_id", "ssh_host_key_fingerprint", "mac_address", "fqdn", "hostname", "ip_address"],
    legacyAssetType: "appliance",
  },
  "wireless_controller": {
    key: "wireless_controller",
    parent: "network_device",
    path: "hardware.network_device.wireless_controller",
    label: "Wireless controller",
    description: "A controller managing a fleet of access points.",
    icon: "RadioTower",
    cmdbCiType: null,
    cyclonedxType: "device",
    identifierPrecedence: ["serial_number", "cmdb_sys_id", "ssh_host_key_fingerprint", "mac_address", "fqdn", "hostname", "ip_address"],
    legacyAssetType: "appliance",
  },
  "access_point": {
    key: "access_point",
    parent: "network_device",
    path: "hardware.network_device.access_point",
    label: "Access point",
    description: "A wireless access point.",
    icon: "Wifi",
    cmdbCiType: "cmdb_ci_wap_network",
    cyclonedxType: "device",
    identifierPrecedence: ["serial_number", "cmdb_sys_id", "mac_address", "fqdn", "hostname", "ip_address"],
    legacyAssetType: "appliance",
  },
  "vpn_gateway": {
    key: "vpn_gateway",
    parent: "network_device",
    path: "hardware.network_device.vpn_gateway",
    label: "VPN gateway",
    description: "A device terminating remote-access or site-to-site tunnels.",
    icon: "ShieldCheck",
    cmdbCiType: null,
    cyclonedxType: "device",
    identifierPrecedence: ["serial_number", "cmdb_sys_id", "ssh_host_key_fingerprint", "mac_address", "fqdn", "hostname", "ip_address"],
    legacyAssetType: "appliance",
  },
  "storage_device": {
    key: "storage_device",
    parent: "hardware",
    path: "hardware.storage_device",
    label: "Storage device",
    description: "A storage array, NAS or SAN appliance.",
    icon: "HardDrive",
    cmdbCiType: "cmdb_ci_storage_device",
    cyclonedxType: "device",
    identifierPrecedence: ["serial_number", "cmdb_sys_id", "mac_address", "fqdn", "hostname", "ip_address"],
    legacyAssetType: "appliance",
  },
  "printer": {
    key: "printer",
    parent: "hardware",
    path: "hardware.printer",
    label: "Printer",
    description: "A printer or multifunction device.",
    icon: "Printer",
    cmdbCiType: "cmdb_ci_printer",
    cyclonedxType: "device",
    identifierPrecedence: ["serial_number", "cmdb_sys_id", "mac_address", "fqdn", "hostname", "ip_address"],
    legacyAssetType: "appliance",
  },
  "ot_device": {
    key: "ot_device",
    parent: "hardware",
    path: "hardware.ot_device",
    label: "OT device",
    description: "Operational-technology equipment on a plant or substation network. Rarely carries an agent and often cannot be actively probed safely.",
    icon: "Factory",
    cmdbCiType: null,
    cyclonedxType: "device",
    identifierPrecedence: ["serial_number", "cmdb_sys_id", "mac_address", "hostname", "ip_address"],
    legacyAssetType: "appliance",
  },
  "plc": {
    key: "plc",
    parent: "ot_device",
    path: "hardware.ot_device.plc",
    label: "PLC",
    description: "A programmable logic controller.",
    icon: "Cpu",
    cmdbCiType: null,
    cyclonedxType: "device",
    identifierPrecedence: ["serial_number", "cmdb_sys_id", "mac_address", "hostname", "ip_address"],
    legacyAssetType: "appliance",
  },
  "rtu": {
    key: "rtu",
    parent: "ot_device",
    path: "hardware.ot_device.rtu",
    label: "RTU",
    description: "A remote terminal unit relaying field telemetry.",
    icon: "Radio",
    cmdbCiType: null,
    cyclonedxType: "device",
    identifierPrecedence: ["serial_number", "cmdb_sys_id", "mac_address", "hostname", "ip_address"],
    legacyAssetType: "appliance",
  },
  "hmi": {
    key: "hmi",
    parent: "ot_device",
    path: "hardware.ot_device.hmi",
    label: "HMI",
    description: "A human-machine interface panel or station.",
    icon: "Gauge",
    cmdbCiType: null,
    cyclonedxType: "device",
    identifierPrecedence: ["serial_number", "cmdb_sys_id", "mac_address", "hostname", "ip_address"],
    legacyAssetType: "appliance",
  },
  "ied": {
    key: "ied",
    parent: "ot_device",
    path: "hardware.ot_device.ied",
    label: "IED",
    description: "An intelligent electronic device, typically in a substation.",
    icon: "Zap",
    cmdbCiType: null,
    cyclonedxType: "device",
    identifierPrecedence: ["serial_number", "cmdb_sys_id", "mac_address", "hostname", "ip_address"],
    legacyAssetType: "appliance",
  },
  "iot_device": {
    key: "iot_device",
    parent: "hardware",
    path: "hardware.iot_device",
    label: "IoT device",
    description: "A network-attached embedded device that is not OT — cameras, sensors, badge readers, building controls.",
    icon: "Cctv",
    cmdbCiType: null,
    cyclonedxType: "device",
    identifierPrecedence: ["serial_number", "cmdb_sys_id", "mac_address", "hostname", "ip_address"],
    legacyAssetType: "appliance",
  },
  "bmc": {
    key: "bmc",
    parent: "hardware",
    path: "hardware.bmc",
    label: "Management controller",
    description: "An out-of-band management controller (iDRAC, iLO, IPMI, Redfish). It has its own address, its own crypto, and its own lifecycle from the host it manages.",
    icon: "ServerCog",
    cmdbCiType: null,
    cyclonedxType: "device",
    identifierPrecedence: ["serial_number", "cmdb_sys_id", "mac_address", "fqdn", "hostname", "ip_address"],
    legacyAssetType: "appliance",
  },
  "virtual": {
    key: "virtual",
    parent: null,
    path: "virtual",
    label: "Virtual",
    description: "Something running on top of someone else's hardware, inside this tenant's own estate. Cloud-provider resources have their own top-level class.",
    icon: "Layers",
    cmdbCiType: null,
    cyclonedxType: "platform",
    identifierPrecedence: ["agent_id", "cloud_resource_id", "cmdb_sys_id", "ssh_host_key_fingerprint", "mac_address", "fqdn", "hostname", "ip_address"],
    legacyAssetType: "server",
  },
  "virtual_machine": {
    key: "virtual_machine",
    parent: "virtual",
    path: "virtual.virtual_machine",
    label: "Virtual machine",
    description: "A guest machine running on a hypervisor.",
    icon: "Box",
    cmdbCiType: "cmdb_ci_vm_instance",
    cyclonedxType: "platform",
    identifierPrecedence: ["agent_id", "cloud_resource_id", "cmdb_sys_id", "ssh_host_key_fingerprint", "mac_address", "fqdn", "hostname", "ip_address"],
    legacyAssetType: "server",
  },
  "container": {
    key: "container",
    parent: "virtual",
    path: "virtual.container",
    label: "Container",
    description: "A running container. Identified by its image and orchestration identity, never by serial number, MAC or address — all three are ephemeral for containers.",
    icon: "Container",
    cmdbCiType: null,
    cyclonedxType: "container",
    identifierPrecedence: ["agent_id", "cloud_resource_id", "cmdb_sys_id", "hostname"],
    legacyAssetType: "service",
  },
  "cluster": {
    key: "cluster",
    parent: "virtual",
    path: "virtual.cluster",
    label: "Cluster",
    description: "A group of nodes managed as one scheduling or failover unit.",
    icon: "Boxes",
    cmdbCiType: "cmdb_ci_cluster",
    cyclonedxType: "platform",
    identifierPrecedence: ["cloud_resource_id", "cmdb_sys_id", "fqdn", "hostname"],
    legacyAssetType: "service",
  },
  "hypervisor": {
    key: "hypervisor",
    parent: "virtual",
    path: "virtual.hypervisor",
    label: "Hypervisor",
    description: "A host running guest machines.",
    icon: "SquareStack",
    cmdbCiType: "cmdb_ci_server",
    cyclonedxType: "platform",
    identifierPrecedence: ["agent_id", "serial_number", "cmdb_sys_id", "ssh_host_key_fingerprint", "mac_address", "fqdn", "hostname", "ip_address"],
    legacyAssetType: "server",
  },
  "cloud_resource": {
    key: "cloud_resource",
    parent: null,
    path: "cloud_resource",
    label: "Cloud resource",
    description: "A resource managed by a cloud provider's control plane. Identified by its provider resource id; never by MAC address.",
    icon: "Cloud",
    cmdbCiType: null,
    cyclonedxType: "platform",
    identifierPrecedence: ["cloud_resource_id", "cmdb_sys_id", "fqdn"],
    legacyAssetType: "service",
  },
  "compute_instance": {
    key: "compute_instance",
    parent: "cloud_resource",
    path: "cloud_resource.compute_instance",
    label: "Compute instance",
    description: "A provider-managed virtual machine.",
    icon: "CloudCog",
    cmdbCiType: "cmdb_ci_vm_instance",
    cyclonedxType: "platform",
    identifierPrecedence: ["agent_id", "cloud_resource_id", "cmdb_sys_id", "ssh_host_key_fingerprint", "fqdn", "hostname", "ip_address"],
    legacyAssetType: "server",
  },
  "managed_database": {
    key: "managed_database",
    parent: "cloud_resource",
    path: "cloud_resource.managed_database",
    label: "Managed database",
    description: "A provider-operated database service instance.",
    icon: "Database",
    cmdbCiType: "cmdb_ci_db_instance",
    cyclonedxType: "application",
    identifierPrecedence: ["cloud_resource_id", "cmdb_sys_id", "fqdn"],
    legacyAssetType: "service",
  },
  "object_storage": {
    key: "object_storage",
    parent: "cloud_resource",
    path: "cloud_resource.object_storage",
    label: "Object storage",
    description: "A bucket or container of objects.",
    icon: "Archive",
    cmdbCiType: null,
    cyclonedxType: "data",
    identifierPrecedence: ["cloud_resource_id", "cmdb_sys_id", "fqdn"],
    legacyAssetType: "service",
  },
  "key_store": {
    key: "key_store",
    parent: "cloud_resource",
    path: "cloud_resource.key_store",
    label: "Key store",
    description: "A KMS, key vault, HSM or secrets manager. We inventory its posture — never the key material it holds.",
    icon: "KeyRound",
    cmdbCiType: null,
    cyclonedxType: "platform",
    identifierPrecedence: ["cloud_resource_id", "cmdb_sys_id", "fqdn"],
    legacyAssetType: "service",
  },
  "cloud_load_balancer": {
    key: "cloud_load_balancer",
    parent: "cloud_resource",
    path: "cloud_resource.cloud_load_balancer",
    label: "Cloud load balancer",
    description: "A provider-managed load balancer.",
    icon: "Scale",
    cmdbCiType: "cmdb_ci_lb",
    cyclonedxType: "platform",
    identifierPrecedence: ["cloud_resource_id", "cmdb_sys_id", "fqdn"],
    legacyAssetType: "appliance",
  },
  "api_gateway": {
    key: "api_gateway",
    parent: "cloud_resource",
    path: "cloud_resource.api_gateway",
    label: "API gateway",
    description: "A provider-managed API front door.",
    icon: "Webhook",
    cmdbCiType: null,
    cyclonedxType: "application",
    identifierPrecedence: ["cloud_resource_id", "cmdb_sys_id", "fqdn"],
    legacyAssetType: "service",
  },
  "cdn_distribution": {
    key: "cdn_distribution",
    parent: "cloud_resource",
    path: "cloud_resource.cdn_distribution",
    label: "CDN distribution",
    description: "A content delivery distribution fronting one or more origins.",
    icon: "Globe",
    cmdbCiType: null,
    cyclonedxType: "platform",
    identifierPrecedence: ["cloud_resource_id", "cmdb_sys_id", "fqdn"],
    legacyAssetType: "service",
  },
  "serverless_function": {
    key: "serverless_function",
    parent: "cloud_resource",
    path: "cloud_resource.serverless_function",
    label: "Serverless function",
    description: "A function executed on demand by the provider.",
    icon: "CloudLightning",
    cmdbCiType: null,
    cyclonedxType: "application",
    identifierPrecedence: ["cloud_resource_id", "cmdb_sys_id"],
    legacyAssetType: "service",
  },
  "virtual_network": {
    key: "virtual_network",
    parent: "cloud_resource",
    path: "cloud_resource.virtual_network",
    label: "Virtual network",
    description: "A provider-managed network (VPC, VNet). CycloneDX has no network component type, so it is emitted as `platform`.",
    icon: "Waypoints",
    cmdbCiType: "cmdb_ci_network",
    cyclonedxType: "platform",
    identifierPrecedence: ["cloud_resource_id", "cmdb_sys_id"],
    legacyAssetType: "service",
  },
  "subnet": {
    key: "subnet",
    parent: "cloud_resource",
    path: "cloud_resource.subnet",
    label: "Subnet",
    description: "A subdivision of a virtual network.",
    icon: "Share2",
    cmdbCiType: "cmdb_ci_ip_network",
    cyclonedxType: "platform",
    identifierPrecedence: ["cloud_resource_id", "cmdb_sys_id"],
    legacyAssetType: "service",
  },
  "application": {
    key: "application",
    parent: null,
    path: "application",
    label: "Application",
    description: "Software running on a host. Dependent identity: matched by its host asset plus product plus instance name, not by an address of its own.",
    icon: "AppWindow",
    cmdbCiType: "cmdb_ci_appl",
    cyclonedxType: "application",
    identifierPrecedence: ["cmdb_sys_id", "name"],
    legacyAssetType: "service",
  },
  "web_application": {
    key: "web_application",
    parent: "application",
    path: "application.web_application",
    label: "Web application",
    description: "An application served over HTTP(S).",
    icon: "Globe",
    cmdbCiType: null,
    cyclonedxType: "application",
    identifierPrecedence: ["cmdb_sys_id", "name"],
    legacyAssetType: "service",
  },
  "database_instance": {
    key: "database_instance",
    parent: "application",
    path: "application.database_instance",
    label: "Database instance",
    description: "A database engine running on a host the tenant operates.",
    icon: "Database",
    cmdbCiType: "cmdb_ci_db_instance",
    cyclonedxType: "application",
    identifierPrecedence: ["cmdb_sys_id", "name"],
    legacyAssetType: "service",
  },
  "service_daemon": {
    key: "service_daemon",
    parent: "application",
    path: "application.service_daemon",
    label: "Service daemon",
    description: "A long-running background process, usually with a listening port.",
    icon: "Cog",
    cmdbCiType: null,
    cyclonedxType: "application",
    identifierPrecedence: ["cmdb_sys_id", "name"],
    legacyAssetType: "service",
  },
  "middleware": {
    key: "middleware",
    parent: "application",
    path: "application.middleware",
    label: "Middleware",
    description: "Software other software talks through — message brokers, application servers, API proxies.",
    icon: "Blocks",
    cmdbCiType: null,
    cyclonedxType: "application",
    identifierPrecedence: ["cmdb_sys_id", "name"],
    legacyAssetType: "service",
  },
  "service": {
    key: "service",
    parent: null,
    path: "service",
    label: "Service",
    description: "A declared service, never discovered. Dependent identity: a service is identified by its name within the tenant and nothing else.",
    icon: "Workflow",
    cmdbCiType: "cmdb_ci_service",
    cyclonedxType: "service",
    identifierPrecedence: ["name"],
    legacyAssetType: "service",
  },
  "business_service": {
    key: "business_service",
    parent: "service",
    path: "service.business_service",
    label: "Business service",
    description: "A service the organisation offers to people, stated in their terms.",
    icon: "Briefcase",
    cmdbCiType: "cmdb_ci_service_business",
    cyclonedxType: "service",
    identifierPrecedence: ["name"],
    legacyAssetType: "service",
  },
  "technical_service": {
    key: "technical_service",
    parent: "service",
    path: "service.technical_service",
    label: "Technical service",
    description: "A service other services consume, stated in technical terms.",
    icon: "Settings",
    cmdbCiType: "cmdb_ci_service_technical",
    cyclonedxType: "service",
    identifierPrecedence: ["name"],
    legacyAssetType: "service",
  },
  "external": {
    key: "external",
    parent: null,
    path: "external",
    label: "External party",
    description: "An endpoint belonging to somebody else. Today's external-connections destination. Never actively probed (active-probing scope rule).",
    icon: "ExternalLink",
    cmdbCiType: null,
    cyclonedxType: "service",
    identifierPrecedence: ["fqdn", "ip_address"],
    legacyAssetType: "endpoint",
  },
  "unknown_host": {
    key: "unknown_host",
    parent: null,
    path: "unknown_host",
    label: "Unknown host",
    description: "A reachable address inside the tenant's own space that nothing has identified further, or a serial nothing has classified yet. A real asset with a real gap, not a placeholder — it is what makes \"how much don't we know\" answerable.",
    icon: "CircleQuestionMark",
    cmdbCiType: null,
    cyclonedxType: "device",
    identifierPrecedence: ["serial_number", "agent_id", "ssh_host_key_fingerprint", "mac_address", "fqdn", "hostname", "ip_address"],
    legacyAssetType: "endpoint",
  },
};

/** Every class key in registry order — a parent always precedes its children. */
export const ASSET_CLASS_KEYS = Object.keys(ASSET_CLASSES) as AssetClassKey[];

export interface AssetClassNode {
  key: AssetClassKey;
  children: AssetClassNode[];
}

/** The class hierarchy, for facet rails and the class picker. Look labels and
 *  icons up in ASSET_CLASSES rather than duplicating them here. */
export const CLASS_TREE: AssetClassNode[] = [
  {
    key: "hardware",
    children: [
      {
        key: "computer",
        children: [
          { key: "server", children: [] },
          { key: "workstation", children: [] },
          { key: "laptop", children: [] },
          { key: "mobile", children: [] },
        ],
      },
      {
        key: "network_device",
        children: [
          { key: "switch", children: [] },
          { key: "router", children: [] },
          { key: "firewall", children: [] },
          { key: "load_balancer", children: [] },
          { key: "wireless_controller", children: [] },
          { key: "access_point", children: [] },
          { key: "vpn_gateway", children: [] },
        ],
      },
      { key: "storage_device", children: [] },
      { key: "printer", children: [] },
      {
        key: "ot_device",
        children: [
          { key: "plc", children: [] },
          { key: "rtu", children: [] },
          { key: "hmi", children: [] },
          { key: "ied", children: [] },
        ],
      },
      { key: "iot_device", children: [] },
      { key: "bmc", children: [] },
    ],
  },
  {
    key: "virtual",
    children: [
      { key: "virtual_machine", children: [] },
      { key: "container", children: [] },
      { key: "cluster", children: [] },
      { key: "hypervisor", children: [] },
    ],
  },
  {
    key: "cloud_resource",
    children: [
      { key: "compute_instance", children: [] },
      { key: "managed_database", children: [] },
      { key: "object_storage", children: [] },
      { key: "key_store", children: [] },
      { key: "cloud_load_balancer", children: [] },
      { key: "api_gateway", children: [] },
      { key: "cdn_distribution", children: [] },
      { key: "serverless_function", children: [] },
      { key: "virtual_network", children: [] },
      { key: "subnet", children: [] },
    ],
  },
  {
    key: "application",
    children: [
      { key: "web_application", children: [] },
      { key: "database_instance", children: [] },
      { key: "service_daemon", children: [] },
      { key: "middleware", children: [] },
    ],
  },
  {
    key: "service",
    children: [
      { key: "business_service", children: [] },
      { key: "technical_service", children: [] },
    ],
  },
  { key: "external", children: [] },
  { key: "unknown_host", children: [] },
];
