-- The statement each measurement type compiles to, from
-- standards/measurement-types.yaml + measurement_shapes.go. GENERATED by
-- TestMeasurementSQLGolden; regenerate with -update-measurement-golden.
-- $1 is the tenant, $2 the optional single-subject filter; a shape's own
-- parameter (fact key, producer) is $3 and the compiled predicates follow.

-- ============================================================
-- asset_class  [shape: asset, subject: asset]
-- predicate args: [monitoring]
SELECT
			a.id AS subject_id,
			a.tenant_id AS tenant_id,
			a.updated_at AS measured_at,
			a.class_key AS col_0,
			a.hostname AS col_1,
			host(a.primary_address) AS col_2,
			a.display_name AS col_3
		FROM assets a
		WHERE a.tenant_id = $1
			AND a.deleted_at IS NULL
			AND ($2::uuid IS NULL OR a.id = $2)
			AND ((lower((a.asset_status)::text) = $3))
			AND (TRUE)
		ORDER BY a.updated_at DESC

-- ============================================================
-- asset_has_location  [shape: asset, subject: asset]
-- predicate args: [monitoring]
SELECT
			a.id AS subject_id,
			a.tenant_id AS tenant_id,
			a.updated_at AS measured_at,
			(COALESCE(NULLIF(btrim(a.site), ''), NULLIF(btrim(a.region), ''), NULLIF(btrim(a.zone), ''), a.location_id::text) IS NOT NULL) AS col_0,
			a.hostname AS col_1,
			host(a.primary_address) AS col_2,
			a.display_name AS col_3,
			a.class_key AS col_4,
			a.site AS col_5,
			a.region AS col_6
		FROM assets a
		WHERE a.tenant_id = $1
			AND a.deleted_at IS NULL
			AND ($2::uuid IS NULL OR a.id = $2)
			AND ((lower((a.asset_status)::text) = $3))
			AND (TRUE)
		ORDER BY a.updated_at DESC

-- ============================================================
-- asset_has_owner  [shape: asset, subject: asset]
-- predicate args: [monitoring]
SELECT
			a.id AS subject_id,
			a.tenant_id AS tenant_id,
			a.updated_at AS measured_at,
			(COALESCE(NULLIF(btrim(a.owner_email), ''), NULLIF(btrim(a.support_group), '')) IS NOT NULL) AS col_0,
			a.hostname AS col_1,
			host(a.primary_address) AS col_2,
			a.display_name AS col_3,
			a.class_key AS col_4,
			a.owner_email AS col_5,
			a.support_group AS col_6
		FROM assets a
		WHERE a.tenant_id = $1
			AND a.deleted_at IS NULL
			AND ($2::uuid IS NULL OR a.id = $2)
			AND ((lower((a.asset_status)::text) = $3))
			AND (TRUE)
		ORDER BY a.updated_at DESC

-- ============================================================
-- cert_algorithm  [shape: certificate, subject: certificate]
SELECT
			c.id AS subject_id,
			c.tenant_id AS tenant_id,
			c.updated_at AS measured_at,
			c.public_key_algorithm AS col_0,
			c.common_name AS col_1,
			c.public_key_size AS col_2
		FROM certificates c
		WHERE c.tenant_id = $1
			AND ($2::uuid IS NULL OR c.id = $2)
			AND c.is_ca_certificate = false
			AND ((c.public_key_algorithm IS NOT NULL))
			AND (TRUE)
		ORDER BY c.updated_at DESC

-- ============================================================
-- cert_expiration_days  [shape: certificate, subject: certificate]
SELECT
			c.id AS subject_id,
			c.tenant_id AS tenant_id,
			now() AS measured_at,
			EXTRACT(EPOCH FROM (c.not_after - NOW())) / 86400.0 AS col_0,
			c.common_name AS col_1,
			c.public_key_algorithm AS col_2,
			c.public_key_size AS col_3,
			c.not_after AS col_4
		FROM certificates c
		WHERE c.tenant_id = $1
			AND ($2::uuid IS NULL OR c.id = $2)
			AND c.is_ca_certificate = false
			AND ((c.not_after IS NOT NULL))
			AND (TRUE)
		ORDER BY c.not_after ASC

-- ============================================================
-- cert_pqc_status  [shape: certificate, subject: certificate]
SELECT
			c.id AS subject_id,
			c.tenant_id AS tenant_id,
			c.updated_at AS measured_at,
			c.public_key_algorithm AS col_0,
			c.common_name AS col_1
		FROM certificates c
		WHERE c.tenant_id = $1
			AND ($2::uuid IS NULL OR c.id = $2)
			AND c.is_ca_certificate = false
			AND (TRUE)
			AND (TRUE)
		ORDER BY c.updated_at DESC

-- ============================================================
-- cert_sig_pqc_status  [shape: certificate, subject: certificate]
SELECT
			c.id AS subject_id,
			c.tenant_id AS tenant_id,
			c.updated_at AS measured_at,
			c.signature_algorithm AS col_0,
			c.common_name AS col_1
		FROM certificates c
		WHERE c.tenant_id = $1
			AND ($2::uuid IS NULL OR c.id = $2)
			AND c.is_ca_certificate = false
			AND ((c.signature_algorithm IS NOT NULL))
			AND (TRUE)
		ORDER BY c.updated_at DESC

-- ============================================================
-- cert_validity_days  [shape: certificate, subject: certificate]
SELECT
			c.id AS subject_id,
			c.tenant_id AS tenant_id,
			c.updated_at AS measured_at,
			EXTRACT(EPOCH FROM (c.not_after - c.not_before)) / 86400.0 AS col_0,
			c.common_name AS col_1
		FROM certificates c
		WHERE c.tenant_id = $1
			AND ($2::uuid IS NULL OR c.id = $2)
			AND c.is_ca_certificate = false
			AND (((c.not_after IS NOT NULL) AND (c.not_before IS NOT NULL)))
			AND (TRUE)
		ORDER BY c.updated_at DESC

-- ============================================================
-- certificate_chain_valid  [shape: certificate, subject: certificate]
SELECT
			c.id AS subject_id,
			c.tenant_id AS tenant_id,
			c.updated_at AS measured_at,
			c.is_self_signed AS col_0,
			c.common_name AS col_1,
			c.issuer_dn AS col_2
		FROM certificates c
		WHERE c.tenant_id = $1
			AND ($2::uuid IS NULL OR c.id = $2)
			AND c.is_ca_certificate = false
			AND (TRUE)
			AND (TRUE)
		ORDER BY c.updated_at DESC

-- ============================================================
-- cipher_suite_name  [shape: crypto_configuration, subject: asset]
SELECT
			na.id AS subject_id,
			ci.tenant_id AS tenant_id,
			ci.last_verified_at AS measured_at,
			ci.cipher_suite AS col_0,
			na.hostname AS col_1,
			host(CASE WHEN ci.endpoint_id IS NULL THEN na.primary_address ELSE e.address END) AS col_2,
			e.fqdn AS col_3,
			e.port AS col_4,
			ci.id AS col_5
		FROM crypto_implementations ci
			JOIN assets na ON na.tenant_id = ci.tenant_id AND na.id = ci.asset_id
			LEFT JOIN asset_endpoints e ON e.tenant_id = ci.tenant_id AND e.id = ci.endpoint_id
		WHERE ci.tenant_id = $1
			AND na.deleted_at IS NULL
			AND ci.deleted_at IS NULL
			AND ($2::uuid IS NULL OR na.id = $2)
			AND ((ci.cipher_suite IS NOT NULL))
			AND (TRUE)
		ORDER BY ci.last_verified_at DESC

-- ============================================================
-- config_kex_pqc_status  [shape: crypto_configuration, subject: asset]
SELECT
			na.id AS subject_id,
			ci.tenant_id AS tenant_id,
			ci.last_verified_at AS measured_at,
			ci.key_exchange_algorithm AS col_0,
			na.hostname AS col_1,
			host(CASE WHEN ci.endpoint_id IS NULL THEN na.primary_address ELSE e.address END) AS col_2,
			e.fqdn AS col_3,
			e.port AS col_4,
			ci.id AS col_5,
			ci.cipher_suite AS col_6
		FROM crypto_implementations ci
			JOIN assets na ON na.tenant_id = ci.tenant_id AND na.id = ci.asset_id
			LEFT JOIN asset_endpoints e ON e.tenant_id = ci.tenant_id AND e.id = ci.endpoint_id
		WHERE ci.tenant_id = $1
			AND na.deleted_at IS NULL
			AND ci.deleted_at IS NULL
			AND ($2::uuid IS NULL OR na.id = $2)
			AND ((ci.key_exchange_algorithm IS NOT NULL))
			AND (TRUE)
		ORDER BY ci.last_verified_at DESC

-- ============================================================
-- config_sig_pqc_status  [shape: crypto_configuration, subject: asset]
SELECT
			na.id AS subject_id,
			ci.tenant_id AS tenant_id,
			ci.last_verified_at AS measured_at,
			ci.signature_algorithm AS col_0,
			na.hostname AS col_1,
			host(CASE WHEN ci.endpoint_id IS NULL THEN na.primary_address ELSE e.address END) AS col_2,
			e.fqdn AS col_3,
			e.port AS col_4,
			ci.id AS col_5,
			ci.cipher_suite AS col_6
		FROM crypto_implementations ci
			JOIN assets na ON na.tenant_id = ci.tenant_id AND na.id = ci.asset_id
			LEFT JOIN asset_endpoints e ON e.tenant_id = ci.tenant_id AND e.id = ci.endpoint_id
		WHERE ci.tenant_id = $1
			AND na.deleted_at IS NULL
			AND ci.deleted_at IS NULL
			AND ($2::uuid IS NULL OR na.id = $2)
			AND ((ci.signature_algorithm IS NOT NULL))
			AND (TRUE)
		ORDER BY ci.last_verified_at DESC

-- ============================================================
-- config_sym_strength  [shape: crypto_configuration, subject: asset]
SELECT
			na.id AS subject_id,
			ci.tenant_id AS tenant_id,
			ci.last_verified_at AS measured_at,
			ci.symmetric_encryption AS col_0,
			na.hostname AS col_1,
			host(CASE WHEN ci.endpoint_id IS NULL THEN na.primary_address ELSE e.address END) AS col_2,
			e.fqdn AS col_3,
			e.port AS col_4,
			ci.id AS col_5,
			ci.cipher_suite AS col_6
		FROM crypto_implementations ci
			JOIN assets na ON na.tenant_id = ci.tenant_id AND na.id = ci.asset_id
			LEFT JOIN asset_endpoints e ON e.tenant_id = ci.tenant_id AND e.id = ci.endpoint_id
		WHERE ci.tenant_id = $1
			AND na.deleted_at IS NULL
			AND ci.deleted_at IS NULL
			AND ($2::uuid IS NULL OR na.id = $2)
			AND ((ci.symmetric_encryption IS NOT NULL))
			AND (TRUE)
		ORDER BY ci.last_verified_at DESC

-- ============================================================
-- duplicate_suspected_count  [shape: finding, subject: asset]
-- $3 = [hygiene]
-- predicate args: [hygiene duplicate_suspected monitoring]
SELECT
			a.id AS subject_id,
			a.tenant_id AS tenant_id,
			now() AS measured_at,
			(SELECT count(*) FROM findings f WHERE f.tenant_id = a.tenant_id AND f.subject_type = 'asset' AND f.subject_id = a.id AND f.detection_state = 'ACTIVE' AND (f.workflow_status <> 'SUPPRESSED' OR f.workflow_status IS NULL) AND (((lower((f.producer)::text) = $4) AND (lower((f.kind)::text) = $5)))) AS col_0,
			a.hostname AS col_1,
			host(a.primary_address) AS col_2,
			a.display_name AS col_3,
			a.class_key AS col_4
		FROM assets a
		WHERE a.tenant_id = $1
			AND a.deleted_at IS NULL
			AND ($2::uuid IS NULL OR a.id = $2)
			AND EXISTS (SELECT 1 FROM producer_assessments pa WHERE pa.tenant_id = a.tenant_id AND pa.asset_id = a.id AND pa.producer = $3)
			AND ((lower((a.asset_status)::text) = $6))
		ORDER BY a.updated_at DESC

-- ============================================================
-- hardware_eos_days  [shape: fact, subject: asset]
-- $3 = [eol.hw.date]
-- predicate args: [monitoring]
SELECT
			a.id AS subject_id,
			af.tenant_id AS tenant_id,
			now() AS measured_at,
			af.value #>> '{}' AS col_0,
			a.hostname AS col_1,
			host(a.primary_address) AS col_2,
			a.display_name AS col_3,
			a.class_key AS col_4,
			NULLIF(af.source_ref, '') AS col_5
		FROM asset_facts af
			JOIN assets a ON a.tenant_id = af.tenant_id AND a.id = af.asset_id
		WHERE af.tenant_id = $1
			AND a.deleted_at IS NULL
			AND ($2::uuid IS NULL OR a.id = $2)
			AND af.key = $3
			AND (af.expires_at IS NULL OR af.expires_at > now())
			AND ((lower((a.asset_status)::text) = $4))
			AND (TRUE)
		ORDER BY af.observed_at DESC

-- ============================================================
-- hash_algorithm  [shape: crypto_configuration, subject: asset]
SELECT
			na.id AS subject_id,
			ci.tenant_id AS tenant_id,
			ci.last_verified_at AS measured_at,
			ci.hash_algorithm AS col_0,
			na.hostname AS col_1,
			host(CASE WHEN ci.endpoint_id IS NULL THEN na.primary_address ELSE e.address END) AS col_2,
			e.fqdn AS col_3,
			e.port AS col_4,
			ci.id AS col_5,
			ci.cipher_suite AS col_6
		FROM crypto_implementations ci
			JOIN assets na ON na.tenant_id = ci.tenant_id AND na.id = ci.asset_id
			LEFT JOIN asset_endpoints e ON e.tenant_id = ci.tenant_id AND e.id = ci.endpoint_id
		WHERE ci.tenant_id = $1
			AND na.deleted_at IS NULL
			AND ci.deleted_at IS NULL
			AND ($2::uuid IS NULL OR na.id = $2)
			AND ((ci.hash_algorithm IS NOT NULL))
			AND (TRUE)
		ORDER BY ci.last_verified_at DESC

-- ============================================================
-- key_exchange_algorithm  [shape: crypto_configuration, subject: asset]
SELECT
			na.id AS subject_id,
			ci.tenant_id AS tenant_id,
			ci.last_verified_at AS measured_at,
			ci.key_exchange_algorithm AS col_0,
			na.hostname AS col_1,
			host(CASE WHEN ci.endpoint_id IS NULL THEN na.primary_address ELSE e.address END) AS col_2,
			e.fqdn AS col_3,
			e.port AS col_4,
			ci.id AS col_5,
			ci.cipher_suite AS col_6
		FROM crypto_implementations ci
			JOIN assets na ON na.tenant_id = ci.tenant_id AND na.id = ci.asset_id
			LEFT JOIN asset_endpoints e ON e.tenant_id = ci.tenant_id AND e.id = ci.endpoint_id
		WHERE ci.tenant_id = $1
			AND na.deleted_at IS NULL
			AND ci.deleted_at IS NULL
			AND ($2::uuid IS NULL OR na.id = $2)
			AND ((ci.key_exchange_algorithm IS NOT NULL))
			AND (TRUE)
		ORDER BY ci.last_verified_at DESC

-- ============================================================
-- key_size  [shape: certificate, subject: certificate]
SELECT
			c.id AS subject_id,
			c.tenant_id AS tenant_id,
			c.updated_at AS measured_at,
			c.public_key_size AS col_0,
			c.common_name AS col_1,
			c.public_key_algorithm AS col_2
		FROM certificates c
		WHERE c.tenant_id = $1
			AND ($2::uuid IS NULL OR c.id = $2)
			AND c.is_ca_certificate = false
			AND ((c.public_key_size IS NOT NULL))
			AND (TRUE)
		ORDER BY c.updated_at DESC

-- ============================================================
-- key_size_ec  [shape: certificate, subject: certificate]
SELECT
			c.id AS subject_id,
			c.tenant_id AS tenant_id,
			c.updated_at AS measured_at,
			c.public_key_size AS col_0,
			c.common_name AS col_1,
			c.public_key_algorithm AS col_2
		FROM certificates c
		WHERE c.tenant_id = $1
			AND ($2::uuid IS NULL OR c.id = $2)
			AND c.is_ca_certificate = false
			AND ((c.public_key_size IS NOT NULL))
			AND (TRUE)
		ORDER BY c.updated_at DESC

-- ============================================================
-- last_seen_days  [shape: asset, subject: asset]
-- predicate args: [monitoring]
SELECT
			a.id AS subject_id,
			a.tenant_id AS tenant_id,
			now() AS measured_at,
			EXTRACT(EPOCH FROM (now() - a.last_seen_at)) / 86400.0 AS col_0,
			a.hostname AS col_1,
			host(a.primary_address) AS col_2,
			a.display_name AS col_3,
			a.class_key AS col_4,
			a.last_seen_at AS col_5
		FROM assets a
		WHERE a.tenant_id = $1
			AND a.deleted_at IS NULL
			AND ($2::uuid IS NULL OR a.id = $2)
			AND ((lower((a.asset_status)::text) = $3))
			AND (TRUE)
		ORDER BY a.updated_at DESC

-- ============================================================
-- mgmt_plaintext  [shape: finding, subject: asset]
-- $3 = [configuration]
-- predicate args: [configuration plaintext_management monitoring]
SELECT
			a.id AS subject_id,
			a.tenant_id AS tenant_id,
			now() AS measured_at,
			(SELECT count(*) FROM findings f WHERE f.tenant_id = a.tenant_id AND f.detection_state = 'ACTIVE' AND (f.workflow_status <> 'SUPPRESSED' OR f.workflow_status IS NULL) AND (((lower((f.producer)::text) = $4) AND (lower((f.kind)::text) = $5))) AND ((f.subject_type = 'asset' AND f.subject_id = a.id) OR (f.subject_type = 'endpoint' AND f.subject_id IN (SELECT e.id FROM asset_endpoints e WHERE e.tenant_id = a.tenant_id AND e.asset_id = a.id)))) AS col_0,
			a.hostname AS col_1,
			host(a.primary_address) AS col_2,
			a.display_name AS col_3,
			a.class_key AS col_4
		FROM assets a
		WHERE a.tenant_id = $1
			AND a.deleted_at IS NULL
			AND ($2::uuid IS NULL OR a.id = $2)
			AND EXISTS (SELECT 1 FROM producer_assessments pa WHERE pa.tenant_id = a.tenant_id AND pa.asset_id = a.id AND pa.producer = $3)
			AND ((lower((a.asset_status)::text) = $6))
		ORDER BY a.updated_at DESC

-- ============================================================
-- orphan_relationship_count  [shape: finding, subject: asset]
-- $3 = [hygiene]
-- predicate args: [hygiene orphan_relationship monitoring]
SELECT
			a.id AS subject_id,
			a.tenant_id AS tenant_id,
			now() AS measured_at,
			(SELECT count(*) FROM findings f JOIN asset_relationships r ON r.id = f.subject_id AND r.tenant_id = f.tenant_id WHERE f.tenant_id = a.tenant_id AND f.subject_type = 'relationship' AND (r.from_asset_id = a.id OR r.to_asset_id = a.id) AND f.detection_state = 'ACTIVE' AND (f.workflow_status <> 'SUPPRESSED' OR f.workflow_status IS NULL) AND (((lower((f.producer)::text) = $4) AND (lower((f.kind)::text) = $5)))) AS col_0,
			a.hostname AS col_1,
			host(a.primary_address) AS col_2,
			a.display_name AS col_3,
			a.class_key AS col_4
		FROM assets a
		WHERE a.tenant_id = $1
			AND a.deleted_at IS NULL
			AND ($2::uuid IS NULL OR a.id = $2)
			AND EXISTS (SELECT 1 FROM producer_assessments pa WHERE pa.tenant_id = a.tenant_id AND pa.asset_id = a.id AND pa.producer = $3)
			AND ((lower((a.asset_status)::text) = $6))
		ORDER BY a.updated_at DESC

-- ============================================================
-- os_eol_days  [shape: fact, subject: asset]
-- $3 = [eol.os.date]
-- predicate args: [monitoring]
SELECT
			a.id AS subject_id,
			af.tenant_id AS tenant_id,
			now() AS measured_at,
			af.value #>> '{}' AS col_0,
			a.hostname AS col_1,
			host(a.primary_address) AS col_2,
			a.display_name AS col_3,
			a.class_key AS col_4,
			NULLIF(af.source_ref, '') AS col_5
		FROM asset_facts af
			JOIN assets a ON a.tenant_id = af.tenant_id AND a.id = af.asset_id
		WHERE af.tenant_id = $1
			AND a.deleted_at IS NULL
			AND ($2::uuid IS NULL OR a.id = $2)
			AND af.key = $3
			AND (af.expires_at IS NULL OR af.expires_at > now())
			AND ((lower((a.asset_status)::text) = $4))
			AND (TRUE)
		ORDER BY af.observed_at DESC

-- ============================================================
-- ot_protocol_encryption  [shape: crypto_configuration, subject: asset]
-- predicate args: [modbus dnp3 mms iccp bacnet bacnet_sc ethernet_ip opc_ua hart_ip s7]
SELECT
			na.id AS subject_id,
			ci.tenant_id AS tenant_id,
			ci.last_verified_at AS measured_at,
			CASE WHEN COALESCE(NULLIF(ci.cipher_suite, ''), '') <> '' OR COALESCE(NULLIF(ci.symmetric_encryption, ''), '') <> '' THEN 'present' ELSE 'absent' END AS col_0,
			ci.protocol::text AS col_1,
			na.hostname AS col_2,
			host(CASE WHEN ci.endpoint_id IS NULL THEN na.primary_address ELSE e.address END) AS col_3,
			e.fqdn AS col_4,
			e.port AS col_5,
			ci.id AS col_6,
			COALESCE(NULLIF(ci.cipher_suite, ''), '') AS col_7
		FROM crypto_implementations ci
			JOIN assets na ON na.tenant_id = ci.tenant_id AND na.id = ci.asset_id
			LEFT JOIN asset_endpoints e ON e.tenant_id = ci.tenant_id AND e.id = ci.endpoint_id
		WHERE ci.tenant_id = $1
			AND na.deleted_at IS NULL
			AND ci.deleted_at IS NULL
			AND ($2::uuid IS NULL OR na.id = $2)
			AND (((lower((ci.protocol)::text) = $3) OR (lower((ci.protocol)::text) = $4) OR (lower((ci.protocol)::text) = $5) OR (lower((ci.protocol)::text) = $6) OR (lower((ci.protocol)::text) = $7) OR (lower((ci.protocol)::text) = $8) OR (lower((ci.protocol)::text) = $9) OR (lower((ci.protocol)::text) = $10) OR (lower((ci.protocol)::text) = $11) OR (lower((ci.protocol)::text) = $12)))
			AND (TRUE)
		ORDER BY ci.last_verified_at DESC

-- ============================================================
-- pfs_support  [shape: crypto_configuration, subject: asset]
SELECT
			na.id AS subject_id,
			ci.tenant_id AS tenant_id,
			ci.last_verified_at AS measured_at,
			ci.key_exchange_algorithm AS col_0,
			na.hostname AS col_1,
			host(CASE WHEN ci.endpoint_id IS NULL THEN na.primary_address ELSE e.address END) AS col_2,
			e.fqdn AS col_3,
			e.port AS col_4,
			ci.id AS col_5
		FROM crypto_implementations ci
			JOIN assets na ON na.tenant_id = ci.tenant_id AND na.id = ci.asset_id
			LEFT JOIN asset_endpoints e ON e.tenant_id = ci.tenant_id AND e.id = ci.endpoint_id
		WHERE ci.tenant_id = $1
			AND na.deleted_at IS NULL
			AND ci.deleted_at IS NULL
			AND ($2::uuid IS NULL OR na.id = $2)
			AND ((ci.key_exchange_algorithm IS NOT NULL))
			AND (TRUE)
		ORDER BY ci.last_verified_at DESC

-- ============================================================
-- software_eol_days  [shape: fact, subject: asset]
-- $3 = [eol.sw.date]
-- predicate args: [monitoring]
SELECT
			a.id AS subject_id,
			af.tenant_id AS tenant_id,
			now() AS measured_at,
			af.value #>> '{}' AS col_0,
			a.hostname AS col_1,
			host(a.primary_address) AS col_2,
			a.display_name AS col_3,
			a.class_key AS col_4,
			NULLIF(af.source_ref, '') AS col_5
		FROM asset_facts af
			JOIN assets a ON a.tenant_id = af.tenant_id AND a.id = af.asset_id
		WHERE af.tenant_id = $1
			AND a.deleted_at IS NULL
			AND ($2::uuid IS NULL OR a.id = $2)
			AND af.key = $3
			AND (af.expires_at IS NULL OR af.expires_at > now())
			AND ((lower((a.asset_status)::text) = $4))
			AND (TRUE)
		ORDER BY af.observed_at DESC

-- ============================================================
-- symmetric_encryption  [shape: crypto_configuration, subject: asset]
SELECT
			na.id AS subject_id,
			ci.tenant_id AS tenant_id,
			ci.last_verified_at AS measured_at,
			ci.symmetric_encryption AS col_0,
			na.hostname AS col_1,
			host(CASE WHEN ci.endpoint_id IS NULL THEN na.primary_address ELSE e.address END) AS col_2,
			e.fqdn AS col_3,
			e.port AS col_4,
			ci.id AS col_5,
			ci.cipher_suite AS col_6
		FROM crypto_implementations ci
			JOIN assets na ON na.tenant_id = ci.tenant_id AND na.id = ci.asset_id
			LEFT JOIN asset_endpoints e ON e.tenant_id = ci.tenant_id AND e.id = ci.endpoint_id
		WHERE ci.tenant_id = $1
			AND na.deleted_at IS NULL
			AND ci.deleted_at IS NULL
			AND ($2::uuid IS NULL OR na.id = $2)
			AND ((ci.symmetric_encryption IS NOT NULL))
			AND (TRUE)
		ORDER BY ci.last_verified_at DESC

-- ============================================================
-- tls_compression_enabled  [shape: crypto_configuration, subject: asset]
-- predicate args: [tls]
SELECT
			na.id AS subject_id,
			ci.tenant_id AS tenant_id,
			ci.last_verified_at AS measured_at,
			CASE WHEN jsonb_typeof(ci.raw_data -> 'compression') = 'boolean' THEN (ci.raw_data ->> 'compression')::boolean ELSE NULL END AS col_0,
			na.hostname AS col_1,
			host(CASE WHEN ci.endpoint_id IS NULL THEN na.primary_address ELSE e.address END) AS col_2,
			e.fqdn AS col_3,
			e.port AS col_4,
			ci.id AS col_5
		FROM crypto_implementations ci
			JOIN assets na ON na.tenant_id = ci.tenant_id AND na.id = ci.asset_id
			LEFT JOIN asset_endpoints e ON e.tenant_id = ci.tenant_id AND e.id = ci.endpoint_id
		WHERE ci.tenant_id = $1
			AND na.deleted_at IS NULL
			AND ci.deleted_at IS NULL
			AND ($2::uuid IS NULL OR na.id = $2)
			AND ((lower((ci.protocol)::text) = $3))
			AND (TRUE)
		ORDER BY ci.last_verified_at DESC

-- ============================================================
-- tls_version  [shape: crypto_configuration, subject: asset]
-- predicate args: [tls]
SELECT
			na.id AS subject_id,
			ci.tenant_id AS tenant_id,
			ci.last_verified_at AS measured_at,
			ci.protocol_version AS col_0,
			na.hostname AS col_1,
			host(CASE WHEN ci.endpoint_id IS NULL THEN na.primary_address ELSE e.address END) AS col_2,
			e.fqdn AS col_3,
			e.port AS col_4,
			ci.id AS col_5
		FROM crypto_implementations ci
			JOIN assets na ON na.tenant_id = ci.tenant_id AND na.id = ci.asset_id
			LEFT JOIN asset_endpoints e ON e.tenant_id = ci.tenant_id AND e.id = ci.endpoint_id
		WHERE ci.tenant_id = $1
			AND na.deleted_at IS NULL
			AND ci.deleted_at IS NULL
			AND ($2::uuid IS NULL OR na.id = $2)
			AND (((lower((ci.protocol)::text) = $3) AND (ci.protocol_version IS NOT NULL)))
			AND (TRUE)
		ORDER BY ci.last_verified_at DESC
