// Code generated by scripts/generate-permissions.mjs from
// standards/permissions.yaml. DO NOT EDIT — edit the YAML and run
// `make generate`.
package auth

// roleGrantFilter is one system role's permission reconciliation filter. The
// two expressions are SQL predicates over the aliases tr (tenant_roles) and tp
// (tenant_permissions):
//
//	Revoke — selects grants the role must NOT hold (the reconciliation DELETE)
//	Grant  — selects the permissions the role must hold (the INSERT)
//
// They are the same expressions emitted into the seed.sql DO block, from the
// same YAML, so the path a new tenant takes (assignRolePermissions) and the
// path an existing tenant takes on helm upgrade (seed.sql) cannot diverge.
type roleGrantFilter struct {
	Role   string
	Revoke string
	Grant  string
}

// roleGrantFilters is the generated grant matrix, in registry order.
var roleGrantFilters = []roleGrantFilter{
	// Billing + read-only visibility into who has access and basic tenant
	// settings.
	{
		Role:   "billing_admin",
		Revoke: "NOT (tp.resource = 'billing' OR tp.name IN ('settings.read', 'users.read'))",
		Grant:  "(tp.resource = 'billing' OR tp.name IN ('settings.read', 'users.read'))",
	},
	// Everything except billing.update. Gets billing.read so they can see
	// invoices, usage and payment history without being able to alter payment
	// methods or cancel.
	{
		Role:   "tenant_admin",
		Revoke: "tp.name = 'billing.update'",
		Grant:  "tp.name <> 'billing.update'",
	},
	// Operational/security scope + users.read + settings.read for incident
	// response.
	//
	// audit.read is granted BY NAME, not by adding 'audit' to the resource
	// list: the resource form would also hand over audit.manage, which the
	// pre- role switch never gave security_admin (it granted
	// audit.read/security/export only). This filter is a RESOURCE ALLOWLIST —
	// a new resource is not granted unless it is named here, so omitting
	// audit.read entirely would have silently STRIPPED security_admin's audit
	// access in the migration.
	{
		Role:   "security_admin",
		Revoke: "NOT (tp.resource IN ('assets', 'sensors', 'reports', 'compliance', 'pcap', 'discovery', 'alerts') OR tp.name IN ('users.read', 'settings.read', 'audit.read'))",
		Grant:  "(tp.resource IN ('assets', 'sensors', 'reports', 'compliance', 'pcap', 'discovery', 'alerts') OR tp.name IN ('users.read', 'settings.read', 'audit.read'))",
	},
	// Read-only across all operational resources (no billing).
	//
	// NOTE: this filter is action-based, so seeding the `audit`
	// resource hands viewer audit.read automatically. That is a real, if
	// small, WIDENING versus the pre- role switch, which denied every
	// audit.* permission to viewer. It is left in place deliberately: the
	// routes audit.read gates (activity-logs/by-user, /by-resource, the SIEM
	// integration list) are tenant-scoped in the handler, and viewer can
	// already read the same tenant's full audit trail through the ungated
	// GET /activity-logs. Carving `audit` out would make viewer's "read
	// everything non-billing" rule a special case. If audit reads should be
	// privileged, change it HERE — one edit now reaches every mirror.
	{
		Role:   "viewer",
		Revoke: "NOT (tp.action = 'read' AND tp.resource <> 'billing')",
		Grant:  "tp.action = 'read' AND tp.resource <> 'billing'",
	},
	// Read-only integration scope across operational data.
	{
		Role:   "api_user",
		Revoke: "NOT (tp.action = 'read' AND tp.resource IN ('assets', 'sensors', 'reports', 'compliance', 'discovery', 'pcap'))",
		Grant:  "tp.action = 'read' AND tp.resource IN ('assets', 'sensors', 'reports', 'compliance', 'discovery', 'pcap')",
	},
}
