package storage

import (
	"encoding/json"
	"strings"

	"github.com/google/uuid"
)

// ArtifactType represents the type of artifact being stored
type ArtifactType string

const (
	ArtifactTypeTenantBranding   ArtifactType = "tenant_branding"
	ArtifactTypePlatformBranding ArtifactType = "platform_branding"
	ArtifactTypeSensorBinaries   ArtifactType = "sensor_binaries"
	ArtifactTypeReports          ArtifactType = "reports"
	ArtifactTypeAuditLogs        ArtifactType = "audit_logs"
	// ArtifactTypeCBOM stores frozen Cryptographic Bill of Materials artifacts
	// generated by cbom-service. Each upload is one CBOM (CycloneDX 1.6 JSON,
	// SPDX 2.3, or PDF projection) for a single tenant + scope + timestamp.
	ArtifactTypeCBOM ArtifactType = "cbom"
)

// URLStrategy defines how URLs are generated for stored artifacts
type URLStrategy string

const (
	URLStrategyCDN       URLStrategy = "cdn"       // Use base_url + path (public CDN/S3 URL)
	URLStrategyPresigned URLStrategy = "presigned" // Generate presigned S3 URLs (secure, time-limited)
	URLStrategyDirect    URLStrategy = "direct"    // Direct S3 URL (requires public bucket)
)

// StorageConfig represents the full artifact storage configuration
type StorageConfig struct {
	DefaultIntegrationID *uuid.UUID                      `json:"default_integration_id"`
	DefaultBucket        string                          `json:"default_bucket"`
	DefaultRegion        string                          `json:"default_region"`
	ArtifactTypes        map[ArtifactType]ArtifactConfig `json:"artifact_types"`
}

// ArtifactConfig represents configuration for a specific artifact type
type ArtifactConfig struct {
	Enabled       bool        `json:"enabled"`
	Bucket        *string     `json:"bucket,omitempty"`   // nil = use default
	Prefix        string      `json:"prefix"`             // e.g., "tenants/{tenant_id}/branding/"
	BaseURL       *string     `json:"base_url,omitempty"` // CDN base URL
	URLStrategy   URLStrategy `json:"url_strategy"`
	IntegrationID *uuid.UUID  `json:"integration_id,omitempty"` // nil = use default
	MaxFileSizeMB int         `json:"max_file_size_mb,omitempty"`
	AllowedTypes  []string    `json:"allowed_types,omitempty"`          // MIME types
	PresignExpiry int         `json:"presign_expiry_seconds,omitempty"` // Default 3600
}

// GetBucket returns the bucket for this artifact type, falling back to default
func (c *ArtifactConfig) GetBucket(defaultBucket string) string {
	if c.Bucket != nil && *c.Bucket != "" {
		return *c.Bucket
	}
	return defaultBucket
}

// GetIntegrationID returns the integration ID for this artifact type, falling back to default
func (c *ArtifactConfig) GetIntegrationID(defaultID *uuid.UUID) *uuid.UUID {
	if c.IntegrationID != nil {
		return c.IntegrationID
	}
	return defaultID
}

// GetPresignExpiry returns the presign expiry in seconds, with a default of 3600 (1 hour)
func (c *ArtifactConfig) GetPresignExpiry() int {
	if c.PresignExpiry > 0 {
		return c.PresignExpiry
	}
	return 3600
}

// GetMaxFileSize returns max file size in bytes
func (c *ArtifactConfig) GetMaxFileSize() int64 {
	if c.MaxFileSizeMB > 0 {
		return int64(c.MaxFileSizeMB) * 1024 * 1024
	}
	return 5 * 1024 * 1024 // Default 5MB
}

// ResolvePath resolves the object key path with template variables
func (c *ArtifactConfig) ResolvePath(filename string, tenantID *uuid.UUID) string {
	path := c.Prefix

	if tenantID != nil {
		path = strings.ReplaceAll(path, "{tenant_id}", tenantID.String())
	}

	// Ensure path doesn't have double slashes and ends properly
	path = strings.TrimSuffix(path, "/")
	if path != "" {
		path = path + "/"
	}

	return path + filename
}

// IsAllowedType checks if a content type is allowed for this artifact type
func (c *ArtifactConfig) IsAllowedType(contentType string) bool {
	if len(c.AllowedTypes) == 0 {
		return true // No restrictions
	}
	for _, allowed := range c.AllowedTypes {
		if allowed == contentType {
			return true
		}
	}
	return false
}

// DefaultStorageConfig returns the default storage configuration
func DefaultStorageConfig() *StorageConfig {
	return &StorageConfig{
		DefaultIntegrationID: nil,
		DefaultBucket:        "",
		DefaultRegion:        "us-east-1",
		ArtifactTypes: map[ArtifactType]ArtifactConfig{
			ArtifactTypeTenantBranding: {
				Enabled:       false,
				Prefix:        "tenants/{tenant_id}/branding/",
				URLStrategy:   URLStrategyPresigned,
				MaxFileSizeMB: 5,
				AllowedTypes:  []string{"image/png", "image/jpeg", "image/svg+xml", "image/x-icon"},
			},
			ArtifactTypePlatformBranding: {
				Enabled:       false,
				Prefix:        "platform/branding/",
				URLStrategy:   URLStrategyPresigned,
				MaxFileSizeMB: 5,
				AllowedTypes:  []string{"image/png", "image/jpeg", "image/svg+xml", "image/x-icon"},
			},
			ArtifactTypeSensorBinaries: {
				Enabled:     false,
				Prefix:      "sensors/",
				URLStrategy: URLStrategyPresigned,
			},
			ArtifactTypeReports: {
				Enabled:     false,
				Prefix:      "reports/{tenant_id}/",
				URLStrategy: URLStrategyPresigned,
			},
			ArtifactTypeAuditLogs: {
				Enabled:     false,
				Prefix:      "audit/{tenant_id}/",
				URLStrategy: URLStrategyPresigned,
			},
			ArtifactTypeCBOM: {
				Enabled: false,
				// One CBOM artifact per object. Tenant-scoped path. Files are
				// canonical CycloneDX 1.6 JSON; they can grow into tens of MB
				// for large enterprises so we cap at 256 MB (admin can override
				// per-tenant if BYO-storage is configured).
				Prefix:        "cbom/{tenant_id}/",
				URLStrategy:   URLStrategyPresigned,
				MaxFileSizeMB: 256,
				AllowedTypes: []string{
					"application/json", // CycloneDX, SPDX
					"application/pdf",  // PDF projection
					"application/vnd.cyclonedx+json",
				},
				PresignExpiry: 3600,
			},
		},
	}
}

// ParseStorageConfig parses a StorageConfig from JSON bytes
func ParseStorageConfig(data []byte) (*StorageConfig, error) {
	var config StorageConfig
	if err := json.Unmarshal(data, &config); err != nil {
		return nil, err
	}
	return &config, nil
}

// ToJSON serializes the StorageConfig to JSON bytes
func (c *StorageConfig) ToJSON() ([]byte, error) {
	return json.Marshal(c)
}
