// Code generated by scripts/generate-permissions.mjs from
// standards/permissions.yaml. DO NOT EDIT — edit the YAML and run
// `make generate`.
package rbac

// RoleDelegation is ONE named carve-out from the role-assignment grantability
// guard. It is data, not policy code: the guard still refuses everything it
// refused before except the exact pairings listed here.
//
// The general rule is unchanged — an actor may not hand someone a role that
// holds a permission the actor does not personally hold. A delegation says
// that for this one (GrantorRole, GranteeRole) pair the named Permissions do
// not count against that rule. It does NOT give GrantorRole those
// permissions: holding a power and being able to delegate it are different
// things, and keeping them different is the whole point of the exception.
//
// Scope of the exemption, deliberately narrow:
//   - it is keyed on the PAIR of roles, so the grantor cannot reach the
//     permission through any other role;
//   - both roles must be system roles, so a same-named custom role cannot
//     impersonate either end;
//   - it applies only to ASSIGNING a role to a user. Editing a role's
//     permission set (UpdateRolePermissions / CreateTenantRole) is unchanged,
//     so the grantor still cannot mint the permission onto a role of its own.
//
// Permissions is exactly the set GranteeRole holds and GrantorRole lacks; the
// generator computes that gap from the grant filters and fails if this list
// disagrees, so the carve-out can neither widen nor go dead unnoticed.
type RoleDelegation struct {
	GrantorRole string
	GranteeRole string
	Permissions []string
}

// RoleDelegations is the generated delegation table, in registry order.
var RoleDelegations = []RoleDelegation{
	// A tenant admin already controls the tenant; delegating billing authority
	// to a finance contact INSIDE that tenant is administration, not privilege
	// escalation. Without this, the documented "assign Billing Admin to your
	// finance contact" flow was unreachable: tenant_admin is denied
	// billing.update by its own grant filter, so the guard refused the role in
	// every picker that offered it, and a paid subscription could not be
	// managed by anyone in the tenant without an out-of-band database grant.
	//
	// Note what is NOT being done here. Dropping billing.update from
	// tenant_admin's except_names would give tenant admins the permission
	// ITSELF — the ability to change payment methods and cancel the
	// subscription. Being able to delegate a power and holding that power are
	// different things, and the separation is the point.
	{
		GrantorRole: "tenant_admin",
		GranteeRole: "billing_admin",
		Permissions: []string{"billing.update"},
	},
}
