// Code generated by scripts/generate-permissions.mjs from
// standards/permissions.yaml. DO NOT EDIT — edit the YAML and run
// `make generate`.
//
// Role grant predicates, consumed by scripts/audit-permissions.mjs to compute
// the permission x role matrix. These are the same filters emitted into
// scripts/database/seed.sql and services/auth-service/internal/auth/
// role_grants_gen.go, from the same YAML, so the matrix cannot drift from what
// the database actually grants.
//
// Each predicate takes a parsed { name, resource, action } row and returns true
// iff that role gets the permission.
export const ROLE_GRANTS = [
  // Billing + read-only visibility into who has access and basic tenant
  // settings.
  {
    role: 'billing_admin',
    displayName: "Billing Admin",
    description: "Billing + visibility into who has access",
    grants: (p) =>
      (p.resource === 'billing') ||
      (['settings.read', 'users.read'].includes(p.name)),
  },
  // Everything except billing.update. Gets billing.read so they can see
  // invoices, usage and payment history without being able to alter payment
  // methods or cancel.
  {
    role: 'tenant_admin',
    displayName: "Tenant Administrator",
    description: "Everything except billing.update",
    grants: (p) => p.name !== 'billing.update',
  },
  // Operational/security scope + users.read + settings.read for incident
  // response.
  //
  // audit.read is granted BY NAME, not by adding 'audit' to the resource
  // list: the resource form would also hand over audit.manage, which the
  // pre- role switch never gave security_admin (it granted
  // audit.read/security/export only). This filter is a RESOURCE ALLOWLIST —
  // a new resource is not granted unless it is named here, so omitting
  // audit.read entirely would have silently STRIPPED security_admin's audit
  // access in the migration.
  {
    role: 'security_admin',
    displayName: "Security Administrator",
    description: "Operational/security scope + read users/settings",
    grants: (p) =>
      (['assets', 'sensors', 'reports', 'compliance', 'pcap', 'discovery', 'alerts'].includes(p.resource)) ||
      (['users.read', 'settings.read', 'audit.read'].includes(p.name)),
  },
  // Read-only across all operational resources (no billing).
  //
  // NOTE: this filter is action-based, so seeding the `audit`
  // resource hands viewer audit.read automatically. That is a real, if
  // small, WIDENING versus the pre- role switch, which denied every
  // audit.* permission to viewer. It is left in place deliberately: the
  // routes audit.read gates (activity-logs/by-user, /by-resource, the SIEM
  // integration list) are tenant-scoped in the handler, and viewer can
  // already read the same tenant's full audit trail through the ungated
  // GET /activity-logs. Carving `audit` out would make viewer's "read
  // everything non-billing" rule a special case. If audit reads should be
  // privileged, change it HERE — one edit now reaches every mirror.
  {
    role: 'viewer',
    displayName: "Viewer",
    description: "Read-only non-billing",
    grants: (p) => p.action === 'read' && p.resource !== 'billing',
  },
  // Read-only integration scope across operational data.
  {
    role: 'api_user',
    displayName: "API User",
    description: "Read-only integration scope",
    grants: (p) =>
      ['assets', 'sensors', 'reports', 'compliance', 'discovery', 'pcap'].includes(p.resource) && p.action === 'read',
  },
];
