#!/bin/bash

# Generate Development Environment Script
# Creates a .env file with generated ports to avoid conflicts with dev tools
#
# This script is non-interactive and can be called automatically by start-session.sh
#
# Port Strategy:
#   - Fixed ports: API Gateway (8080), Web UI (3000), Admin UI (3006)
#   - Generated ports: NATS, Grafana, Adminer use base 18000 + offset
#   - Database ports: Keep defaults (5432, 6379, 8086) - rarely conflict
#
# Documentation:
#   - See docsv4/development/workflows/registry-first.md

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT_DIR"

BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log() { echo -e "${BLUE}$*${NC}"; }
ok() { echo -e "${GREEN}$*${NC}"; }
warn() { echo -e "${YELLOW}$*${NC}"; }

ENV_FILE=".env"

# =============================================================================
# Port Configuration
# =============================================================================

# Base port for generated auxiliary services (avoids Cursor IDE conflicts)
DEV_PORT_BASE=18000

# Fixed ports (locked for ALB target group compatibility)
API_GATEWAY_PORT=8080
WEB_UI_PORT=3000
ADMIN_UI_PORT=3006

# Generated ports (base + offset)
NATS_CLIENT_PORT=$((DEV_PORT_BASE + 0))    # 18000
NATS_HTTP_PORT=$((DEV_PORT_BASE + 1))      # 18001
GRAFANA_PORT=$((DEV_PORT_BASE + 2))        # 18002
ADMINER_PORT=$((DEV_PORT_BASE + 3))        # 18003

# Database ports (keep defaults - rarely conflict with dev tools)
POSTGRES_PORT=5432
REDIS_PORT=6379
INFLUXDB_PORT=8086

# Service ports (from service-registry.yaml)
AUTH_SERVICE_PORT=8081
INVENTORY_SERVICE_PORT=8082
COMPLIANCE_ENGINE_PORT=8083
CBOM_SERVICE_PORT=8084
SENSOR_MANAGER_PORT=8085
CLUSTER_SENSOR_SERVICE_PORT=8088
ADMIN_SERVICE_PORT=8089
MONITORING_SERVICE_PORT=8091
RESOURCE_TRACKER_SERVICE_PORT=8092
TENANT_HEALTH_SERVICE_PORT=8093
DEVICE_INTERROGATION_SERVICE_PORT=8095
AUDIT_SERVICE_PORT=8096

# =============================================================================
# Generate Environment File
# =============================================================================

log "Generating development environment file..."

cat > "$ENV_FILE" << EOF
# =============================================================================
# Development Environment Configuration
# =============================================================================
# Generated on $(date)
# Generator: scripts/generate-dev-env.sh
#
# This file is gitignored and automatically generated by start-session.sh
# To regenerate: rm .env && ./start-session.sh
#
# Port Strategy:
#   - Fixed ports: API Gateway, Web UI, Admin UI (for ALB compatibility)
#   - Generated ports: NATS, Grafana, Adminer (base ${DEV_PORT_BASE} to avoid conflicts)
#   - Database ports: Standard defaults (rarely conflict)
# =============================================================================

# -----------------------------------------------------------------------------
# Fixed Ports (locked for ALB target group compatibility)
# -----------------------------------------------------------------------------
API_GATEWAY_HOST_PORT=${API_GATEWAY_PORT}
WEB_UI_HOST_PORT=${WEB_UI_PORT}
ADMIN_UI_HOST_PORT=${ADMIN_UI_PORT}

# -----------------------------------------------------------------------------
# Generated Ports (base ${DEV_PORT_BASE} + offset, avoids Cursor IDE conflicts)
# -----------------------------------------------------------------------------
NATS_CLIENT_HOST_PORT=${NATS_CLIENT_PORT}
NATS_HTTP_HOST_PORT=${NATS_HTTP_PORT}
GRAFANA_HOST_PORT=${GRAFANA_PORT}
ADMINER_HOST_PORT=${ADMINER_PORT}

# -----------------------------------------------------------------------------
# Database Ports (standard defaults)
# -----------------------------------------------------------------------------
POSTGRES_HOST_PORT=${POSTGRES_PORT}
REDIS_HOST_PORT=${REDIS_PORT}
INFLUXDB_HOST_PORT=${INFLUXDB_PORT}

# -----------------------------------------------------------------------------
# Service Ports (from service-registry.yaml)
# -----------------------------------------------------------------------------
AUTH_SERVICE_HOST_PORT=${AUTH_SERVICE_PORT}
INVENTORY_SERVICE_HOST_PORT=${INVENTORY_SERVICE_PORT}
COMPLIANCE_ENGINE_HOST_PORT=${COMPLIANCE_ENGINE_PORT}
CBOM_SERVICE_HOST_PORT=${CBOM_SERVICE_PORT}
SENSOR_MANAGER_HOST_PORT=${SENSOR_MANAGER_PORT}
CLUSTER_SENSOR_SERVICE_HOST_PORT=${CLUSTER_SENSOR_SERVICE_PORT}
ADMIN_SERVICE_HOST_PORT=${ADMIN_SERVICE_PORT}
MONITORING_SERVICE_HOST_PORT=${MONITORING_SERVICE_PORT}
RESOURCE_TRACKER_SERVICE_HOST_PORT=${RESOURCE_TRACKER_SERVICE_PORT}
TENANT_HEALTH_SERVICE_HOST_PORT=${TENANT_HEALTH_SERVICE_PORT}
DEVICE_INTERROGATION_SERVICE_HOST_PORT=${DEVICE_INTERROGATION_SERVICE_PORT}
AUDIT_SERVICE_HOST_PORT=${AUDIT_SERVICE_PORT}

# -----------------------------------------------------------------------------
# Development Credentials (safe defaults for local dev)
# -----------------------------------------------------------------------------
POSTGRES_DB=crypto_inventory
POSTGRES_USER=crypto_user
POSTGRES_PASSWORD=crypto_pass_dev

REDIS_PASSWORD=redis_pass_dev

INFLUXDB_USERNAME=admin
INFLUXDB_PASSWORD=adminpass123
INFLUXDB_ORG=crypto-inventory
INFLUXDB_BUCKET=metrics
INFLUXDB_TOKEN=dev-token-1234567890

NATS_USER=nats_user
NATS_PASSWORD=nats_pass_dev

JWT_SECRET=dev-secret-key-change-in-production
JWT_EXPIRY=24h

# Service-to-service HMAC auth secret (shared/serviceauth). Required by every
# backend service that uses serviceauth; see standards/service-registry.yaml
# `required_secrets` per service. Kept in sync with generate-dev-env.mjs.
INTERNAL_AUTH_SECRET=dev-internal-auth-secret-change-in-production

# Platform Integrations Encryption Key
ENCRYPTION_MASTER_KEY=dev-master-key-change-in-production

# -----------------------------------------------------------------------------
# CORS Configuration
# -----------------------------------------------------------------------------
DEV_CORS_ORIGINS=http://localhost:${WEB_UI_PORT},http://localhost:${ADMIN_UI_PORT}

# -----------------------------------------------------------------------------
# Logging
# -----------------------------------------------------------------------------
LOG_LEVEL=debug
GIN_MODE=debug
ENV=development
EOF

ok "Development environment file generated: $ENV_FILE"
log ""
log "Port assignments:"
log "  API Gateway:    http://localhost:${API_GATEWAY_PORT}"
log "  Web UI:         http://localhost:${WEB_UI_PORT}"
log "  Admin UI:       http://localhost:${ADMIN_UI_PORT}"
log "  NATS Client:    localhost:${NATS_CLIENT_PORT}"
log "  NATS HTTP:      http://localhost:${NATS_HTTP_PORT}"
log "  Grafana:        http://localhost:${GRAFANA_PORT}"
log "  Adminer:        http://localhost:${ADMINER_PORT}"
log ""
warn "This file is gitignored - it will not be committed."
