#!/usr/bin/env node
import fs from 'fs-extra';
import os from 'os';
import path from 'path';
import { fileURLToPath } from 'url';
import yaml from 'yaml';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function main() {
  const root = path.resolve(__dirname, '..');
  const registryPath = path.resolve(root, 'standards', 'service-registry.yaml');
  const envFilePath = path.resolve(root, '.env');

  if (!(await fs.pathExists(registryPath))) {
    console.error(`❌ Registry not found: ${registryPath}`);
    process.exit(1);
  }

  console.log('📝 Generating development environment file...');
  console.log('-----------------------------------------');

  // Read registry
  const registry = yaml.parse(await fs.readFile(registryPath, 'utf8'));

  // Extract image versions from registry
  const images = registry.docker_images || {};
  const goBuilder = images.go_builder || 'golang:1.26-alpine';
  const runtime   = images.runtime    || 'alpine:3.24.1';
  const node      = images.node       || 'node:24-alpine';
  const python    = images.python     || 'python:3.11-slim';

  // Extract infrastructure port configuration
  const devPortGen = registry.infrastructure?.dev_port_generation || {};
  const basePort = devPortGen.base_port || 18000;
  const fixedPorts = devPortGen.fixed_ports || {};
  const generatedPorts = devPortGen.generated_ports || {};
  const defaultPorts = devPortGen.default_ports || {};
  const portEnvVars = devPortGen.port_env_vars || {};

  // Calculate fixed ports
  const apiGatewayPort = fixedPorts.api_gateway || 8080;
  const webUIPort = fixedPorts.web_ui || 3000;
  const adminUIPort = fixedPorts.admin_ui || 3006;
  const jaegerUIPort = fixedPorts.jaeger_ui || 16686;

  // Calculate generated ports (base_port + offset)
  const natsClientPort = basePort + (generatedPorts.nats_client || 0);
  const natsHttpPort = basePort + (generatedPorts.nats_http || 1);
  const grafanaPort = basePort + (generatedPorts.grafana || 2);
  const adminerPort = basePort + (generatedPorts.adminer || 3);
  const portainerHttpsPort = basePort + (generatedPorts.portainer || 4);

  // Extract default ports
  const postgresPort = defaultPorts.postgres || 5432;
  const redisPort = defaultPorts.redis || 6379;
  const influxdbPort = defaultPorts.influxdb || 8086;
  const otelGrpcPort = defaultPorts.otel_grpc || 4317;
  const otelHttpPort = defaultPorts.otel_http || 4318;

  // Extract service ports from registry.services
  const servicePorts = {};
  for (const service of registry.services || []) {
    // Check port_env_vars mapping first, then fall back to generated name
    const mappedEnvVar = portEnvVars[service.name];
    const envVar = mappedEnvVar ||
      `${service.name.toUpperCase().replace(/-/g, '_')}_HOST_PORT`;
    servicePorts[service.name] = {
      port: service.external_port,
      envVar: envVar
    };
  }

  // Extract UI ports from registry.ui
  const uiTenantPort = registry.ui?.tenant?.external_port || 3000;
  const uiAdminPort = registry.ui?.admin?.external_port || 3006;

  // Detect LAN hostname and IPs for CORS (enables browser access from non-localhost clients).
  // Excludes loopback and Docker bridge ranges (172.x.x.x).
  const lanIPs = Object.values(os.networkInterfaces())
    .flat()
    .filter((iface) => iface?.family === 'IPv4' && !iface.internal && !iface.address.startsWith('172.'))
    .map((iface) => iface?.address)
    .filter(Boolean);
  const shortHostname = os.hostname();
  const extraOrigins = new Set();
  if (shortHostname && shortHostname !== 'localhost') {
    extraOrigins.add(`http://${shortHostname}:${webUIPort}`);
    extraOrigins.add(`http://${shortHostname}:${adminUIPort}`);
  }
  for (const ip of lanIPs) {
    extraOrigins.add(`http://${ip}:${webUIPort}`);
    extraOrigins.add(`http://${ip}:${adminUIPort}`);
  }
  const extraCorsOrigins = [...extraOrigins].join(',');

  // Generate .env file content
  const now = new Date().toISOString();
  const envContent = `# =============================================================================
# Development Environment Configuration
# =============================================================================
# Generated on ${now}
# Generator: scripts/generate-dev-env.mjs
# Source: standards/service-registry.yaml
#
# This file is gitignored and automatically generated by start-session.sh
# To regenerate: rm .env && ./start-session.sh
#
# Port Strategy:
#   - Fixed ports: API Gateway, Web UI, Admin UI (for ALB compatibility)
#   - Generated ports: NATS, Grafana, Adminer (base ${basePort} to avoid conflicts)
#   - Database ports: Standard defaults (rarely conflict)
# =============================================================================

# -----------------------------------------------------------------------------
# Fixed Ports (locked for ALB target group compatibility)
# -----------------------------------------------------------------------------
${portEnvVars.api_gateway || 'API_GATEWAY_HOST_PORT'}=${apiGatewayPort}
${portEnvVars.web_ui || 'WEB_UI_HOST_PORT'}=${webUIPort}
${portEnvVars.admin_ui || 'ADMIN_UI_HOST_PORT'}=${adminUIPort}

# -----------------------------------------------------------------------------
# Generated Ports (base ${basePort} + offset, avoids Cursor IDE conflicts)
# -----------------------------------------------------------------------------
${portEnvVars.nats_client || 'NATS_CLIENT_HOST_PORT'}=${natsClientPort}
${portEnvVars.nats_http || 'NATS_HTTP_HOST_PORT'}=${natsHttpPort}
${portEnvVars.grafana || 'GRAFANA_HOST_PORT'}=${grafanaPort}
${portEnvVars.adminer || 'ADMINER_HOST_PORT'}=${adminerPort}
${portEnvVars.portainer || 'PORTAINER_HTTPS_HOST_PORT'}=${portainerHttpsPort}

# -----------------------------------------------------------------------------
# Observability Ports
# -----------------------------------------------------------------------------
${portEnvVars.jaeger_ui || 'JAEGER_UI_HOST_PORT'}=${jaegerUIPort}
${portEnvVars.otel_grpc || 'OTEL_GRPC_HOST_PORT'}=${otelGrpcPort}
${portEnvVars.otel_http || 'OTEL_HTTP_HOST_PORT'}=${otelHttpPort}

# -----------------------------------------------------------------------------
# Database Ports (standard defaults)
# -----------------------------------------------------------------------------
${portEnvVars.postgres || 'POSTGRES_HOST_PORT'}=${postgresPort}
${portEnvVars.redis || 'REDIS_HOST_PORT'}=${redisPort}
${portEnvVars.influxdb || 'INFLUXDB_HOST_PORT'}=${influxdbPort}

# -----------------------------------------------------------------------------
# Service Ports (from service-registry.yaml)
# -----------------------------------------------------------------------------
${Object.values(servicePorts).map(s => `${s.envVar}=${s.port}`).join('\n')}

# -----------------------------------------------------------------------------
# Docker Build Images (from service-registry.yaml)
# To update image versions: edit standards/service-registry.yaml then run 'make generate'
# start-session.sh may override these with DHI equivalents when dhi.enabled=true
# -----------------------------------------------------------------------------
GO_BUILDER_IMAGE=${goBuilder}
RUNTIME_IMAGE=${runtime}
NODE_IMAGE=${node}
PYTHON_IMAGE=${python}

# -----------------------------------------------------------------------------
# Development Credentials (safe defaults for local dev)
# -----------------------------------------------------------------------------
POSTGRES_DB=crypto_inventory
POSTGRES_USER=crypto_user
POSTGRES_PASSWORD=crypto_pass_dev

REDIS_PASSWORD=redis_pass_dev

INFLUXDB_USERNAME=admin
INFLUXDB_PASSWORD=adminpass123
INFLUXDB_ORG=crypto-inventory
INFLUXDB_BUCKET=metrics
INFLUXDB_TOKEN=dev-token-1234567890

NATS_USER=nats_user
NATS_PASSWORD=nats_pass_dev

JWT_SECRET=dev-secret-key-change-in-production
JWT_EXPIRY=24h

# Platform Integrations Encryption Key
ENCRYPTION_MASTER_KEY=dev-master-key-change-in-production

# Internal Service Authentication (HMAC-SHA256)
INTERNAL_AUTH_SECRET=dev-internal-auth-secret-change-in-production

# Grafana Admin Password
GRAFANA_ADMIN_PASSWORD=admin

# -----------------------------------------------------------------------------
# CORS Configuration
# -----------------------------------------------------------------------------
# Gateway (Traefik): DEV_CORS_ALLOW_ANY=1 (default) accepts any http(s) browser origin in dev.
# Set DEV_CORS_ALLOW_ANY=0 and TRAEFIK_DEV_EXTRA_CORS_ORIGINS for a strict allowlist instead.
DEV_CORS_ALLOW_ANY=1
DEV_CORS_ORIGINS=http://localhost:${webUIPort},http://localhost:${adminUIPort}${extraCorsOrigins ? ',' + extraCorsOrigins : ''}
# Used only when DEV_CORS_ALLOW_ANY=0 — then run 'make generate-gateway' after changing.
TRAEFIK_DEV_EXTRA_CORS_ORIGINS=${extraCorsOrigins}

# -----------------------------------------------------------------------------
# Logging
# -----------------------------------------------------------------------------
LOG_LEVEL=debug
ENV=development
`;

  // Write .env file
  await fs.writeFile(envFilePath, envContent);

  console.log(`✅ Development environment file generated: .env`);
  console.log('');
  console.log('Port assignments:');
  console.log(`  API Gateway:    http://localhost:${apiGatewayPort}`);
  console.log(`  Web UI:         http://localhost:${webUIPort}`);
  console.log(`  Admin UI:       http://localhost:${adminUIPort}`);
  console.log(`  NATS Client:    localhost:${natsClientPort}`);
  console.log(`  NATS HTTP:      http://localhost:${natsHttpPort}`);
  console.log(`  Grafana:        http://localhost:${grafanaPort}`);
  console.log(`  Adminer:        http://localhost:${adminerPort}`);
  console.log(`  Portainer:      https://localhost:${portainerHttpsPort} (dev UI)`);
  console.log(`  Jaeger UI:      http://localhost:${jaegerUIPort}`);
  console.log(`  OTEL gRPC:      localhost:${otelGrpcPort}`);
  console.log(`  OTEL HTTP:      http://localhost:${otelHttpPort}`);
  console.log('');
  console.log(`⚠️  This file is gitignored - it will not be committed.`);
}

main().catch(err => {
  console.error('❌ Error generating dev environment:', err);
  process.exit(1);
});
