// Code generated by scripts/generate-connectors.mjs from
// standards/connectors.yaml. DO NOT EDIT — edit the YAML and run
// `make generate`.

// Package connectors is the generated registry of external systems the
// platform integrates with (asset-inventory ADR-0004 D5). It replaces the
// knowledge that is currently spread across two CHECK constraints in
// schema.sql, which carry a list of names and nothing else: no kind, no
// direction, no notion of what an integration produces.
//
// In this phase the CHECKs remain the enforcement point for writes and stay
// hand-maintained; `make audit` asserts that every live connector here still
// appears in the CHECK that carries it, so the two cannot drift apart.
package connectors

// Connector keys.
const (
	ConnectorAWS            = "aws"
	ConnectorAzure          = "azure"
	ConnectorGCP            = "gcp"
	ConnectorSlack          = "slack"
	ConnectorPagerduty      = "pagerduty"
	ConnectorDatadog        = "datadog"
	ConnectorSplunk         = "splunk"
	ConnectorGithub         = "github"
	ConnectorGitlab         = "gitlab"
	ConnectorBitbucket      = "bitbucket"
	ConnectorHashicorpVault = "hashicorp_vault"
	ConnectorCustom         = "custom"
	ConnectorServicenow     = "servicenow"
	ConnectorDevice42       = "device42"
	ConnectorSolarwinds     = "solarwinds"
	ConnectorOomnitza       = "oomnitza"
	ConnectorNetbox         = "netbox"
	ConnectorJira           = "jira"
	ConnectorIntune         = "intune"
	ConnectorJamf           = "jamf"
	ConnectorOsquery        = "osquery"
	ConnectorSBOMUpload     = "sbom_upload"
)

// Connector kinds.
const (
	KindCloud                = "cloud"
	KindCMDB                 = "cmdb"
	KindNetworkSourceOfTruth = "network_source_of_truth"
	KindITSM                 = "itsm"
	KindSIEM                 = "siem"
	KindNotification         = "notification"
	KindEDRMDM               = "edr_mdm"
	KindSBOMSource           = "sbom_source"
	KindSecretsStore         = "secrets_store"
)

// Direction values.
const (
	DirectionPull = "pull"
	DirectionPush = "push"
	DirectionBoth = "both"
)

// Status values.
//
// The three answer different questions and must not be collapsed:
//
//	StatusLive       an implementation dispatches on this key. [Implementation]
//	                 names the package, and the registry test fails if it does
//	                 not exist.
//	StatusRegistered the schema accepts the key — a row may carry it — but
//	                 nothing dispatches on it. A catalogue shows it; a UI must
//	                 not offer it as addable.
//	StatusPlanned    declared here only. No CHECK carries it, so the database
//	                 would reject a row.
const (
	StatusLive       = "live"
	StatusRegistered = "registered"
	StatusPlanned    = "planned"
)

// Connector is one external system the platform can integrate with.
type Connector struct {
	Key       string `json:"key"`
	Label     string `json:"label"`
	Kind      string `json:"kind"`
	Direction string `json:"direction"`
	// ProducesClasses are asset-class keys this connector can create assets
	// for, as plain strings: standards/asset-classes.yaml owns the class tree.
	// Empty for connectors that produce no assets, such as notification sinks.
	ProducesClasses []string `json:"produces_classes,omitempty"`
	Status          string   `json:"status"`
	// SchemaSource names the CHECK constraint carrying this key while the
	// CHECKs remain hand-maintained. Empty for planned connectors.
	SchemaSource string `json:"schema_source,omitempty"`
	// Feature is the entitlement key (a billable_items key) this connector is
	// gated on, or empty for a Core connector. The EDITION is deliberately not
	// stored here: shared/entitlements.EditionFor(Feature) is the single source
	// for that, and a second copy is a second opinion.
	Feature     string `json:"feature,omitempty"`
	Description string `json:"description"`
}

// All is the generated connector list, in YAML order.
var All = []Connector{
	{
		Key:             "aws",
		Label:           "Amazon Web Services",
		Kind:            "cloud",
		Direction:       "pull",
		ProducesClasses: []string{"compute_instance", "object_storage", "managed_database", "cloud_load_balancer", "serverless_function"},
		Status:          "live",
		SchemaSource:    "platform_integrations",
		Feature:         "",
		Description:     "Pulls EC2, S3, RDS, ELB, Lambda and ACM inventory with placement facts (cloud.account_id, cloud.region, cloud.vpc_id, cloud.subnet_id) and the certificates and keys those services present.",
	},
	{
		Key:             "azure",
		Label:           "Microsoft Azure",
		Kind:            "cloud",
		Direction:       "pull",
		ProducesClasses: []string{"compute_instance", "object_storage", "managed_database", "cloud_load_balancer", "serverless_function", "key_store"},
		Status:          "live",
		SchemaSource:    "platform_integrations",
		Feature:         "",
		Description:     "Pulls virtual machines, storage accounts, SQL databases, application gateways, functions and Key Vault inventory, with subscription and region placement facts.",
	},
	{
		Key:             "gcp",
		Label:           "Google Cloud Platform",
		Kind:            "cloud",
		Direction:       "pull",
		ProducesClasses: []string{"compute_instance", "object_storage", "managed_database", "cloud_load_balancer", "serverless_function"},
		Status:          "live",
		SchemaSource:    "platform_integrations",
		Feature:         "",
		Description:     "Pulls Compute Engine, Cloud Storage, Cloud SQL, load balancers and Cloud Functions inventory, with project and region placement facts.",
	},
	{
		Key:             "slack",
		Label:           "Slack",
		Kind:            "notification",
		Direction:       "push",
		ProducesClasses: nil,
		Status:          "live",
		SchemaSource:    "platform_integrations",
		Feature:         "",
		Description:     "Delivers alerts to a Slack workspace. A sink only: it never reads, and never creates an asset.",
	},
	{
		Key:             "pagerduty",
		Label:           "PagerDuty",
		Kind:            "notification",
		Direction:       "push",
		ProducesClasses: nil,
		Status:          "live",
		SchemaSource:    "platform_integrations",
		Feature:         "",
		Description:     "Raises PagerDuty incidents from alerts. A sink only.",
	},
	{
		Key:             "datadog",
		Label:           "Datadog",
		Kind:            "siem",
		Direction:       "push",
		ProducesClasses: nil,
		Status:          "live",
		SchemaSource:    "platform_integrations",
		Feature:         "",
		Description:     "Ships events and metrics to Datadog. Classified as a siem sink rather than an observability source because nothing is read back: the platform is the producer in this relationship.",
	},
	{
		Key:             "splunk",
		Label:           "Splunk",
		Kind:            "siem",
		Direction:       "push",
		ProducesClasses: nil,
		Status:          "live",
		SchemaSource:    "platform_integrations",
		Feature:         "",
		Description:     "Ships findings and audit events to Splunk (OCSF for event export, per ADR-0005 D6). Push only today; a pull direction would mean treating Splunk as an inventory source, which is a separate decision.",
	},
	{
		Key:             "github",
		Label:           "GitHub",
		Kind:            "sbom_source",
		Direction:       "pull",
		ProducesClasses: nil,
		Status:          "registered",
		SchemaSource:    "platform_integrations",
		Feature:         "",
		Description:     "Reads repository metadata and dependency data. Produces software inventory, not assets — a repository is not a configuration item, and the source-code scanning that once mapped repos to assets was removed because no repository-to-asset mapping ever existed. REGISTERED, NOT LIVE: the platform_integrations CHECK accepts the key, but nothing in the tree dispatches on it — the collector went with the source-code scanning that was deleted.",
	},
	{
		Key:             "gitlab",
		Label:           "GitLab",
		Kind:            "sbom_source",
		Direction:       "pull",
		ProducesClasses: nil,
		Status:          "registered",
		SchemaSource:    "platform_integrations",
		Feature:         "",
		Description:     "Reads project metadata and dependency data. Produces software inventory, not assets. REGISTERED, NOT LIVE: no collector dispatches on this key.",
	},
	{
		Key:             "bitbucket",
		Label:           "Bitbucket",
		Kind:            "sbom_source",
		Direction:       "pull",
		ProducesClasses: nil,
		Status:          "registered",
		SchemaSource:    "platform_integrations",
		Feature:         "",
		Description:     "Reads repository metadata and dependency data. Produces software inventory, not assets. REGISTERED, NOT LIVE: no collector dispatches on this key.",
	},
	{
		Key:             "hashicorp_vault",
		Label:           "HashiCorp Vault",
		Kind:            "secrets_store",
		Direction:       "pull",
		ProducesClasses: []string{"key_store"},
		Status:          "registered",
		SchemaSource:    "platform_integrations",
		Feature:         "",
		Description:     "Reads Vault's own posture — which secret engines and PKI mounts exist, the transit key algorithms and sizes, and PKI role configuration — as key_store assets. Posture only: no secret and no key material is retrieved or stored (CLAUDE.md, \"Collect posture, never key material\"). REGISTERED, NOT LIVE: the key is carried by the platform_integrations CHECK, but no Vault collector exists — it is roadmap (docsv4/internal/roadmap/encryption-detection-opportunities.md). No code dispatches on the type, and the tenant-facing create handler's `oneof` does not accept it, so nothing reaches Vault today.",
	},
	{
		Key:             "custom",
		Label:           "Custom integration",
		Kind:            "cmdb",
		Direction:       "both",
		ProducesClasses: nil,
		Status:          "live",
		SchemaSource:    "platform_integrations",
		Feature:         "",
		Description:     "A tenant-defined integration configured through the generic integration form. Deliberately claims no classes: what a custom integration produces is not knowable from the registry, so nothing downstream may assume a shape for it.",
	},
	{
		Key:             "servicenow",
		Label:           "ServiceNow CMDB",
		Kind:            "cmdb",
		Direction:       "both",
		ProducesClasses: []string{"server", "workstation", "switch", "router", "firewall", "printer", "application", "business_service"},
		Status:          "live",
		SchemaSource:    "cmdb_sync_profiles",
		Feature:         "cmdb_sync",
		Description:     "Two-way sync with the ServiceNow CMDB: pull configuration items as assets, push discovered assets and their relationships back. The class tree is ServiceNow-derived (ADR-0002 D2), so the CI-class mapping is close to identity.",
	},
	{
		Key:             "device42",
		Label:           "Device42",
		Kind:            "cmdb",
		Direction:       "both",
		ProducesClasses: []string{"server", "workstation", "switch", "router", "firewall", "application"},
		Status:          "live",
		SchemaSource:    "cmdb_sync_profiles",
		Feature:         "cmdb_sync",
		Description:     "Two-way sync with a Device42 CMDB.",
	},
	{
		Key:             "solarwinds",
		Label:           "SolarWinds",
		Kind:            "cmdb",
		Direction:       "pull",
		ProducesClasses: []string{"server", "switch", "router", "firewall"},
		Status:          "live",
		SchemaSource:    "cmdb_sync_profiles",
		Feature:         "cmdb_sync",
		Description:     "Pulls monitored nodes from SolarWinds as assets. Pull only: SolarWinds is a monitoring system of record, and pushing discovered devices into it would create nodes it would then try to poll.",
	},
	{
		Key:             "oomnitza",
		Label:           "Oomnitza",
		Kind:            "cmdb",
		Direction:       "both",
		ProducesClasses: []string{"server", "workstation", "mobile", "application"},
		Status:          "live",
		SchemaSource:    "cmdb_sync_profiles",
		Feature:         "cmdb_sync",
		Description:     "Two-way sync with Oomnitza's enterprise technology management inventory.",
	},
	{
		Key:             "netbox",
		Label:           "NetBox",
		Kind:            "network_source_of_truth",
		Direction:       "pull",
		ProducesClasses: []string{"server", "switch", "router", "firewall"},
		Status:          "live",
		SchemaSource:    "connector_connections",
		Feature:         "connector_netbox",
		Description:     "Pulls sites, prefixes, VLANs, device types and devices from NetBox (ADR-0001 D3 Q3, ADR-0004 D5). Sites become location context, prefixes and VLANs become network segments, devices become observations through the identification engine. NetBox is the source of truth for network structure, so the pull direction wins on conflict. Direction is PULL, not both: v1 writes NOTHING back. What NetBox does not know about is surfaced as a read-only Drift view for the network team to act on in NetBox itself — pushing discovered devices into a source of truth would make it a mirror of our guesses rather than a statement of their intent. A push direction is a separate, deliberate decision.",
	},
	{
		Key:             "jira",
		Label:           "Jira",
		Kind:            "itsm",
		Direction:       "push",
		ProducesClasses: nil,
		Status:          "planned",
		SchemaSource:    "",
		Feature:         "",
		Description:     "Creates and updates Jira issues from tickets. Push only, and deliberately so: the boundary review refused a workflow engine, so Jira owns the workflow and the platform owns the finding.",
	},
	{
		Key:             "intune",
		Label:           "Microsoft Intune",
		Kind:            "edr_mdm",
		Direction:       "pull",
		ProducesClasses: []string{"workstation", "mobile"},
		Status:          "planned",
		SchemaSource:    "",
		Feature:         "",
		Description:     "Pulls managed endpoints with their OS, hardware and compliance facts. The managed-endpoint coverage a network-observation-only inventory cannot reach: a laptop that never appears on a monitored segment.",
	},
	{
		Key:             "jamf",
		Label:           "Jamf Pro",
		Kind:            "edr_mdm",
		Direction:       "pull",
		ProducesClasses: []string{"workstation", "mobile"},
		Status:          "planned",
		SchemaSource:    "",
		Feature:         "",
		Description:     "Pulls managed macOS and iOS endpoints with their OS, hardware and software inventory.",
	},
	{
		Key:             "osquery",
		Label:           "osquery",
		Kind:            "edr_mdm",
		Direction:       "pull",
		ProducesClasses: []string{"server", "workstation"},
		Status:          "planned",
		SchemaSource:    "",
		Feature:         "",
		Description:     "Adapter over an existing osquery fleet, reading host facts and software inventory from the customer's own deployment. An adapter, not an embedding: osquery was rejected as a dependency on CGO and licence grounds (ADR-0004), so this consumes results rather than linking the engine.",
	},
	{
		Key:             "sbom_upload",
		Label:           "SBOM upload",
		Kind:            "sbom_source",
		Direction:       "pull",
		ProducesClasses: nil,
		Status:          "planned",
		SchemaSource:    "",
		Feature:         "",
		Description:     "Ingests a CycloneDX 1.6 or SPDX 2.3/3.0 document uploaded by the tenant and turns it into software installs against an existing asset. Produces no assets of its own: an SBOM describes what runs on something, and inventing the something from a document nobody verified is how a CMDB fills with ghosts.",
	},
}

// Kinds is the connector-kind vocabulary, in YAML order.
var Kinds = []string{"cloud", "cmdb", "network_source_of_truth", "itsm", "siem", "notification", "edr_mdm", "sbom_source", "secrets_store"}

var byKey = func() map[string]Connector {
	m := make(map[string]Connector, len(All))
	for _, c := range All {
		m[c.Key] = c
	}
	return m
}()

// Get returns the registry entry for a connector key. The second result is
// false when the key is not registered.
func Get(key string) (Connector, bool) {
	c, ok := byKey[key]
	return c, ok
}

// IsLive reports whether a connector is shipped and reachable — that is,
// whether something in this tree dispatches on the key. A registered or
// planned connector appears in the catalogue so a tenant can see it is coming;
// it is NOT dispatchable, and a caller that treats "in the registry" as "I can
// run this" is the bug this distinction exists to prevent.
func IsLive(key string) bool {
	c, ok := Get(key)
	return ok && c.Status == StatusLive
}

// IsRegistered reports whether the schema accepts this key but nothing
// implements it. Such a connector must be shown as "not yet available", never
// offered as addable.
func IsRegistered(key string) bool {
	c, ok := Get(key)
	return ok && c.Status == StatusRegistered
}

// FeatureFor returns the entitlement key gating a connector, or "" when it is
// Core (free in every edition). The second result is false for an unregistered
// key, which callers must treat as "do not dispatch" rather than as Core.
func FeatureFor(key string) (string, bool) {
	c, ok := Get(key)
	if !ok {
		return "", false
	}
	return c.Feature, true
}

// ByKind returns the connectors of one kind, in registry order.
func ByKind(kind string) []Connector {
	var out []Connector
	for _, c := range All {
		if c.Kind == kind {
			out = append(out, c)
		}
	}
	return out
}
