package services

import (
	"context"
	"database/sql"
	"fmt"
	"log"
	"slices"
	"strings"
	"time"

	"github.com/google/uuid"
)

// IncidentResponseHook handles incident response hooks for compliance logging
// Automatically creates security incidents based on critical log patterns
type IncidentResponseHook struct {
	db              *sql.DB
	securityService IncidentCreator
	enabled         bool
	logger          *log.Logger
}

// IncidentCreator interface for creating security incidents
// This allows decoupling from admin-service dependencies
type IncidentCreator interface {
	CreateSecurityIncident(ctx context.Context, incident SecurityIncident) (*SecurityIncident, error)
}

// SecurityIncident represents a security incident (simplified for monitoring-service)
type SecurityIncident struct {
	ID                   uuid.UUID
	IncidentID           string
	Title                string
	Description          *string
	Severity             string
	Category             string
	Status               string
	Priority             string
	DetectedAt           time.Time
	OccurredAt           *time.Time
	RelatedEvents        []uuid.UUID
	AffectedTenants      []uuid.UUID
	AffectedUsers        []uuid.UUID
	ImpactDescription    *string
	ResponseActions      []string
	RequiresNotification bool
	Metadata             map[string]interface{}
	Tags                 []string
	ComplianceTags       []string
	ReporterID           *uuid.UUID
	Team                 *string
}

// NewIncidentResponseHook creates a new incident response hook service
func NewIncidentResponseHook(db *sql.DB, securityService IncidentCreator, enabled bool) *IncidentResponseHook {
	return &IncidentResponseHook{
		db:              db,
		securityService: securityService,
		enabled:         enabled,
		logger:          log.New(log.Writer(), "[IncidentResponseHook] ", log.LstdFlags),
	}
}

// CheckAndCreateIncident checks if a log entry should trigger an incident and creates one if needed
func (h *IncidentResponseHook) CheckAndCreateIncident(ctx context.Context, metadata *LogMetadata) error {
	if !h.enabled || h.securityService == nil {
		return nil // Hook disabled or no service configured
	}

	// Determine if this log should trigger an incident
	shouldTrigger, incidentData := h.shouldTriggerIncident(metadata)
	if !shouldTrigger {
		return nil
	}

	h.logger.Printf("Triggering incident for log %s: %s", metadata.LogID, incidentData.Title)

	// Create security incident
	incident := SecurityIncident{
		ID:          uuid.New(),
		IncidentID:  "", // Auto-generated by service
		Title:       incidentData.Title,
		Description: incidentData.Description,
		Severity:    incidentData.Severity,
		Category:    incidentData.Category,
		Status:      "open",
		Priority:    incidentData.Priority,
		DetectedAt:  metadata.Timestamp,
		OccurredAt:  &metadata.Timestamp,
		Metadata: map[string]interface{}{
			"log_id":          metadata.LogID,
			"service_name":    metadata.ServiceName,
			"event_type":      metadata.EventType,
			"severity":        metadata.Severity,
			"correlation_id":  metadata.CorrelationID,
			"trace_id":        metadata.TraceID,
			"pii_detected":    metadata.PIIDetected,
			"pii_types":       metadata.PIITypes,
			"compliance_tags": metadata.ComplianceTags,
		},
		Tags:                 []string{"auto-generated", "log-triggered"},
		ComplianceTags:       metadata.ComplianceTags,
		RequiresNotification: incidentData.RequiresNotification,
	}

	// Add affected entities
	if metadata.TenantID != nil {
		incident.AffectedTenants = []uuid.UUID{*metadata.TenantID}
	}
	if metadata.UserID != nil {
		incident.AffectedUsers = []uuid.UUID{*metadata.UserID}
	}

	// Add response actions based on incident type
	incident.ResponseActions = h.getResponseActions(incidentData.Category, metadata)

	// Create incident via service
	_, err := h.securityService.CreateSecurityIncident(ctx, incident)
	if err != nil {
		return fmt.Errorf("failed to create security incident: %w", err)
	}

	h.logger.Printf("Created incident for log %s successfully", metadata.LogID)
	return nil
}

// IncidentTriggerData represents data for creating an incident from a log
type IncidentTriggerData struct {
	Title                string
	Description          *string
	Severity             string
	Category             string
	Priority             string
	RequiresNotification bool
}

// shouldTriggerIncident determines if a log entry should trigger an incident
func (h *IncidentResponseHook) shouldTriggerIncident(metadata *LogMetadata) (bool, IncidentTriggerData) {
	// PII breach detection - critical for GDPR compliance
	if metadata.PIIDetected && slices.Contains(metadata.ComplianceTags, "gdpr") {
		return true, IncidentTriggerData{
			Title: fmt.Sprintf("PII Detected in %s Logs", metadata.ServiceName),
			Description: stringPtr(fmt.Sprintf(
				"Personal Identifiable Information (PII) detected in logs from service '%s'. "+
					"PII types detected: %s. Log ID: %s. This may require GDPR notification.",
				metadata.ServiceName, strings.Join(metadata.PIITypes, ", "), metadata.LogID,
			)),
			Severity:             "high",
			Category:             "data_breach",
			Priority:             "high",
			RequiresNotification: true,
		}
	}

	// Critical security errors
	if metadata.Severity == "critical" && slices.Contains(metadata.ComplianceTags, "security") {
		return true, IncidentTriggerData{
			Title: fmt.Sprintf("Critical Security Event in %s", metadata.ServiceName),
			Description: stringPtr(fmt.Sprintf(
				"Critical security event detected in service '%s'. "+
					"Event type: %s. Category: %s. Log ID: %s",
				metadata.ServiceName, metadata.EventType, metadata.Category, metadata.LogID,
			)),
			Severity:             "critical",
			Category:             "unauthorized_access",
			Priority:             "critical",
			RequiresNotification: false, // May require notification based on further investigation
		}
	}

	// Authentication failures with suspicious patterns
	if metadata.EventType == "auth" && metadata.Severity == "error" {
		if metadata.ResponseStatus != nil && *metadata.ResponseStatus == 401 {
			// Multiple 401 errors might indicate brute force attack
			// Check if there are recent similar failures (simplified check)
			return true, IncidentTriggerData{
				Title: fmt.Sprintf("Authentication Failure Pattern in %s", metadata.ServiceName),
				Description: stringPtr(fmt.Sprintf(
					"Authentication failure detected in service '%s'. "+
						"Request path: %s. Source IP: %s. This may indicate a brute force attack.",
					metadata.ServiceName, metadata.RequestPath, getSourceIP(metadata.SourceIP),
				)),
				Severity:             "medium",
				Category:             "unauthorized_access",
				Priority:             "medium",
				RequiresNotification: false,
			}
		}
	}

	// High-severity errors in security-related services
	if metadata.Severity == "error" && slices.Contains(metadata.ComplianceTags, "security") {
		if metadata.ServiceName == "auth-service" || metadata.ServiceName == "admin-service" {
			return true, IncidentTriggerData{
				Title: fmt.Sprintf("Security Error in %s", metadata.ServiceName),
				Description: stringPtr(fmt.Sprintf(
					"High-severity error detected in security-critical service '%s'. "+
						"Event type: %s. Log ID: %s",
					metadata.ServiceName, metadata.EventType, metadata.LogID,
				)),
				Severity:             "high",
				Category:             "compliance_violation",
				Priority:             "high",
				RequiresNotification: false,
			}
		}
	}

	return false, IncidentTriggerData{}
}

// getResponseActions returns recommended response actions based on incident category
func (h *IncidentResponseHook) getResponseActions(category string, metadata *LogMetadata) []string {
	actions := []string{}

	switch category {
	case "data_breach":
		actions = append(actions,
			"1. Isolate affected systems",
			"2. Preserve logs and evidence",
			"3. Assess scope of data exposure",
			"4. Review GDPR notification requirements",
			"5. Engage legal and compliance teams",
		)
	case "unauthorized_access":
		actions = append(actions,
			"1. Block suspicious IP addresses",
			"2. Review authentication logs",
			"3. Check for privilege escalation",
			"4. Verify user account status",
			"5. Review access patterns",
		)
	case "compliance_violation":
		actions = append(actions,
			"1. Review compliance requirements",
			"2. Document the violation",
			"3. Assess impact on compliance status",
			"4. Implement remediation steps",
		)
	default:
		actions = append(actions,
			"1. Review incident details",
			"2. Assess impact",
			"3. Determine response plan",
		)
	}

	return actions
}

func stringPtr(s string) *string {
	return &s
}

func getSourceIP(sourceIP *string) string {
	if sourceIP == nil {
		return "unknown"
	}
	return *sourceIP
}

// NotificationIncidentCreator implements IncidentCreator by fanning out to the monitoring notification service.
type NotificationIncidentCreator struct {
	notifier *NotificationService
}

// NewNotificationIncidentCreator builds an incident creator that reuses configured monitoring notification channels.
func NewNotificationIncidentCreator(notifier *NotificationService) *NotificationIncidentCreator {
	return &NotificationIncidentCreator{notifier: notifier}
}

// CreateSecurityIncident sends incident notifications via the configured channels.
func (n *NotificationIncidentCreator) CreateSecurityIncident(ctx context.Context, incident SecurityIncident) (*SecurityIncident, error) {
	if n == nil || n.notifier == nil {
		return &incident, nil
	}

	channels, err := n.notifier.GetNotificationChannels()
	if err != nil {
		return nil, fmt.Errorf("failed to load notification channels: %w", err)
	}

	message := incident.Title
	if incident.Description != nil && *incident.Description != "" {
		message = *incident.Description
	}

	alert := &AlertNotification{
		ThresholdName: incident.Title,
		ServiceName:   "monitoring-service",
		MetricType:    incident.Category,
		Severity:      incident.Severity,
		Threshold:     0,
		ActualValue:   0,
		Message:       message,
		Timestamp:     time.Now(),
		Metadata: map[string]interface{}{
			"incident_id": incident.IncidentID,
			"log_id":      incident.Metadata["log_id"],
			"priority":    incident.Priority,
		},
	}

	for i := range channels {
		channel := channels[i]
		if err := n.notifier.SendNotification(&channel, alert); err != nil {
			log.Printf("[IncidentResponseHook] failed to send notification via %s: %v", channel.ChannelName, err)
		}
	}

	return &incident, nil
}
