// Code generated by scripts/generate-findings-registry.mjs from
// standards/findings-registry.yaml. DO NOT EDIT — edit the YAML and run
// `make generate`.
//
// The finding registry for the TypeScript side — producers, the kinds each one
// emits, and the shared subject vocabulary. The Go mirror is
// shared/findings/registry_gen.go; both come from the same YAML, and
// `make audit` fails if either drifts.
//
// The query language's `finding` target publishes producer, kind and
// subject_type as closed value sets (QUERY_LANGUAGE §4.3), and
// `query/registry-fields.gen.ts` reads all three from here rather than
// repeating them.
//
// There is no `validate()` here, unlike the Go mirror. Go's is the enforcement
// point for WRITES — the findings table carries no CHECK constraint — and
// nothing in a browser writes a finding. A TypeScript copy of that rule would
// be a second opinion about something the server owns.

/** How a kind's severity is decided. */
export type FindingSeverityModel =
  | 'fixed'
  | 'ladder';

/** Where a kind's score comes from. `catalogue` and `cvss_x10` are resolved at
 *  evaluation time, not from this registry. */
export type FindingScoreSource =
  | 'fixed'
  | 'catalogue'
  | 'cvss_x10'
  | 'ladder';

/** A severity a kind may declare. `from-control` and `from-catalogue` defer to
 *  the control or the algorithm catalogue the finding came from. */
export type FindingSeverity =
  | 'critical'
  | 'high'
  | 'medium'
  | 'low'
  | 'info'
  | 'from-control'
  | 'from-catalogue';

/** Every registered producer key. */
export type FindingProducerKey =
  | 'compliance'
  | 'crypto'
  | 'eol'
  | 'vulnerability'
  | 'configuration'
  | 'hygiene'
  | 'drift';

/** Every registered kind key. Kind keys are unique across the whole registry,
 *  not just within a producer, so a finding row is readable from its kind
 *  alone. */
export type FindingKindKey =
  | 'control_noncompliant'
  | 'weak_configuration'
  | 'weak_certificate'
  | 'pqc_vulnerable'
  | 'os_end_of_life'
  | 'software_end_of_life'
  | 'hardware_end_of_support'
  | 'known_vulnerability'
  | 'plaintext_management'
  | 'default_credentials_exposed'
  | 'insecure_service_exposed'
  | 'no_owner'
  | 'no_class'
  | 'no_location'
  | 'duplicate_suspected'
  | 'stale'
  | 'orphan_relationship'
  | 'new_class_in_segment'
  | 'unexpected_protocol'
  | 'port_profile_changed'
  | 'new_issuer';

/** What a finding (or a ticket, or an alert) can be about. */
export type FindingSubjectType =
  | 'asset'
  | 'endpoint'
  | 'certificate'
  | 'key'
  | 'crypto_configuration'
  | 'software_install'
  | 'relationship'
  | 'control'
  | 'framework';

/** One step of a ladder severity model. Rungs are ordered worst-last. */
export interface FindingRung {
  threshold: string;
  severity: FindingSeverity;
  score: number;
}

/** One finding producer: a subsystem that judges facts against a catalogue or
 *  a rule set. */
export interface FindingProducer {
  key: FindingProducerKey;
  label: string;
  /** The catalogue it judges against, or 'none' where there is not one. */
  catalogue: string;
  description: string;
}

/** One finding kind a producer may emit. */
export interface FindingKind {
  producer: FindingProducerKey;
  key: FindingKindKey;
  severityModel: FindingSeverityModel;
  /** Absent on a ladder kind, which carries a severity per rung. */
  defaultSeverity?: FindingSeverity;
  score: number;
  scoreSource: FindingScoreSource;
  /** Only a ladder kind has rungs. */
  rungs?: readonly FindingRung[];
  subjectTypes: readonly FindingSubjectType[];
  /** Whether the finding contributes to the asset risk rollup. */
  feedsRisk: boolean;
  titleTemplate: string;
  /**
   * Customer-facing remediation guidance: what a person does about a finding
   * of this kind. Generic to the kind, never to one instance.
   *
   * It is also the remediator seam's null default (ADR-0008 D1) — a deployment
   * with no model configured answers "draft me a plan" with exactly this — so
   * it has to stand on its own. Not the description field, which is ours.
   */
  guidance: string;
  description: string;
}

/** The producer list, in registry order. */
export const FINDING_PRODUCERS: readonly FindingProducer[] = [
  {
    key: 'compliance',
    label: 'Compliance',
    catalogue: 'frameworks',
    description: 'Evaluates activated framework controls against tenant inventory and records the controls that fail.',
  },
  {
    key: 'crypto',
    label: 'Cryptography',
    catalogue: 'algorithms',
    description: 'Judges observed cryptographic posture — negotiated configurations, certificates and their algorithms — against the algorithms catalogue.',
  },
  {
    key: 'eol',
    label: 'End of life',
    catalogue: 'eol_catalogue',
    description: 'Compares observed operating systems, software and hardware against the end-of-life catalogue.',
  },
  {
    key: 'vulnerability',
    label: 'Vulnerability',
    catalogue: 'vulnerability_catalogue',
    description: 'Matches installed software against the mirrored vulnerability catalogue by CPE and Package URL.',
  },
  {
    key: 'configuration',
    label: 'Configuration',
    catalogue: 'configuration_rules',
    description: 'Judges how a device is managed and what it exposes, from endpoint and interrogation facts, against the configuration rule table.',
  },
  {
    key: 'hygiene',
    label: 'Inventory hygiene',
    catalogue: 'none',
    description: 'Reports gaps in the inventory itself — missing ownership, missing classification, suspected duplicates, stale records. Data quality, not security: nothing here feeds risk.',
  },
  {
    key: 'drift',
    label: 'Drift',
    catalogue: 'none',
    description: 'Compares the current population of a segment or an asset against its recent baseline window and reports what changed. Rule-based defaults first; the ADR-0008 drift seam may propose more later.',
  },
];

/** The finding-kind list, in registry order. */
export const FINDING_KINDS: readonly FindingKind[] = [
  {
    producer: 'compliance',
    key: 'control_noncompliant',
    severityModel: 'fixed',
    defaultSeverity: 'from-control',
    score: 0,
    scoreSource: 'fixed',
    subjectTypes: ['asset', 'certificate'],
    feedsRisk: false,
    titleTemplate: 'Control {subject} is noncompliant',
    guidance: 'Open the control to see which measurement failed and what it expected. Fix the underlying object — the asset or the certificate the measurement was taken on — and the next evaluation closes the finding. Where the requirement genuinely does not apply here, record a control override with a rationale rather than leaving the finding open.',
    description: 'A published framework\'s control failed evaluation against one concrete object. The subject is the object the measurement was taken on — the asset, or the certificate — and `control_id` names the control it failed. One finding per (control, subject) pair, which is the granularity a tenant triages, assigns and raises a ticket at.\nWritten as `[control]` when the registry first landed, before the writer moved (workstream 3.1). A control-subject finding cannot be reached by `finding:(…)` from an asset, cannot be counted by the `has_findings` facet, and cannot carry a per-asset assignment — all three are live product surfaces, so the subject is the object, not the control.\nThe retired compliance table\'s three-value asset-kind CHECK maps onto TWO: network_asset → asset, crypto_implementation → asset, certificate → certificate. `asset_type` there named the measurement KIND, not the type of the id beside it — `asset_id` was always the asset\'s for the first two — so renaming the third value to `crypto_configuration` would have made every one of those rows claim to point at a `crypto_implementations.id` it has never held. A configuration measurement is scoped and selected per ASSET; the configurations it was taken over travel in `evidence.crypto_implementation_ids`.\n`crypto_configuration` is RESERVED for the `configuration` producer below (workstream 3.5), which measures one configuration at a time and carries its id. Do not add it back here without a writer that actually puts a crypto_implementations.id in subject_id.\nDoes not feed the per-asset risk rollup: compliance is scored by the framework score, and double-counting a control across every asset it touches would swamp the rollup.',
  },
  {
    producer: 'crypto',
    key: 'weak_configuration',
    severityModel: 'fixed',
    defaultSeverity: 'from-catalogue',
    score: 0,
    scoreSource: 'catalogue',
    subjectTypes: ['crypto_configuration', 'endpoint'],
    feedsRisk: true,
    titleTemplate: 'Weak cryptographic configuration on {subject}',
    guidance: 'Reconfigure the service to stop offering the weak component the catalogue flagged: disable the obsolete protocol version, remove the cipher suite from the server\'s list, or move the key exchange to a modern curve. Change it on the service itself, not on the client — a client-side workaround leaves the endpoint willing to negotiate the weak option with anything else that asks. Re-scan the endpoint afterwards to confirm the new negotiation.',
    description: 'A crypto configuration negotiates a protocol version, cipher suite, key exchange, signature, symmetric or hash algorithm the catalogue rates as weak or deprecated. Score is the algorithms.risk_score of the worst linked component (worst-component-wins); severity follows from banding that score. Never hardcode a second opinion here — edit the catalogue row.',
  },
  {
    producer: 'crypto',
    key: 'weak_certificate',
    severityModel: 'fixed',
    defaultSeverity: 'from-catalogue',
    score: 0,
    scoreSource: 'catalogue',
    subjectTypes: ['certificate'],
    feedsRisk: true,
    titleTemplate: 'Certificate {subject} uses weak cryptography',
    guidance: 'Reissue the certificate with a key and signature algorithm the catalogue rates acceptable — for RSA that means at least 2048 bits, and SHA-256 or better for the signature. Replace it everywhere it is deployed, then revoke the old one so a copy left on another host cannot still be used.',
    description: 'A certificate\'s key algorithm, key size or signature algorithm is rated weak by the catalogue, or falls below an SP 800-131A floor. Expiry is an alert (certificate_expiring), not a finding.',
  },
  {
    producer: 'crypto',
    key: 'pqc_vulnerable',
    severityModel: 'fixed',
    defaultSeverity: 'medium',
    score: 40,
    scoreSource: 'fixed',
    subjectTypes: ['crypto_configuration', 'certificate', 'key'],
    feedsRisk: true,
    titleTemplate: '{subject} is vulnerable to quantum attack',
    guidance: 'Plan a migration to a post-quantum or hybrid algorithm for this subject. Nothing here is broken today: NIST IR 8547 deprecates these primitives in 2030 and disallows them in 2035, so the work is inventory-led — confirm what depends on this key or configuration, check whether the software and the peers support a PQC or hybrid option yet, and schedule the change. Long-lived data protected by this key is the part to prioritise.',
    description: 'The subject uses a classical asymmetric primitive broken by Shor\'s algorithm (signature, kem, key-agree, pke) per NIST IR 8547. Classification is the denylist in pqc_readiness.go — a subject not classified is unclassified, never assumed safe.',
  },
  {
    producer: 'eol',
    key: 'os_end_of_life',
    severityModel: 'ladder',
    score: 0,
    scoreSource: 'ladder',
    rungs: [
      { threshold: 'within 90 days of end of life', severity: 'low', score: 30 },
      { threshold: 'past end of life', severity: 'high', score: 70 },
      { threshold: 'past end of life by more than 365 days', severity: 'critical', score: 90 },
    ],
    subjectTypes: ['asset'],
    feedsRisk: true,
    titleTemplate: '{subject} runs an end-of-life operating system ({detail})',
    guidance: 'Upgrade the operating system to a release that is still supported, or move the workload to a host that runs one. An end-of-life OS receives no security fixes, so the exposure grows with every advisory published after the date. Where an upgrade is genuinely blocked, isolate the host and record the compensating controls.',
    description: 'The asset\'s os.name/os.version facts resolve to a catalogue entry whose end-of-life date has passed or is approaching. Escalates as the date recedes.',
  },
  {
    producer: 'eol',
    key: 'software_end_of_life',
    severityModel: 'ladder',
    score: 0,
    scoreSource: 'ladder',
    rungs: [
      { threshold: 'within 90 days of end of life', severity: 'low', score: 20 },
      { threshold: 'past end of life', severity: 'medium', score: 50 },
      { threshold: 'past end of life by more than 365 days', severity: 'high', score: 75 },
    ],
    subjectTypes: ['software_install'],
    feedsRisk: true,
    titleTemplate: '{subject} is end of life ({detail})',
    guidance: 'Upgrade the package to a supported version, or remove it if nothing still needs it. Check what depends on it first — an end-of-life library is often pulled in by something else, and upgrading the dependent is the real fix.',
    description: 'An installed software product has passed, or is approaching, its catalogue end-of-life date. Scored below OS end-of-life because the blast radius of one package is narrower than the platform it runs on.',
  },
  {
    producer: 'eol',
    key: 'hardware_end_of_support',
    severityModel: 'ladder',
    score: 0,
    scoreSource: 'ladder',
    rungs: [
      { threshold: 'within 180 days of end of support', severity: 'low', score: 20 },
      { threshold: 'past end of support', severity: 'medium', score: 50 },
      { threshold: 'past end of support by more than 365 days', severity: 'high', score: 70 },
    ],
    subjectTypes: ['asset'],
    feedsRisk: true,
    titleTemplate: '{subject} hardware is past vendor support ({detail})',
    guidance: 'Plan the hardware refresh. Past end of support the vendor issues no further firmware fixes, so a future advisory against this model has no remedy. Until it is replaced, keep it off management networks reachable from anywhere untrusted.',
    description: 'The asset\'s hw.vendor/hw.model facts resolve to a catalogue entry whose end-of-support date has passed or is approaching. Unsupported hardware stops receiving firmware fixes.',
  },
  {
    producer: 'vulnerability',
    key: 'known_vulnerability',
    severityModel: 'fixed',
    defaultSeverity: 'from-catalogue',
    score: 0,
    scoreSource: 'cvss_x10',
    subjectTypes: ['software_install', 'asset'],
    feedsRisk: true,
    titleTemplate: '{subject} is affected by {detail}',
    guidance: 'Apply the vendor\'s fixed version for this advisory. Where a patch is not available yet, apply the vendor\'s documented mitigation and re-check when one ships. Confirm afterwards that the installed version really changed — the finding closes on the next inventory pass, not on the change ticket.',
    description: 'An installed software version matches a catalogue advisory by CPE or PURL. Score is the CVSS base score x10 (the convention models.RiskBands is anchored to), so severity bands land on the CVSS qualitative ratings. A CVE with no CVSS score scores 0 and is reported as not scored, never as harmless.',
  },
  {
    producer: 'configuration',
    key: 'plaintext_management',
    severityModel: 'fixed',
    defaultSeverity: 'high',
    score: 70,
    scoreSource: 'fixed',
    subjectTypes: ['asset', 'endpoint'],
    feedsRisk: true,
    titleTemplate: '{subject} is managed over a plaintext protocol ({detail})',
    guidance: 'Move management onto the encrypted equivalent — SSH instead of Telnet, HTTPS instead of HTTP, SFTP instead of FTP, SNMPv3 instead of v1 or v2c — and then disable the plaintext service so it cannot be reached at all. Treat any credential used over the plaintext service as exposed and rotate it.',
    description: 'The asset\'s management plane runs over a protocol with no transport confidentiality — Telnet, HTTP, FTP, SNMP v1/v2c. Credentials and configuration cross the network in the clear.',
  },
  {
    producer: 'configuration',
    key: 'default_credentials_exposed',
    severityModel: 'fixed',
    defaultSeverity: 'critical',
    score: 90,
    scoreSource: 'fixed',
    subjectTypes: ['asset', 'endpoint'],
    feedsRisk: true,
    titleTemplate: '{subject} accepts default credentials',
    guidance: 'Change the credential now, on the device itself, and then check whether the same default is in use anywhere else. A vendor default is published, so assume it has been tried. Where the device allows it, disable the default account rather than only changing its password.',
    description: 'A management endpoint accepted a documented vendor default credential. The finding records that it was accepted; it never records the credential itself (see "Collect posture, never key material").',
  },
  {
    producer: 'configuration',
    key: 'insecure_service_exposed',
    severityModel: 'fixed',
    defaultSeverity: 'medium',
    score: 50,
    scoreSource: 'fixed',
    subjectTypes: ['endpoint'],
    feedsRisk: true,
    titleTemplate: '{subject} exposes an insecure service ({detail})',
    guidance: 'Close the port, bind the service to a management interface, or put it behind an authenticating proxy. Decide first whether the service is needed on this segment at all — the cheapest fix is usually removing an exposure nobody was using.',
    description: 'An endpoint listens on a service the rule table rates as unsafe to expose on this segment — an unauthenticated database port, a debug interface, a legacy file-sharing protocol.',
  },
  {
    producer: 'hygiene',
    key: 'no_owner',
    severityModel: 'fixed',
    defaultSeverity: 'low',
    score: 0,
    scoreSource: 'fixed',
    subjectTypes: ['asset'],
    feedsRisk: false,
    titleTemplate: '{subject} has no owner',
    guidance: 'Set an owner email or a support group on the asset. An unowned asset has nobody to send a finding to, which is what makes it the one that stays unfixed.',
    description: 'An asset has no owner_email and no support_group.',
  },
  {
    producer: 'hygiene',
    key: 'no_class',
    severityModel: 'fixed',
    defaultSeverity: 'low',
    score: 0,
    scoreSource: 'fixed',
    subjectTypes: ['asset'],
    feedsRisk: false,
    titleTemplate: '{subject} is unclassified',
    guidance: 'Classify the asset, or add an identification rule that classifies this shape of asset automatically. An unclassified asset is invisible to class facets and to every class-scoped policy, so it is silently excluded from work it should be part of.',
    description: 'An asset has no class, or sits on a placeholder class the classifier could not refine. An unclassified asset is invisible to class facets and to any class-scoped policy.',
  },
  {
    producer: 'hygiene',
    key: 'no_location',
    severityModel: 'fixed',
    defaultSeverity: 'low',
    score: 0,
    scoreSource: 'fixed',
    subjectTypes: ['asset'],
    feedsRisk: false,
    titleTemplate: '{subject} has no location',
    guidance: 'Record a site, region or zone on the asset. Location is what turns a finding into a work order somebody can act on, and it is what scopes an exposure to a building or a plant.',
    description: 'An asset has no site, region, zone or location record.',
  },
  {
    producer: 'hygiene',
    key: 'duplicate_suspected',
    severityModel: 'fixed',
    defaultSeverity: 'medium',
    score: 0,
    scoreSource: 'fixed',
    subjectTypes: ['asset'],
    feedsRisk: false,
    titleTemplate: '{subject} may be a duplicate of {detail}',
    guidance: 'Compare the two records and either merge them through the Approvals queue or record why they are genuinely different. Leaving both means every count that involves this asset is wrong by one, in a direction nobody can see.',
    description: 'The identification engine found two assets sharing an identifier but disagreeing on others, so it did not merge them. The merge proposal goes to Approvals; this finding is how it surfaces in the inventory.',
  },
  {
    producer: 'hygiene',
    key: 'stale',
    severityModel: 'ladder',
    score: 0,
    scoreSource: 'ladder',
    rungs: [
      { threshold: 'not seen for 30 days', severity: 'low', score: 0 },
      { threshold: 'not seen for 90 days', severity: 'medium', score: 0 },
      { threshold: 'not seen for 180 days', severity: 'high', score: 0 },
    ],
    subjectTypes: ['asset', 'endpoint', 'software_install'],
    feedsRisk: false,
    titleTemplate: '{subject} has not been seen for {detail}',
    guidance: 'Confirm whether the subject still exists. If it does, find out why no collector has seen it — a decommissioned sensor, a changed network path, or an agent that stopped reporting. If it does not, archive the record so it stops being counted as part of the estate.',
    description: 'No collector has observed the subject within the freshness window. Stale records are the main way an inventory silently becomes wrong; escalating rungs prompt an archive decision.',
  },
  {
    producer: 'hygiene',
    key: 'orphan_relationship',
    severityModel: 'fixed',
    defaultSeverity: 'low',
    score: 0,
    scoreSource: 'fixed',
    subjectTypes: ['relationship'],
    feedsRisk: false,
    titleTemplate: 'Relationship {subject} points at a missing asset',
    guidance: 'Delete the relationship, or restore the asset it points at if it was archived by mistake. An edge to a missing asset makes dependency views read as complete when they are not.',
    description: 'A relationship edge references an asset that has been archived or deleted. The edge is kept so the history stays readable, but it should be resolved.',
  },
  {
    producer: 'drift',
    key: 'new_class_in_segment',
    severityModel: 'fixed',
    defaultSeverity: 'medium',
    score: 30,
    scoreSource: 'fixed',
    subjectTypes: ['asset'],
    feedsRisk: true,
    titleTemplate: '{subject} is the first {detail} seen in its network segment',
    guidance: 'Confirm whether the asset belongs on this segment. If it does, nothing needs fixing and the finding can be resolved. If it does not, move it — an unexpected class on a segment is usually either a misconfigured port or something nobody meant to plug in.',
    description: 'An asset of a class never before seen in this network segment was observed. A printer on a server VLAN is worth a look; an OT device on a corporate VLAN is worth a call.',
  },
  {
    producer: 'drift',
    key: 'unexpected_protocol',
    severityModel: 'fixed',
    defaultSeverity: 'medium',
    score: 40,
    scoreSource: 'fixed',
    subjectTypes: ['asset', 'endpoint'],
    feedsRisk: true,
    titleTemplate: '{subject} started speaking {detail}',
    guidance: 'Find out what started using the protocol and whether it was a planned change. A newly-appearing plaintext or remote-access protocol is the case worth chasing; where it was intentional, resolve the finding so the baseline picks the new behaviour up.',
    description: 'An asset began using a protocol it has not used in the baseline window. Newly-appearing plaintext or remote-access protocols are the cases that matter.',
  },
  {
    producer: 'drift',
    key: 'port_profile_changed',
    severityModel: 'fixed',
    defaultSeverity: 'low',
    score: 20,
    scoreSource: 'fixed',
    subjectTypes: ['asset'],
    feedsRisk: true,
    titleTemplate: '{subject}\'s listening ports changed ({detail})',
    guidance: 'Compare the current listening ports against what this asset is supposed to run, and confirm the change was planned. Ports opening is the signal to chase first, but a port closing unexpectedly can mean a service has failed rather than been removed.',
    description: 'The set of listening sockets on an asset differs from its baseline. Ports opening is the signal; ports closing is recorded but scored the same because either direction can mean an unplanned change.',
  },
  {
    producer: 'drift',
    key: 'new_issuer',
    severityModel: 'fixed',
    defaultSeverity: 'medium',
    score: 30,
    scoreSource: 'fixed',
    subjectTypes: ['certificate', 'asset'],
    feedsRisk: true,
    titleTemplate: '{subject} presented a certificate from a new issuer ({detail})',
    guidance: 'Confirm the new issuer is one you chose. A planned CA migration explains it and the finding can be resolved; an issuer nobody recognises on a connection that should be direct is what an interception looks like, and is worth treating as one until it is explained.',
    description: 'A certificate was observed from an issuer not seen for this subject in the baseline window. A changed issuer is either a planned CA migration or an interception.',
  },
];

/** The shared finding-subject vocabulary, in registry order. */
export const FINDING_SUBJECT_TYPES: readonly FindingSubjectType[] = ['asset', 'endpoint', 'certificate', 'key', 'crypto_configuration', 'software_install', 'relationship', 'control', 'framework'];

/**
 * What "open" means, in the query language, in ONE place.
 *
 * Both halves are load-bearing. `detection_state` is the finding's own
 * lifecycle (still detected? INACTIVE means it went away) and
 * `workflow_status` is the human one (has anybody dealt with it?). Counting
 * only the first includes findings someone already signed off; counting only
 * the second includes findings that have since been fixed.
 *
 * The facet rail writes this text when its "has open findings" checkbox is
 * ticked, and the server's `has_findings` facet COMPILES the same text to
 * produce the number beside it. The Go half is findings.OpenQuery, generated
 * from the same line of YAML.
 */
export const OPEN_FINDINGS_QUERY = 'finding:(detection_state:ACTIVE and workflow_status not in (RESOLVED, SUPPRESSED))';

/** Producer keys alone, in registry order. */
export const FINDING_PRODUCER_KEYS: readonly FindingProducerKey[] = [
  'compliance',
  'crypto',
  'eol',
  'vulnerability',
  'configuration',
  'hygiene',
  'drift',
];

/** Kind keys alone, in registry order. */
export const FINDING_KIND_KEYS: readonly FindingKindKey[] = [
  'control_noncompliant',
  'weak_configuration',
  'weak_certificate',
  'pqc_vulnerable',
  'os_end_of_life',
  'software_end_of_life',
  'hardware_end_of_support',
  'known_vulnerability',
  'plaintext_management',
  'default_credentials_exposed',
  'insecure_service_exposed',
  'no_owner',
  'no_class',
  'no_location',
  'duplicate_suspected',
  'stale',
  'orphan_relationship',
  'new_class_in_segment',
  'unexpected_protocol',
  'port_profile_changed',
  'new_issuer',
];

/** Producers by symbol, for call sites that prefer a name to a literal. */
export const FINDING_PRODUCER = {
  Compliance: 'compliance',
  Crypto: 'crypto',
  EOL: 'eol',
  Vulnerability: 'vulnerability',
  Configuration: 'configuration',
  Hygiene: 'hygiene',
  Drift: 'drift',
} as const satisfies Record<string, FindingProducerKey>;

/** Kinds by symbol. */
export const FINDING_KIND = {
  ControlNoncompliant: 'control_noncompliant',
  WeakConfiguration: 'weak_configuration',
  WeakCertificate: 'weak_certificate',
  PQCVulnerable: 'pqc_vulnerable',
  OSEndOfLife: 'os_end_of_life',
  SoftwareEndOfLife: 'software_end_of_life',
  HardwareEndOfSupport: 'hardware_end_of_support',
  KnownVulnerability: 'known_vulnerability',
  PlaintextManagement: 'plaintext_management',
  DefaultCredentialsExposed: 'default_credentials_exposed',
  InsecureServiceExposed: 'insecure_service_exposed',
  NoOwner: 'no_owner',
  NoClass: 'no_class',
  NoLocation: 'no_location',
  DuplicateSuspected: 'duplicate_suspected',
  Stale: 'stale',
  OrphanRelationship: 'orphan_relationship',
  NewClassInSegment: 'new_class_in_segment',
  UnexpectedProtocol: 'unexpected_protocol',
  PortProfileChanged: 'port_profile_changed',
  NewIssuer: 'new_issuer',
} as const satisfies Record<string, FindingKindKey>;

/** Subject types by symbol. */
export const FINDING_SUBJECT = {
  Asset: 'asset',
  Endpoint: 'endpoint',
  Certificate: 'certificate',
  Key: 'key',
  CryptoConfiguration: 'crypto_configuration',
  SoftwareInstall: 'software_install',
  Relationship: 'relationship',
  Control: 'control',
  Framework: 'framework',
} as const satisfies Record<string, FindingSubjectType>;

/** The registry entry for a producer key, or undefined when it is not
 *  registered. Mirrors Go's `findings.GetProducer`. */
export function findingProducer(key: string): FindingProducer | undefined {
  return FINDING_PRODUCERS.find((p) => p.key === key);
}

/** The registry entry for a kind key, or undefined when it is not registered.
 *  Mirrors Go's `findings.Get`, which takes the producer as well because it
 *  also checks the pairing; kind keys are unique, so a read needs only the
 *  kind. */
export function findingKind(key: string): FindingKind | undefined {
  return FINDING_KINDS.find((k) => k.key === key);
}
